### ISSUE TITLE
The “How can we improve Relay for you? Let us know.” link for premium accounts is white and almost invisible

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1015]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10, Android 9;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. If there is no survey banner present, go to the FAQ page;
3. Observe the survey banner at the top of the page;

#### Expected result:
- The banner should display the link for the survey;

#### Actual result:
- The banner and the link are displayed, but the link is written with white on white background and is therefore almost invisible;

#### Notes:
- The background color changes to white for premium users, but the color of the link remains white;
![image](https://user-images.githubusercontent.com/85748693/129565803-42973418-a6d1-49d1-b080-6bb1673561e6.png)
![image](https://user-images.githubusercontent.com/85748693/129565842-3ff09713-e8ef-43b8-ac60-d408a21070b5.png)

**Comment by Bianca-O** [comment]
This issue is verified as fixed on Stage under Windows 10 64-bit and Android 11. The link is visible. See new situation:

![new situation link](https://user-images.githubusercontent.com/79697848/133265112-78e5b26e-e52e-4a18-b92e-85e40760bf7e.gif)
