### ISSUE TITLE
Duplicate "Copy to Clipboard" Code

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/fx-private-relay#1033]
https://github.com/mozilla/fx-private-relay/blob/main/privaterelay/templates/profile.html#L144-L153
https://github.com/mozilla/fx-private-relay/blob/main/privaterelay/templates/profile.html#L116-L125

(Leave 144)

**Comment by Vinnl** [comment]
Absolutely correct @ggujjula, thanks for circling back on this! We now have [a single code path](https://github.com/mozilla/fx-private-relay/blob/473f1d19b072b79eaace5d16da0cdc24fc2f5463/frontend/src/components/dashboard/aliases/Alias.tsx#L62-L68) for "Copy to Clipboard".
