### ISSUE TITLE
More details arrow doesn't have a focus effect when using Tab key navigation

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1045]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14

**Browsers tested on:**
Firefox

**Preconditions:**
The user has a few aliases already added.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account. 
2. Focus the More details arrow using the Tab key.

**Actual result:**
There is no focus effect displayed when the More details arrow is selected using the Tab key.

**Expected result:**
More details arrow successfully displays a focus effect.

**Additional notes:**
Firefox Relay title and logo and Account menu icon don't have a focus effect either since the header background was changed to white when signed in.

![no focus - Tab navigation ](https://user-images.githubusercontent.com/79697848/131325617-692d4aa4-42b7-4ed1-8101-fc485e5fdf16.gif)

**Comment by Vinnl** [comment]
Fixed by #1518.
