### ISSUE TITLE
Aliases number and "x" button remain displayed when text in Search bar is deleted

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1046]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14

**Browsers tested on:**
Firefox

**Preconditions:**
The user has a few aliases already added.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account. 
2. Enter a text in the Search aliases bar and then delete it.
3. Click outside the Search aliases bar.

**Actual result:**
Aliases number and the "x" button are still displayed.

**Expected result:**
Aliases number and the "x" button are not displayed anymore.

**Additional notes:**
For comparison: When you just click in the Search bar and then outside of it, the Aliases number and the "x" button disappear.
 
![number   x button remain displayed](https://user-images.githubusercontent.com/79697848/131330408-65a40ebe-bb7e-4d8f-98cd-33cc94dfb202.gif)

**Comment by Vinnl** [comment]
Fixed in #1082.

**Comment by AOiegas** [comment]
Verified this issue as fixed on stage, Windows 10 and Android 9. The alias number and "x" button do not remain displayed when the text from the Search bar is deleted. Now they disappear when the alias search bar is not activated.
![nrandx](https://user-images.githubusercontent.com/85748693/133282978-cb7de698-7e95-425f-bd53-9815905f30a2.gif)
