### ISSUE TITLE
German localization of the site has the “Click to copy” and “Disable/Enable email forwarding for this alias” tooltips not translated

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1047]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;
- Have a few aliases created;
- Have the browser language set to German;

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. Scroll down to the alias list;
3. Hover mouse over the “Disable/Enable forwarding for this alias” button;
4. Hover mouse over the alias;
5. Observe both tooltips;

#### Expected result:
- The tooltips should be translated to german;

#### Actual result:
- The tooltips are in english;

#### Notes:
- N/A;
![localization 1 1](https://user-images.githubusercontent.com/85748693/131349374-19bd58b7-d39f-4631-8f75-af54cc2ab47c.png)
![localization 1 2](https://user-images.githubusercontent.com/85748693/131349378-b18bebc3-02e8-4ae6-9307-56c7d93b5b34.png)

**Comment by Bianca-O** [comment]
This issue is verified as fixed on Stage under Windows 10 64 bit. The tooltips are translated to German. See new situation:

![tooltip translated ](https://user-images.githubusercontent.com/79697848/133269068-5aba1bd6-b4c1-4378-b311-41c3946314e7.gif)
