### ISSUE TITLE
Filter issue when using the "x" button in the Search aliases bar

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1056]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Preconditions:**
The user has an active subscription.
The user has a few aliases added, some have forwarding enabled and some disabled.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account. 
2. Click on the filter button and check Active aliases option.
3. Click Apply and observe the displayed results.
4. Click in the Search aliases bar and then click the "x" button.
5. Observe the displayed results.

**Actual result:**
Both enabled and disabled aliases are displayed although the Active aliases filter is ON.

**Expected result:**
Only the Active aliases are displayed.

![filter issue](https://user-images.githubusercontent.com/79697848/131479185-ca406ed3-e079-42fa-8448-9022482849bd.gif)

**Comment by AOiegas** [comment]
Verified this issue on stage, Windows 10 and Android 9. The issue does not reproduce anymore as clicking on the "x" button of an empty alias search bar does not change/break the filters.
