### ISSUE TITLE
Apply button gets outside of filter dropdown when page is in Deutsch

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1059]
**Build:**
Stage

**Affected platforms:**
Windows 10 64 bit
macOS 10.14

**Browsers tested on:**
Firefox

**Preconditions:**
The user has an active subscription.
The browser's language is set to Deutsch.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account. 
2. Click the filter button and observe the drop-down elements.

**Actual result:**
The "Apply (Anwenden)" button gets outside of filter dropdown.

**Expected result:**
The "Apply (Anwenden)" button fits in the filter dropdown.

![button displayed outside of dropdown](https://user-images.githubusercontent.com/79697848/131481664-6f43cf3e-c383-402d-8f7a-0fa2d2fff076.PNG)

**Comment by AOiegas** [comment]
Verified this issue as fixed on stage, Windows 10. The apply and reset buttons arrange themselves on two rows when the translated words end up being too big for the initial layout. The languages that don't cause this layout issue keep the buttons on the same row.
This fix also fixes issue #1076 
![filtermenufix1](https://user-images.githubusercontent.com/85748693/133580222-c3d82cb7-381b-4445-9189-a3132101b376.png)
![filtermenufix2](https://user-images.githubusercontent.com/85748693/133580236-5e75dee4-05d8-4521-83d2-c078e54524da.png)
![filtermenufix3](https://user-images.githubusercontent.com/85748693/133580254-1f9c56a5-729e-4014-9383-d5f985636a31.png)
