### ISSUE TITLE
Alias domain not fully visible in the confirmation dialog

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1091]
**Build:**
Stage

**Affected platforms:**
Windows 10 64 bit
macOS 10.14
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Preconditions:**
The user has an active subscription but no email domain added.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in with an existing account.
2. Fill in the Search domain field and click the "Get Domain" button.
3. Observe the confirmation dialog.

**Actual result:**
The alias domain is not fully visible in the dialog.

**Expected result:**
The alias domain is fully visible in the dialog.

![domain not fully visible in confirmationdialog](https://user-images.githubusercontent.com/79697848/132855860-1b934957-9e40-4869-8c6c-d4876542d2fa.png)

**Comment by Vinnl** [comment]
The overflow in the screenshot mainly appears to be the result of `.mozmail.fxprivaterelay.nonprod.cloudops.mozgcp.net` being a very long word, but shouldn't happen in production when the URL is more concise.

That said, a very long custom domain name on a small screen _can_ overflow the modal. I'll ask UX how to deal with this.

![image](https://user-images.githubusercontent.com/4251/133414341-02651de6-1406-47ab-ad5b-2c0f809533de.png)
