### ISSUE TITLE
The user can register a subdomain containing special characters

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1095]
#### Build:
- Stage;

#### Affected Platforms:
- Across platforms;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Don’t have a subdomain set; 

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. In the subdomain registration field write something that contains at least one special character;
3. Click on the “Get domain” button;
4. Observe the results;

#### Expected result:
- The user gets and error message informing him that it is not a valid subdomain name;

#### Actual result:
- The user can continue registering the invalid subdomain;

#### Notes:
- N/A;
![image](https://user-images.githubusercontent.com/85748693/132864060-948c3cc9-a846-40d9-a3dc-40d72f9b83b5.png)

**Comment by Bianca-O** [comment]
This issue is verified as fixed on Stage under Windows 10 64 bit and Android 11. A warning message is displayed. See new situation:
![new situation](https://user-images.githubusercontent.com/79697848/134006037-c953117f-06b6-415e-aa2a-8121c23645e2.PNG)
:
