### ISSUE TITLE
"Copied" tooltip for an alias is displayed again when closing/deleting the search filter

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1099]
**Build:**
Stage

**Affected platforms:**
Windows 10 64 bit
macOS 10.14

**Browsers tested on:**
Firefox

**Preconditions:**
The user has a few aliases already created.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in with an existing account.
2. Select an alias and click the "Copy" button.
3. Search for an alias by entering a text in the Search aliases bar.
4. Delete the text in the Search bar or close the search filter.

**Actual result:**
"Copied" tooltip is displayed again for the previously selected alias.

**Expected result:**
"Copied" tooltip is not displayed anymore for the previously selected alias.

![copied tooltip appears again](https://user-images.githubusercontent.com/79697848/133074846-a83f58e5-d2f4-4135-8ae0-0660ed7a5923.gif)

**Comment by AOiegas** [comment]
Verified this issue as fixed on stage, Windows 10 and Android 9. The "Copied" tooltip doesn't reappear when closing/deleting the search filter anymore.
