### ISSUE TITLE
<em>⁨soft⁩</em> “bounce”

### ISSUE THREAD

**Issue by fffillyy** [mozilla/fx-private-relay#1116]
Relay⁩ couldn’t deliver your email.

We are currently unable to send email to ⁨myusername@hotmail.com⁩. We received a <em>⁨soft⁩</em> “bounce” from your email provider when trying to forward emails to you. This can happen if ⁨Relay⁩ couldn’t connect to your email provider, or if your mailbox was full. We will try again on ⁨20/09/2021 2:23 a.m.⁩.

My mailbox is not full.

**Comment by EL670** [comment]
Gosh, I had the same message just now.  What was the solution?
