### ISSUE TITLE
Question: How to run the docker image locally?

### ISSUE THREAD

**Issue by raed667** [mozilla/fx-private-relay#1131]
I have tried cloning the project: 

```
git clone --recurse-submodules https://github.com/mozilla/fx-private-relay.git
```

Then ran to build the image: 

```
docker build -t fx-private-relay .
```

Then ran:
```
docker run -d -p 8000:8000 --name relay fx-private-relay
```

When I got to `http://127.0.0.1:8000/` on the host machine the request doesn't go through. But when I `docker exec` into the container and run `curl 127.0.0.1:8000` I see the HTML response. 

What am I missing here? Could you please add a beginner guide on how to run it dockerized?

**Comment by hydrargyrum** [comment]
Is this the official image? https://hub.docker.com/r/mozilla/fxa-profile-server
There's no readme attached

**Comment by hydrargyrum** [comment]
@raed667 what have you found?

**Comment by raed667** [comment]
@hydrargyrum I moved on to another project since the team doesn't seem to be interested in the question.

If you wish you can open another issue.
