### ISSUE TITLE
Alignment issue and different font size for Profile menu options

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1190]
**Build:**
Stage

**Affected platforms:**
Windows 10 64 bit
macOS 10.14

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/ and log in with an existing account.
2. Click the "Profile" icon. 
3. Observe the alignment of "Settings" and "Sign Out of Relay" texts.
4. Observe the texts font size.

**Actual result:**
The two texts are not aligned. They also have a different font size.

**Expected result:**
The two texts are aligned. They have the same font size.

![no alignment](https://user-images.githubusercontent.com/79697848/136961889-a2b8826d-4db2-4101-b076-b3eb8f9489ba.PNG)

![diff font size and alignment issue](https://user-images.githubusercontent.com/79697848/136963425-edfb68ab-47ab-4051-a85c-c27d1f0d2b09.PNG)

**Comment by Vinnl** [comment]
Fixed by https://github.com/mozilla/fx-private-relay/pull/1518.
