### ISSUE TITLE
The numbers for Blocked/ Forwarded on alias cards are not always aligned when Welsh language is selected

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1192]
**Build:**
Stage

**Affected platforms:**
Windows 10 64 bit
macOS 10.14

**Browsers tested on:**
Firefox

**Preconditions:**
The browser's language is set to Welsh.
The user has a few aliases already created.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/ and log in with an existing account.
2. Observe the counter on the aliases cards. 

**Actual result:**
The text wraps on two lines and the numbers for Blocked/Forwarded are not aligned when alias name is longer.

**Expected result:**
The numbers for Blocked/Forwarded are aligned even when alias name is longer.

![Welsh - alignment issue on card](https://user-images.githubusercontent.com/79697848/136968290-0153d1cf-e73e-4f77-855c-d4ce1d51b326.PNG)

**Comment by Vinnl** [comment]
Fixed by https://github.com/mozilla/fx-private-relay/pull/1518.
