### ISSUE TITLE
django.urls.path warning when calling runserver function

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/fx-private-relay#1201]
Whenever I run the app locally, I get the following warning: 

>WARNINGS:
> ?: (2_0.W001) Your URL pattern 'v1/swagger(?P<format>\.json|\.yaml)' [name='schema-json'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().

Stackoverflow Search Results:
https://stackoverflow.com/questions/47661536/django-2-0-path-error-2-0-w001-has-a-route-that-contains-p-begins-wit

**Comment by jwhitlock** [comment]
Can you re-open this? I believe it is a real issue:

```
curl -I http://localhost:8000/api/v1/swagger.json
curl -I https://relay.firefox.com/api/v1/swagger.json
```

I have a fix as well.
