### ISSUE TITLE
Double email addresses at 551px wide

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fx-private-relay#1216]
Casually noticed while resizing ye olde browser window. Double email addressed displayed at 551px wide, and fixes itself at 768px wide (so 551-767px page widths are suspect).

![Firefox_Relay](https://user-images.githubusercontent.com/557895/137428855-3bf0a1ec-08ba-44e2-b54f-13b0e23987e6.png)

![Firefox_Relay](https://user-images.githubusercontent.com/557895/137428907-ada11fe2-36b5-4504-96d7-0df4d9b529e0.png)

---

macOS 11.6 (Big Sur) on rMBP and latest Nightly.

**Comment by Vinnl** [comment]
Fixed by https://github.com/mozilla/fx-private-relay/pull/1518.
