### ISSUE TITLE
Inconsistent favicon vs logo

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fx-private-relay#1219]
Randomly spotted while admiring one of my screenshots in a previous issue:

![Firefox_Relay](https://user-images.githubusercontent.com/557895/137443202-e4ee3687-5266-4857-a1f9-8ff14a0c3e88.png)

Not sure if your Relay logo changed recently, but the main logo in the header is a different shade of purple than the current favicon.

🤷

**Comment by Vinnl** [comment]
Fixed in https://github.com/mozilla/fx-private-relay/pull/1518.
