### ISSUE TITLE
Unify Banner Cookie Logic 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/fx-private-relay#1238]
The following functions are all clones of each other. We should migrate this to a single function with some parameters.

Params: 
- Cookie ID Name
- Banner Target ID/Class
- Dismiss Target Class 

https://github.com/mozilla/fx-private-relay/blob/b443409dcd9b3423643ee507c2d8d40d01dcfc59/static/js/app.js#L480
https://github.com/mozilla/fx-private-relay/blob/b443409dcd9b3423643ee507c2d8d40d01dcfc59/static/js/app.js#L431
https://github.com/mozilla/fx-private-relay/blob/b1e954a9d0d9a8afded6d64d428047c2c5d27a66/static/js/app.js#L529

**Comment by Vinnl** [comment]
We have roughly this now with https://github.com/mozilla/fx-private-relay/pull/1518.
