### ISSUE TITLE
Add PR Checklist Templates

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/fx-private-relay#1258]
Starting a draft here: https://docs.google.com/document/d/1tv4TCbsmG4t2J056sCKCdBErUxc21LMgVKaJ-7xIYVE/edit?usp=sharing

It should have a few "sections" to it: 
- Global (applies to all PRs) 
- New feature
- Bug fix

**Comment by Vinnl** [comment]
Fixed by #1349 - updates are still possible of course :)
