### ISSUE TITLE
Subdomain Registration Box is hidden by default, making scroll-to anchor links difficult

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/fx-private-relay#1285]
This definitely is the right code, but when I tried to spot-check my local by going to http://127.0.0.1:8000/accounts/profile/?utm_source=fx-relay-addon&utm_medium=popup&utm_content=register-email-domain#mpp-choose-subdomain , the subdomain modal is properly highlighted, but the browser window doesn't seem to scroll down to it. 😢

_Originally posted by @groovecoder in https://github.com/mozilla/fx-private-relay-add-on/pull/185#pullrequestreview-787601158_

**Comment by Vinnl** [comment]
Fixed by #1315.

**Comment by Vinnl** [comment]
To test this, see the steps at https://github.com/mozilla/fx-private-relay-add-on/pull/185 and verify that the domain registration form is actually scrolled into view.
