### ISSUE TITLE
"Contact us" link is not available in the Profile menu when user is on the FAQ page 

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1286]
**Build:**
Stage

**Affected platforms:**
Windows 10 64 bit
macOS 10.14

**Browsers tested on:**
Firefox

**Preconditions:**
The user has an active subscription.

**Steps to reproduce:**

1. Navigate to Stage server and log in with an existing account.
2. Click on the Profile icon and observe the Contact us link.
3. Go to FAQ page.
4. Click again the Profile icon and look for Contact us link.

**Actual result:**
The Contact us link is not available in the Profile menu when user is on the FAQ page.

**Expected result:**
The Contact us link is available in the Profile menu when user is on the FAQ page.

![contact us link](https://user-images.githubusercontent.com/79697848/138705542-86990ec4-a0bd-494f-a7fa-b6ff7ec31a61.gif)

**Comment by AOiegas** [comment]
Verified this as fixed on Stage, Windows 10. The "Contact Us" link is available while on the FAQs page, only for Premium users as intended.
![image](https://user-images.githubusercontent.com/85748693/146018848-973dac52-601b-47b8-96ed-7c8ae07a82f3.png)
