### ISSUE TITLE
DRY: Profile "Alias" Markup duplicates code 

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/fx-private-relay#1301]
The profile has duplicated markup to generated each type of alias: 

- Generated aliases: [/templates/profile.html#L101-L226](https://github.com/mozilla/fx-private-relay/blob/main/privaterelay/templates/profile.html#L101-L226)
- Custom aliases [/templates/profile.html#L228-L356](https://github.com/mozilla/fx-private-relay/blob/main/privaterelay/templates/profile.html#L228-L356)

Noted from this comment: https://github.com/mozilla/fx-private-relay/pull/1298#issue-766499302

**Comment by Vinnl** [comment]
Fixed by #1316.
