### ISSUE TITLE
[Feature Request] Allow secondary email address for sign up

### ISSUE THREAD

**Issue by teonbrooks** [mozilla/fx-private-relay#133]
Following up on the demo from product club, after trying out the login flow for the Private Relay, it requested that I must use my primary email address to sign up for the feature. Currently sign up is restricted to mozilla-domain email addresses. My primary account is a `gmail.com` and my secondary is a `mozilla.com`. Would there be a way to have the login flow use secondary emails for authentication?

**Comment by groovecoder** [comment]
Thanks for the early feedback. But I think we'll close this. By the time we could try to build this, we will probably already be in open beta where we'll accept sign-ups on any FXA no matter the email address domain.
