### ISSUE TITLE
Wrong message displayed when adding a domain that is not allowed

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1332]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14

**Browsers tested on:**
Firefox

**Preconditions:**
The user has an active subscription but no email domain added.

**Steps to reproduce:**

1. Navigate to Stage server and log in with an existing account.
2. Click the "Get Started" button on the new onboarding.
3. At step 2 add white space as a domain or a word that is on the badwords list.
4. Observe the warning message displayed.

**Actual result:**
The last message displayed shows up as a warning message. (If "...successfully signed in" message was last displayed then this is displayed as the warning message too)

**Expected result:**
The correct warning message is displayed.

![wrong message displayed1](https://user-images.githubusercontent.com/79697848/140710003-34d3e85f-fa9f-4fd6-a3af-f4d6a7fcdc5a.gif)

**Comment by AOiegas** [comment]
This also happens when trying to use not allowed characters, like most special characters.

**Comment by codemist** [comment]
@Bianca-O I can't seem to reproduce this error: 
<img width="1617" alt="image" src="https://user-images.githubusercontent.com/13066134/140816978-1445ee39-313c-4b4d-95be-4eef76022f0f.png">

**Comment by maxxcrawford** [comment]
@codemist It only occurs when you login and have a green "logged in" success message visible. 

I have a fix for this!
