### ISSUE TITLE
Endless spinning page when hitting Add to Firefox button 

### ISSUE THREAD

**Issue by digitarald** [mozilla/fx-private-relay#134]
STR: Hit `Add to Firefox`
AR: Endless spinning accounts page, no related console logs

![image](https://user-images.githubusercontent.com/8599/78919557-ee262c80-7a46-11ea-945a-9ed49456ab9d.png)

Maybe because my Firefox email isn't `@mozilla.com`? I have a HAR file which I shared in private channels, as it might contain PII tokens.

**Comment by digitarald** [comment]
Using `Sign In` has the same issue, but `Refresh` fixes it.

**Comment by digitarald** [comment]
After `Sign In` works I get
<img width="999" alt="image" src="https://user-images.githubusercontent.com/8599/78924222-4280da80-7a4e-11ea-94eb-47ac0fcf6ede.png">

**Comment by groovecoder** [comment]
That's the error you should get when your FXA email isn't `@mozilla.com`, but I'm not sure why it looks all janky. 😢 Can you try again to see if you get a nicer error page? Maybe some browser CSS cache, or we were deploying when you did it last time?

**Comment by digitarald** [comment]
Still fails, also with Network panel open and Cache disabled.

**Comment by groovecoder** [comment]
Hmm ... this is what I see ...

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/71928/79170451-071b3e80-7db5-11ea-87aa-4705289a9313.png">


Browser & version? Add-ons?

**Comment by lesleyjanenorton** [comment]
Fixed as of #159 and #132
