### ISSUE TITLE
"Manage All Aliases" link in the add-on menu is not fully visible when browser's language is not English

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1363]
**Build:**
Production

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox

**Preconditions:**
The Relay add-on is installed.
1)
The user doesn't have a subscription.
The browser's language is set to German/ Portuguese (Brasil).
2)
The user has an active subscription but no email domain added.
The browser's language is set to Welsh/ Swedish/ Ukrainian, etc.

**Steps to reproduce:**

1. Navigate to Stage server and log in with an existing account.
2. Click the Relay add-on button in the toolbar.
3. Observe the first/ second page in the add-on menu.
4. Observe the Manage All Aliases link.

**Actual result:**
The Manage All Aliases link is not fully visible in the menu.

**Expected result:**
The Manage All Aliases link is fully visible in the menu.

![German addon issue](https://user-images.githubusercontent.com/79697848/142021899-54076835-b6b7-4b93-83f9-4b6383894969.PNG)

![portughese add-on menu](https://user-images.githubusercontent.com/79697848/142023654-fcc53027-c2a6-4bce-bf4a-4828405afcbb.PNG)

![Ukrainian - link not visible](https://user-images.githubusercontent.com/79697848/142177315-8f6777f4-f47a-4ffd-a2c4-0592b0a7f6be.PNG)

**Comment by codemist** [comment]
PR for this issue is here: https://github.com/mozilla/fx-private-relay-add-on/pull/212
