### ISSUE TITLE
Investigate: Sync possibilities with about:logins

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/fx-private-relay#138]
If a user has saved logins using Relay aliases, is signed in and using sync, could we add login domain info to the alias cards?

**Comment by groovecoder** [comment]
Maybe. But we're currently planning to store the login domain client-side in `browser.storage.local` - not on the server. So, we'll have to figure out if/how to access that add-on storage from `about:logins`, or else this will have to wait if/until we merge this code into central.

**Comment by tcinotto** [comment]
Overcome by events. A user can now use label syncing.
