### ISSUE TITLE
Cannot add label to alias

### ISSUE THREAD

**Issue by lucy2812** [mozilla/fx-private-relay#1380]
I do not have an option to add a name or label to an email alias:
https://support.mozilla.org/en-US/kb/use-labels-keep-your-aliases-organized-firefox-rel

![image](https://user-images.githubusercontent.com/85310065/142747506-f34fbe04-d97d-46e8-9ccd-e93a93855ead.png)

**Comment by Vinnl** [comment]
Hi @lucy2812, did you [enable data collection](https://support.mozilla.org/en-US/kb/firefox-relay-get-your-labels-all-your-devices)? You can only add labels if you gave us permission to store them.

**Comment by Vinnl** [comment]
I'm assuming that the above was the issue; if not, feel free to re-open!
