### ISSUE TITLE
"is available" text is not correctly displayed in the subdomain confirmation dialog

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1381]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox

**Preconditions:**
The user has an active subscription but no email domain added.

**Steps to reproduce:**

1. Navigate to Stage server and log in with an existing account.
2. Fill in a valid subdomain in the "Search domain" field and click "Search".
3. Observe the subdomain confirmation dialog.

**Actual result:**
"is available" text is not correctly displayed in the dialog.

**Expected result:**
"is available" text is correctly displayed in the dialog under the domain address.

![confirmation dialog text issue](https://user-images.githubusercontent.com/79697848/142871590-648667e8-f461-42d0-a82a-d719692a925c.gif)

**Comment by Vinnl** [comment]
We now just show `.mozmail.com` even on stage, so this should no longer occur.
