### ISSUE TITLE
Relay intercepts "tab" key and breaks auto-type in keepass

### ISSUE THREAD

**Issue by dzikimarian** [mozilla/fx-private-relay#1388]
**Version info**
Windows 10
FF 94.0.2
Relay 2.0.0

**Steps to reproduce**
1. Go to any supported login form
2. Enter username
3. Press tab
4. Relay icon will gain focus. Next key-press will open pop-up to pick/generate alias

**Expected behavior**
Relay icon, should not take focus on "tab" press, since it breaks auto-type sequence on password managers (in my case keepass). Since I don't know which forms will be supported by relay, and which won't be (or even if it will be always consistent for the same website) it's hard to adjust autotype sequence.

**Comment by Vinnl** [comment]
Hi @dzikimarian, the icon is added by the add-on. Since this same issue was already redirected in the add-on repository, I'd like to ask you to follow that issue, and I'll close this one. The other issue can be found here: https://github.com/mozilla/fx-private-relay-add-on/issues/243

Cheers!
