### ISSUE TITLE
Customer unable to reply to emails forwaded by Relay

### ISSUE THREAD

**Issue by JC-Support** [mozilla/fx-private-relay#1401]
Customer is unable to respond to any emails forwarded by Relay. Customer has attempted on both web mail and email clients. The user provided the following 

———test-mail———
test.account@mail.com —> alias@mozmail.com
On Relay-Dashboard Redirected-Counter increases✅
test-mail is in “firefox.account@mail.com” Inbox✅

———test-reply———
firefox.account@mail.com —> replies@relay.firefox.com
On Relay-Dashboard Redirected-Counter increases✅
test-reply is neither in “test.account@mail.com” Inbox nor in Spam❌

Tested on linux, macOS, iOS
web browser (Firefox), desktop client (thunderbird)(on mac with apple mail too), app client (associate app)
changed my firefox primary account mail for testing different inboxes (Gmail, iCloud mail, Proton Mail)
with “alias@mozmail.com” and “alias@domain.mozmail.com”
with/without VPN (Mozilla VPN)
no monitoring

**Comment by say-yawn** [comment]
@JC-Support can you ask the user if:

- They get any email back about an error to send the email?
- Does the number forwarded increment? (this will change later so we are creating metrics for replies separate from forwarded emails)
- Is the email they are using to send reply the same as the email they are getting relayed to? (sometimes the user can use an alias on FxA so the email will get forwarded there but the response may be a different email address, see this [Gmail doc](https://support.google.com/mail/answer/22370?hl=en) on how to send response with another email address).

**Comment by JC-Support** [comment]
Hi @say-yawn The user responded with the below: 

    no error mail or error message at all

    counter matches exactly the number of received mails and replies

    no it’s not the same, but even i send a mail to myself, reply doesn’t work

**Comment by groovecoder** [comment]
@AOiegas - can you try to reproduce this and record the STR if you do?

**Comment by groovecoder** [comment]
We deployed a fix for this which looks in the `References` header for message IDs too.
