### ISSUE TITLE
Can't sign out or deactivate Firefox Relay

### ISSUE THREAD

**Issue by ruslanbay** [mozilla/fx-private-relay#1445]
As a Firefox account owner I want to deactivate or at least sign out from the Firefox Relay service if I don't use it anymore.

Steps:
1. Navigate to https://accounts.firefox.com
2. Login to your Firefox Account
3. Navigate to https://relay.firefox.com
4. Login
5. Navigate to https://accounts.firefox.com/settings#connected-services
**Result:** You will see "Firefox Private Relay" with a "Sign out" button in the list
![image](https://user-images.githubusercontent.com/67730802/148058112-d12986c7-9f1a-41dc-bc40-33911ed10658.png)

6. Click on the "Sign out" button from the step 5
7. Update the page
**Result:** "Firefox Private Relay" appears in the list again

8. Navigate to https://relay.firefox.com/accounts/profile/
9. Click on the "Sign Out from Relay" button
10. Navigate to https://accounts.firefox.com/settings#connected-services
**Result:** "Firefox Private Relay" still in the "Connected Services" list

**Comment by tcinotto** [comment]
Thank you for filing this! We'll take a look right now.

**Comment by ruslanbay** [comment]
Can't reproduce anymore. I'll close this issue.
