### ISSUE TITLE
Localise French and German promo images

### ISSUE THREAD

**Issue by Vinnl** [mozilla/fx-private-relay#1451]
Related to https://github.com/mozilla/fx-private-relay/pull/1450. The hero images are currently translated to French and German, but names are still US-style. The Figma files to update the text in can be found [here](https://www.figma.com/file/41y1kGrI2zKv4kvfdJdAWW?node-id=93:6239#137485201).

They could be further localised as follows:

## French

John Doe: Dominique Dupont
thebestonlinestore.com: ~~lemeilleursiteenligne.fr~~ lemeilleursiteenligne.com
foodie@smithfamily.com: gastronomie@familledurand.mozmail.com
social@smithfamily.mozmail.com: social@familledurand.mozmail.com
social networks: Réseaux sociaux

See also https://en.wikipedia.org/wiki/List_of_placeholder_names_by_language#Persons_5

Additionally, "Octobre" should be decapitalised, i.e. "octobre".

## German

John Doe: Erika Musterfrau
thebestonlinestore.com: derbesteonlineshop.com
foodie@smithfamily.mozmail.com: foodie@familiemueller.mozmail.com
social@smithfamily.mozmail.com: social@familiemueller.mozmail.com
social networks: Soziale Medien

See also https://en.wikipedia.org/wiki/List_of_placeholder_names_by_language#Persons_6

**Comment by Mozinet-fr** [comment]
If you want to be inclusive at the level of French-speaking countries, you can use the ".com" instead of the ".fr" restricted to France. The ".com" is very common in France for online stores.
thebestonlinestore.com: lemeilleursiteenligne.com
