### ISSUE TITLE
The “Generate New Alias” button doesn’t become grayed-out when reaching 5 aliases for a free user from a country where Premium is not available

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1499]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10, Android 11;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with NO active subscription;
- Have 4 aliases created;
- Have a VPN set to a country where Premium Relay is not available (e.g. Romania, Poland, Serbia);

#### Steps to reproduce:
1. Go to the Relay Dashboard;
2. Click on the “Generate New Alias” button;
3. Observe the same button;

#### Expected result:
- The button should become grayed-out and inactive;

#### Actual result:
- The button doesn’t become grayed-out;

#### Notes:
- Encountered with and without a VPN on, and on three other non-premium countries;
- For countries that have Premium available there doesn’t seem to be a similar problem;
- The button seems to be still click-able, but it doesn't do anything;
- See attached media:
![strg](https://user-images.githubusercontent.com/85748693/151370339-c332b666-c5f5-40b8-b0ac-cc9e1526955b.gif)

**Comment by Vinnl** [comment]
Should be fixed by https://github.com/mozilla/fx-private-relay/pull/1518.
