### ISSUE TITLE
Green successful message banners cannot be dismissed by clicking on the “X” button

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1500]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10, Android 11;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;

#### Steps to reproduce:
1. Go to the Relay Dashboard;
2. Sign out;
3. Click on the “X” button of the green message banner;

#### Expected result:
- The green successful message banner should be dismissed;

#### Actual result:
- Clicking on the “X” button does not dismiss the banner;

#### Notes:
- This seems to apply to the banner that appears when a user successfully signs in;
- The red banner displayed when a Premium user enters an unavailable custom domain name doesn’t seem to be affected;
- See attached media:
![nox](https://user-images.githubusercontent.com/85748693/151372860-aa809055-e88f-49f4-b70a-152074cb9c4d.gif)

**Comment by joaonunomota** [comment]
It is possible to close the signed in / out banners by clicking on the "X" button.

Example:

![example-toast](https://github.com/mozilla/fx-private-relay/assets/16689477/17f6daa0-ab0a-45e7-acc3-cc8f6086b6dd)

**Comment by jwhitlock** [comment]
Thanks @joaonunomota! This should have been closed with PR #1792.
