### ISSUE TITLE
The main text section of the “Create a new custom alias” modal presents layout issues

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1504]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Have a Subdomain (Custom Domain Name) set;

#### Steps to reproduce:
1. Go to the Relay Dashboard;
2. Click on the “Generate New Alias” button;
3. In the opened drop-down menu, click on the “@<subdomain> Alias” option;
4. Observe the text in the top half of the opened modal; 

#### Expected result:
- The text is displayed without any issues;

#### Actual result:
- The text presents layout issues, specifically affecting how the example email is warping the rest of the paragraph;

#### Notes:
- From what I see, the modal in the Figma reference and the one that is present on Stage seem to have different dimensions, though I might be wrong;
- See attached media:
Figma reference:
![image](https://user-images.githubusercontent.com/85748693/151519737-4f070bca-4e6e-437d-88c3-a3ccdb884449.png)
Stage:
![image](https://user-images.githubusercontent.com/85748693/151520017-71c64e70-d8b8-48fa-b115-cea0a819776b.png)

**Comment by Vinnl** [comment]
Generally we don't expect implementations to be pixel-perfect renditions of the design, as there's many factors (screen size, zoom factor, font size, language, etc.) that influence what things will look like in practice. The main reason it looks somewhat weird here is that `"shop@customdomain.mozmail.com"` is considered a single word and thus gets pushed onto the next line in its entirety. I think that's expected behaviour though, and in different configurations it might just fit on the previous line.

**Comment by AOiegas** [comment]
Yes, I figured out that it being considered a single word might be the main reason, but it still looks off because of it. I was thinking if putting the whole sentence on a different line would help, but it will probably move the last word, "example", to another line as well, so I don't know if that would be considered an improvement.

**Comment by Vinnl** [comment]
Yeah and again, that can't be done predictably: if I insert a line break before "Try", on smaller screens you might have a line with just "Try" on there, for example. And in different languages the email address might be in the middle of the sentence, moving it back onto a separate line again.
