### ISSUE TITLE
Count the number of replies sent to relayed emails

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#151]
To understand if and how to fix #99, we should count the number of emails sent to `noreply@relay.firefox.com`, so we know how many people are trying to reply to relayed emails.

**Comment by groovecoder** [comment]
I'm going to start by recording how often this happens. If/when we start to see this happen a lot more, we can consider adding code for it.

**Comment by Lanchon** [comment]
this is not indicative. most people using the service are saavy and would note the noreply@ address and skip writing and sending an email.

**Comment by groovecoder** [comment]
We have a count of these now at https://earthangel-b40313e5.influxcloud.net/d/qiwPC76Zk/fx-private-relay?orgId=1. Still not capturing all the intention to use replies, as @Lanchon pointed out.
