### ISSUE TITLE
The Relay Upsell Banners appear for Free Users as well

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1510]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Have a VPN set to a country where Premium Relay is not available;

#### Steps to reproduce:
1. Create a new Browser profile;
2. Go to the Relay homepage;
3. Create a new Free Relay account (non-mozilla) and proceed to the Relay Dashboard;
4. Generate a new alias;
5. Send an email to the generated alias;
6. Observe the received email;

#### Expected result:
- The relayed email should not contain the Relay Upsell Banners;

#### Actual result:
- The relayed emails contains the Relay Upsell Banners;

#### Notes:
- Up until now, creating a new Browser profile and creating a new free account was enough to stop the Upsell Banners to show up;
- This was also encountered by a tester colleague that had not interacted with the Relay since before the Upsell Banners were implemented;
- See attached media:

![image](https://user-images.githubusercontent.com/85748693/151776416-6cbe8753-04a2-4a88-adfa-b8839f2f071e.png)

**Comment by Vinnl** [comment]
Hi @AOiegas, do you know what language the browser was configured to use when creating the Firefox account? I believe the country associated with that language is what is used in determining whether Premium is available, because we don't have other location data available from Firefox accounts.

**Comment by AOiegas** [comment]
@Vinnl It was English. So then it's probably because of that. I missed the fact that it's dependent on the language. Let me check again with other languages.

**Comment by AOiegas** [comment]
@Vinnl Indeed, it is dependent on the language of the browser. They do not show up with a language from a country that doesn't have Premium available. Closing this then.
