### ISSUE TITLE
Scaling changed on some websites when addon is enabled

### ISSUE THREAD

**Issue by LukePeltier** [mozilla/fx-private-relay#1515]
reddit.com, twitch.com, sites appear "zoomed" when this extension is enabled. Disabling the extension removes the issue

**Comment by LukePeltier** [comment]
![image](https://user-images.githubusercontent.com/18688112/152015787-73dbe94d-8fd9-449c-b329-6e44d2702af1.png)


extension disabled:
![image](https://user-images.githubusercontent.com/18688112/152015869-13cfcb40-658b-4f0c-9ce8-90f29f45663c.png)

**Comment by occlu** [comment]
I confirm the issue for twitch. As said, enabling/disabling the extension will zoom/dezoom the pages in real time.

**Comment by kwenzig** [comment]
I confirm the issue for tagesschau.de and deutschlandfunk.de

**Comment by humpfhumpf** [comment]
In relay.css,  ":root" rule sets the default size of font:
```
:root, body {
  font-size: 16px;
}
```

**Comment by maxxcrawford** [comment]
Hey everyone! This has been fixed and we've published a new version. Please make sure you're [updated to the latest version](https://support.mozilla.org/en-US/kb/how-update-add-ons) of the add-on (`2.2.2`).
