### ISSUE TITLE
relay.css significantly increases font sizes

### ISSUE THREAD

**Issue by kenlyon** [mozilla/fx-private-relay#1516]
This might have been introduced by today's update. I certainly didn't notice it before.

Today I noticed font sizes appearing too large in certain websites. One example is https://mint.intuit.com/. After initial page load, certain elements grow a bit and don't quite fit with the rest of the page.

At first I thought it was my page zoom or scaling in Windows Display Settings, but after inspecting the page I found it was rules being applied from relay.css. Disabling the extension resulted in the page displaying as intended.

I think you might need to use more targetted selectors to style only the parts that you are adding to pages.

**Comment by Vinnl** [comment]
Thanks for reporting @kenlyon, could you try [updating](https://support.mozilla.org/en-US/kb/how-update-add-ons) to the latest version 2.2.2? This should be fixed there.

See also:

- https://github.com/mozilla/fx-private-relay/issues/1515
- https://github.com/mozilla/fx-private-relay-add-on/issues/272
- https://github.com/mozilla/fx-private-relay-add-on/issues/275

**Comment by kenlyon** [comment]
Thanks. It looks good now!
