### ISSUE TITLE
Mobile: For a user with a long Custom Domain Name set, it is displayed on the dashboard’s header in a faulty way

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1527]
#### Build:
- Stage;

#### Affected Platforms:
- Android 11;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Have a least one alias created;
- Have a Custom Domain Name set;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Observe the dashboard header;

#### Expected result:
- The Custom Domain Name is displayed without issue;

#### Actual result:
- The Custom Domain Name is displayed in a faulty way, clipping out of the phone screen instead of warping;

#### Notes:
- See attached media:
![image](https://user-images.githubusercontent.com/85748693/153424052-c78e83df-3a32-4e57-9c42-4b2a397e0124.png)

**Comment by Vinnl** [comment]
With #1789 I think we're always showing `.mozmail.com`, even on stage, so there are no long names anymore.
