### ISSUE TITLE
The CSAT banner is not translated into German (de) and French (fr)

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1534]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with NO active subscription;
- Have the browser’s language set to German (de) or French (fr);
- Have a VPN set to a country other than the US;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Right click on the page and choose the “Inspect” option;
3. Navigate to the “Storage” tab and select “Cookies”;
4. For the Firefox Relay cookies, click on the “first_visit” value field;
5. Change it to a date that’s more than 7 days ago (e.g. "2022-01-11 07:05:10.243043+00:00");
6. Refresh the Relay dashboard page;
7. Observe the CSAT banner at the top of the page;

#### Expected result:
- The CSAT banner is displayed in the language of the browser;

#### Actual result:
- The CSAT banner is displayed in in English;

#### Notes:
- The content of the survey is translated in both German and French;
- It might be too early to have the translation of the banner as it’s a new feature, but I’d rather have this issue reported;
- See attached media:
German:
![germanCSAT](https://user-images.githubusercontent.com/85748693/153605794-7a31f47f-36ef-4b2f-9b11-31a29535bf71.png)
French:
![frenchCSAT](https://user-images.githubusercontent.com/85748693/153605804-b5901ecb-d5a9-4021-ab7c-0e85462c2dfe.png)

**Comment by Vinnl** [comment]
I believe these are fully translated now.
