### ISSUE TITLE
Enforce DMARC policies of sending domains

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#1549]
To prevent someone using Relay to bypass DMARC enforcement, we should enforce DMARC policies when we relay email.

See https://docs.aws.amazon.com/ses/latest/dg/receiving-email-notifications-contents.html#receiving-email-notifications-contents-dmarcverdict-object.

**Comment by groovecoder** [comment]
Test comment.

**Comment by groovecoder** [comment]
2nd test comment - should NOT forward to @vr4tr3q23

**Comment by AOiegas** [comment]
Test comment - forward.

**Comment by AOiegas** [comment]
Test comment - promotionals.

**Comment by Bianca-O** [comment]
test comment - forward

**Comment by Bianca-O** [comment]
test comment - promotionals

**Comment by birelay** [comment]
another test

**Comment by biaO10** [comment]
test - forward

**Comment by biaO10** [comment]
test - no forwarding

**Comment by biaO10** [comment]
another test - forward

**Comment by AOiegas** [comment]
test - fwd

**Comment by AOiegas** [comment]
test - promo

**Comment by AOiegas** [comment]
test - promo x2

**Comment by AOiegas** [comment]
test - promo x3

**Comment by AOiegas** [comment]
test - fwd x2

**Comment by AOiegas** [comment]
test - block x1

**Comment by AOiegas** [comment]
test - promo x5

**Comment by AOiegas** [comment]
test - fwd x3

**Comment by biaO10** [comment]
test - block promo

**Comment by biaO10** [comment]
test- no blocking

**Comment by birelay** [comment]
test - no blocking

**Comment by birelay** [comment]
test - block

**Comment by biaO10** [comment]
test - block 2

**Comment by biaO10** [comment]
test - no block 2

**Comment by AOiegas** [comment]
Test - forwarding

**Comment by AOiegas** [comment]
Test - promo

**Comment by AOiegas** [comment]
Test - block

**Comment by AOiegas** [comment]
Test - back to forwarding
