### ISSUE TITLE
Investigate errors coming from django.security.DisallowedHosts

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#1557]
# About this Issue
Investigate and resolve the following errors being logged in django.security.DisallowedHosts logger:
- [Invalid HTTP_HOST header: 'localhost'. You may need to ...](https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/8667885/?query=logger%3Adjango.security.DisallowedHost)
- [Invalid HTTP_HOST header: '130.211.19.131'. You may need](https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/8120631/?query=logger%3Adjango.security.DisallowedHost)
- [Invalid HTTP_HOST header: 'prod.fxprivaterelay.prod](https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/9310523/?query=logger%3Adjango.security.DisallowedHost)
#
One way to handle this is set Sentry config to no longer send DisallowedHosts error.

**Comment by jwhitlock** [comment]
I was concerned that these were generated by a Mozilla process that we should fix. I took a look at the Load Balancer entries (thanks @moz-astults for a guide to Log Explorer):

* [localhost log entries](https://cloudlogging.app.goo.gl/SEGE6arEcpyiKgXX9)
* [IP address log entries](https://cloudlogging.app.goo.gl/y9cmPrbWmrtjjF1DA)
* [prod.fxprivaterelay.prod...](https://cloudlogging.app.goo.gl/R2xfyNUCPxBYrDHY6)

They look like security scans to me, and from an assortment of IP addresses outside of AWS. I think we're doing the right thing (block with 400), and we can proceed with issue #1556 and avoid sending them to Sentry.

**Comment by moz-astults** [comment]
I also have a task to allow the specific hostnames we expect so this can be `404`'d at the load balancer, but it is a low-priority task for me and I don't have a firm time it will be done.

**Comment by jwhitlock** [comment]
I think we can call the investigation done - these are external security scans, not a bad configuration, and are available in the logs. 404s are a nice-to-have, but not a high-priority. The work to omit them from Sentry is in issue #1556.
