### ISSUE TITLE
Add "invitations" list

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#156]
To invite users on the wait-list, and enable a rolling invitation flow, we need to:

1. Add an `invitations` table:
   * `id`, `email`, `date_added`, `active`, `date_sent`, `date_redeemed`
2. Copy the email addresses from Monitor subscribers' ["waitlists joined"](https://github.com/mozilla/blurts-server/blob/master/db/DB.js#L338-L346) field
   * Set `date_added` to `now()`
3. Write a script to:
   * Select N invitations ordered by `date_added` where `active` is `False`
   * Set `active` to `True`
   * Send invitation email to `email`
   * Set `date_sent` to `now()`
4. Update `mozillians_only` signal handler to `invitations_only`:
   * Check that `sociallogin.account.extra_data['email']` is in `invitations` table with `active=True`
   * Set `date_redeemed` to `now()`
   * Catch `PermissionDenied` and/or redirect other visitors to join the `invitations` with `active` set to `False` and `date_added` set to `now()`

**Comment by skim1102** [comment]
What does the `active` do other then checking to see that the email has been sent? If it only checks that the email has been sent maybe we should just use the `date_sent` column `IS NOT NULL`. 

I am worried about the 4th instruction to update the `mozillians_only` signal handler to `invitations_only`. This could exclude the users with Mozilla email address (which we would always want to allow, right?) and only allow emails in the `invitations` table. Perhaps we want to create a signal like`beta_testers_only` that checks to see if we are testing for invitations as well? Pseudocode looks like:
```
def beta_testers_only(sender, **kwargs):
    sociallogin = kwargs['sociallogin']
    email = sociallogin.account.extra_data['email']
    if waffle.switch_is_active('invitations_allowed')):
        # return True if email in invitations table AND date_sent not null
    if email.split('@')[-1] in ALLOWED_SIGNUP_DOMAINS:
        return True
    raise PermissionDenied
```
What do you think?

P.S. not sure what you normally do to allow additional beta testers from the invitations but may I recommend using `django-waffle`'s [Swtich](https://waffle.readthedocs.io/en/stable/types/switch.html#switches)? That is, if we are using the django-admin in prod.

**Comment by groovecoder** [comment]
Hmm ... `date_sent IS NOT NULL` could effectively be the same as `active=True` - just seems a bit like overloading the field with hidden meaning? No biggie though.

Good call on doing `beta_testers_only` so we can do both Mozillians and Invitees. But we're disabling django admin site in production, so we won't use waffle. More like this ...

```python
def beta_testers_only(sender, **kwargs):
    sociallogin = kwargs['sociallogin']
    email = sociallogin.account.extra_data['email']
    if email.split('@')[-1] in ALLOWED_SIGNUP_DOMAINS:
        return True
    if Invitations.objects.filter(email=email, active=True).count() > 0:
        return True
    raise PermissionDenied
```

**Comment by jens1o** [comment]
I was directed to here to ask whether you could include NDA'd contributors into the list? I'd be keen to try it out and give feedback! :)

**Comment by groovecoder** [comment]
Howdy. In working on this invitations list/table, I'll see if we can include a way to load an "arbitrary" address or list of addresses too.

**Comment by Suleman-Elahi** [comment]
How to get an invitation for Relay?

**Comment by groovecoder** [comment]
@Suleman-Elahi - we are putting invitations in place now.

Will close this issue when the invitation code has landed, and then it should go live on the site within a few days after that.

**Comment by groovecoder** [comment]
Calling this done; we're iterating on it in new individual issues.
