### ISSUE TITLE
[Chrome] The "Sign back in with your aliases” announcement appears for Chrome users eventually in the “News” menu

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1582]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with or without an active subscription on Chrome;
- Have not interacted with the “News” drop-down menu announcements yet;
- Have the Chrome-specific Relay add-on installed;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Click on the “News” button in the page header;
3. Open each announcement then close the drop-down menu;
4. Refresh the page;
5. Observe the “News” button;
6. Click on the “News” button again and observe the content;

#### Expected result:
- There should be no change after the refresh and the “News” menu should stay the same;

#### Actual result:
- After a refresh, the “News” button displays the notification badge for a new announcement. Inside the “News” menu there is now displayed the “Sign back in with your aliases” announcement which is not be available for Chrome users;

#### Notes:
- It seems that after I reproduced this once on a Premium account, the following Premium accounts I created had displayed the same behavior without me needing to access the announcements and then refresh;
- I have not been able to reproduce this on either Chrome or Firefox while not having the add-on installed. This announcement is not supposed to appear at all if a user does not have the Add-on installed;
- See attached media:
Chrome Free user:
![appearance3](https://user-images.githubusercontent.com/85748693/156186035-a40edb22-dfea-4b6f-a948-f3c8e0db5626.gif)

Chrome Premium user initially:
![appearance2](https://user-images.githubusercontent.com/85748693/156186070-98f11101-fe04-4b98-a117-83871819eb01.gif)

Chrome Premium user later:
![appearance](https://user-images.githubusercontent.com/85748693/156186100-f5056145-fed4-4eab-8b81-327d3e1bd6f7.gif)

**Comment by Vinnl** [comment]
Hmm, I think that this might have to do with the way we're currently detecting whether the user has the extension installed: wait for half a second, hope that the extension has been loaded by the time, and then check. I can't reproduce it, but that might just be my computer being faster and having loaded the extension more quickly?

If that's true, then the more robust mechanism from #1518 will hopefully resolve this soon.

**Comment by maxxcrawford** [comment]
I'm not seeing that news item at all now (on either browser)

@Vinnl Did we remove the Log back in news point all together?

**Comment by Vinnl** [comment]
@maxxcrawford No, but you need to have the add-on installed (and pointing to the site you're looking at) - did you?

**Comment by maxxcrawford** [comment]
@Vinnl Ahhh. That's it. I see it now. 

@AOiegas For testing, you'll need a dev. version of the Chrome add-on (any version will work) installed. I'll get a patch up for this. :)
