### ISSUE TITLE
Handle SNS notification for unsupported type

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#1588]
# About this Issue
We are currently [logging error](https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/10505337/) where the SNS notifications from AWS SNS has the notification type `None`. 

# Acceptance Criteria
- We should log the `eventType` to see if there is specific type of events that is passing `notificationType` to be sent with `None` and handle them appropriately.

Related to https://github.com/mozilla/fx-private-relay/issues/1587

**Comment by jwhitlock** [comment]
Let's see if we can determine the shape of these unknown notifications with the additional information.
