### ISSUE TITLE
The “Your settings have been updated” green banner doesn’t display an “X” (close) button

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1593]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version

#### Prerequisites:
- Be signed in into a Firefox Relay account;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Click on the Profile button/image from the right side of the page header;
3. Click on the “Settings” button;
4. In the Setting menu click on the “Save” button;
5. Observe the green banner that appears;

#### Expected result:
- The green banner contains an “X” button and can be clicked on to dismiss the banner;

#### Actual result:
- The banner does not display an “X” button;

#### Notes:
- Other green banners do not display the same issue;
- See attached media:

![image](https://user-images.githubusercontent.com/85748693/156387251-7cc70894-e70b-4a60-8f6f-184c674bcc82.png)

**Comment by Vinnl** [comment]
Fixed by https://github.com/mozilla/fx-private-relay/pull/1518.
