### ISSUE TITLE
The banner sections is displayed below the alias list on the dashboard if there are only Domain Aliases generated

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1596]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active Premium subscription;
- Have ONLY one Random alias created;
- Have a Domain Name (subdomain) set;
- Have at least one Custom alias created;
- Do NOT have the Relay Add-on installed, so that the Add-on CTA banner is displayed; 

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Open the card of the Random alias by clicking the downwards arrow on the right side of the card;
3. Delete the Random alias;
4. Observe the page;

#### Expected result:
- There should be no layout or display issues;

#### Actual result:
- The alias list, now containing only Custom aliases, is displayed above the banner section;

#### Notes:
- See attached media:

Only Custom aliases:
![bannerbelowaliaslist](https://user-images.githubusercontent.com/85748693/156576360-4413b08e-3346-4422-9371-d4131299d3a6.png)

**Comment by Vinnl** [comment]
Fixed by https://github.com/mozilla/fx-private-relay/pull/1518.
