### ISSUE TITLE
The description for the use cases on the interstitial page is not displayed

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1598]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox, latest release

**Preconditions:**
The interstitial page is opened in the browser.

**Steps to reproduce:**

1. Scroll to the bottom of the page at the use cases section "Use Relay email aliases anywhere".
2. Click on each of the cases.

**Actual result:**
The description is not displayed when you click on each case.

**Expected result:**
The description is displayed for each case when you click on it.

**Notes:**
N/A

![use cases issue](https://user-images.githubusercontent.com/79697848/156601954-bac50646-33b3-4ad2-86c9-e8060993fffc.gif)

**Comment by Vinnl** [comment]
Fixed by https://github.com/mozilla/fx-private-relay/pull/1518.
