### ISSUE TITLE
Consider: Only forward emails when the From: domain matches the site for which the address was generated

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#16]
See also #7.

To help encourage adoption (and not block-listing) of our domain, we can forward emails where the From: domain matches the original App/Site of the original sign-up.

That way, the App/Site can still contact their users, but a 3rd-party aggregator cannot link on the address nor spam it.

**Comment by hackel** [comment]
Along the same lines, it would be wonderful if there was an option to reject messages that do not pass SPF/DKIM validation.  Some type of rejected message counter might be nice as an indicator that an alias has been leaked to spammers.

**Comment by tcinotto** [comment]
Discussed with team and not feasible at this time.

**Comment by groovecoder** [comment]
While this issue is infeasible, https://github.com/mozilla/fx-private-relay/issues/16#issuecomment-668133289 is a good idea. I've uplifted it into https://github.com/mozilla/fx-private-relay/issues/1549.
