### ISSUE TITLE
Add Black Python formatter/linter?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fx-private-relay#160]
https://black.readthedocs.io/en/stable/installation_and_usage.html#usage

```sh
black . --exclude venv
```

Not sure how much linting for errors or issues Black does, or if it's mostly just a formatter (ESLint vs Prettier), so maybe we need to add other Python linting as well.

**Comment by groovecoder** [comment]
Do we use `black` in other python code-bases? I've always used `flake8` for python code.

**Comment by pdehaan** [comment]
I've _heard_ that we use it, but I'll ping my larger team and see if they can point me to any prior works of art.

I did find https://bugzilla.mozilla.org/show_bug.cgi?id=1555560 in my email records, but that doesn't look merged yet.

**Comment by jeroen7s** [comment]
> Do we use `black` in other python code-bases? I've always used `flake8` for python code.

Black is mostly a Code formatter, making sure all code is formatted consistently across a project, kinda like Prettier for JS.
So it's for a different purpose than Flake8.
