### ISSUE TITLE
Clicking on the “Manage your Firefox Account” link doesn’t open a new tab

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1604]
#### Build:
- Stage;
- Production;

#### Affected Platforms:
- Across platforms;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Click on the Profile button from the right side of the header;
3. Click on the “Manage your Firefox Account” link;
4. Observe the behavior;

#### Expected result:
- Clicking on the link opens it in a new tab;

#### Actual result:
- Clicking on the link opens it in the same tab;

#### Notes:
- According to the new tab icon next to the link this should be opened in a new tab;
- See attached media:
![newtab](https://user-images.githubusercontent.com/85748693/156745845-d1381523-8652-43c8-80bb-caa6c0c69a46.gif)

**Comment by Bianca-O** [comment]
This issue is not reproducible anymore on Stage, Windows 10 64-bit. The Firefox accounts page is opened in a new tab. Closing. See new situation:

![new situation](https://user-images.githubusercontent.com/79697848/161952787-bbf9321c-a63a-4fd5-886d-b5b8ea72ccce.gif)
