### ISSUE TITLE
The third step of the onboarding displays the “Go to Dashboard” button instead of the “Continue, I’ll download the extension later” link/button

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1613]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Chrome, Release version;

#### Prerequisites:
- Have a Relay account with a fresh Premium subscription;
- Do NOT have interacted with the Premium onboarding;
- Do NOT have the Relay add-on for Chrome installed;

#### Steps to reproduce:
1. Navigate to the Relay dashboard;
2. Go through the Premium onboarding until the third step;
3. Observe the contents of the third step;

#### Expected result:
- The third step displays to the user the “Continue, I’ll download the extension later” link/button;

#### Actual result:
- There is no such link/button, and instead there is the “Go to Dashboard” button;

#### Notes:
- The “Go to Dashboard” button should be displayed only if the user has the Relay add-on installed;
- See attached media:

![image](https://user-images.githubusercontent.com/85748693/157036161-48881ea6-0132-4e93-8b7f-cf2b18f25c94.png)

![image](https://user-images.githubusercontent.com/85748693/157036268-6e2f617f-6105-455e-af65-2cf219ff98f4.png)

**Comment by Vinnl** [comment]
This was fixed (either by the React migration, or by the addition of the Chrome add-on).
