### ISSUE TITLE
Investigate FTL / Fluent exceptions

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/fx-private-relay#1618]
We're getting 500 - 3,000 FTL exceptions per hour in Sentry:

https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/11770350/

Investigate if there are common causes and if any of these are fixable.

The translations repo is at https://github.com/mozilla-l10n/fx-private-relay-l10n

**Comment by Vinnl** [comment]
I think these shouldn't occur so much anymore now that most FTL strings are loaded in the front-end. (i.e. the remaining ones are probably in the email templates?).

**Comment by jwhitlock** [comment]
Yes, much lower. I looked at 5 recent ones:

* locale [da], message 'forwarded-email-footer-2'
* locale [da], message 'forwarded-email-header-from'
* locale [es-ar], message 'nav-profile-sign-out'
* locale [es-ar], message 'nav-profile-sign-out-relay'
* locale [es-ar], message 'nav-profile-help'

I think it would be useful to parse these and generate a report.

**Comment by jwhitlock** [comment]
I've created a BigQuery query to process Fluent error messages, and then some Python to make a report. I think this is a more useful way then Sentry to analyze these errors.

# Fluent Error Report

7446 errors reported between 2022-05-10 and 2022-05-11

## Supported Locales

* cs (288 errors)
    * `'forwarded-email-footer-2'`: 94 errors
    * `'forwarded-email-header-attachment'`: 6 errors
    * `'forwarded-email-header-from'`: 94 errors
    * `'logo-premium-alt'`: 94 errors
* de (201 errors)
    * `'landing-pricing-free-feature-free'`: 201 errors
* el (50 errors)
    * `'landing-pricing-free-feature-free'`: 50 errors
* en (223 errors)
    * `'landing-pricing-free-feature-free'`: 223 errors
* en-gb (201 errors)
    * `'landing-pricing-free-feature-free'`: 201 errors
* es-mx (165 errors)
    * `'landing-pricing-free-feature-free'`: 165 errors
* fr (202 errors)
    * `'landing-pricing-free-feature-free'`: 202 errors
* hu (108 errors)
    * `'landing-pricing-free-feature-free'`: 108 errors
* id (108 errors)
    * `'landing-pricing-free-feature-free'`: 108 errors
* it (186 errors)
    * `'landing-pricing-free-feature-free'`: 186 errors
* nl (168 errors)
    * `'landing-pricing-free-feature-free'`: 168 errors
* ru (401 errors)
    * `'forwarded-email-footer-2'`: 183 errors
    * `'forwarded-email-header-attachment'`: 18 errors
    * `'forwarded-email-header-cc-notice-2'`: 17 errors
    * `'forwarded-email-header-from'`: 183 errors
* sk (32 errors)
    * `'landing-pricing-free-feature-free'`: 32 errors
* uk (44 errors)
    * `'landing-pricing-free-feature-free'`: 44 errors
* zh-cn (180 errors)
    * `'landing-pricing-free-feature-free'`: 180 errors
* zh-tw (174 errors)
    * `'landing-pricing-free-feature-free'`: 174 errors

## Unsupported Locales

|Locale|Error Count|
|:-|-:|
|ar|119|
|az|2|
|be|12|
|bg|18|
|ca|128|
|da|116|
|en-au|252|
|eo|10|
|es|578|
|es-ar|214|
|es-co|12|
|es-ve|10|
|et|10|
|eu|30|
|fa|16|
|fi|556|
|ga|4|
|gl|4|
|he|64|
|ja|379|
|ka|10|
|ko|110|
|lt|24|
|lv|4|
|mr|2|
|nb|148|
|nn|6|
|pl|378|
|pt|109|
|pt-br|188|
|ro|46|
|sl|20|
|sr|16|
|sv|104|
|te|8|
|th|78|
|tr|319|
|vi|411|
|zh|100|
|zh-hans|70|
|zh-hant|30|

**Comment by say-yawn** [comment]
@jwhitlock please add the acceptance criteria for this issue to stop logging the error on Sentry since we will be using Data Studio to get the data instead.

**Comment by jwhitlock** [comment]
Acceptance criteria:

* Fluent errors are not sent to Sentry
* Recent Fluent errors can be viewed in a report by language, string code, and instance count over the time period
* Team documentation links to the report

**Comment by jwhitlock** [comment]
* Fluent error are not sent to Sentry, pushed with release v3.6.1
* The Data Studio report is setup, defaults to the previous 7 days of data. It only covers backend translations, such as email headers
* I've published the report link on our team confluence page.
