### ISSUE TITLE
[Chrome] “News” button remains highlighted if dismissed by pressing the “Esc” key

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1625]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with or without a Premium subscription;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Click on the “News” menu button from the page header;
3. Press the Esc key on your keyboard to dismiss the menu;
4. Observe the behavior;

#### Expected result:
- The menu is dismissed without any issue;

#### Actual result:
- The menu is dismissed but the button remains highlighted;

#### Notes:
- This happens for both Premium and Free users, and only on Chrome;
- This does not happen if the users dismisses the menu while inside a specific announcement;
- See attached media:
![highlightchrome](https://user-images.githubusercontent.com/85748693/157632089-9507e810-5f85-418f-a618-1470126cf4f9.gif)

**Comment by Vinnl** [comment]
Fixed by https://github.com/mozilla/fx-private-relay/pull/1518.
