### ISSUE TITLE
"Attachment size increase" announcement not aligned with the other ones in the "News" menu

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1627]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox, latest release
Chrome, latest release

**Prerequisites:**
The user has an active subscription.
The user is logged in to Firefox Relay.
The Relay add-on is installed to see the "Sign back in with your aliases" announcement.

**Steps to reproduce:**

1. Open the Relay dashboard.
2. Click the "News" menu in the header.
3. Observe the announcements.

**Actual result:**
The "Attachment size increase" announcement is not aligned with the other ones. The image is bigger.

**Expected result:**
The "Attachment size increase" announcement is aligned with the other ones.

**Notes:**
N/A

![no alignment](https://user-images.githubusercontent.com/79697848/157641388-8f07ec8b-f079-42c0-9e67-f2349b5acfd1.PNG)

**Comment by Vinnl** [comment]
I think that this was fixed by https://github.com/mozilla/fx-private-relay/pull/1601.
