### ISSUE TITLE
The “Attachment size increase” announcement is missing from the Add-on menu

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1634]
#### Build:
- Stage;
- Production;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;
- Have the Relay Add-on installed;

#### Steps to reproduce:
1. Open the Add-on menu from the toolbar menu;
2. Cycle through the announcements present;
3. Observe which are present;

#### Expected result:
- There should be the “Attachment size increase” announcement present;

#### Actual result:
- The “Attachment size increase” announcement is missing;

#### Notes:
- This announcement should be present in any situation; 
- It seems this might have been forgotten when they were rectified for the 10 MB size, as the “News” menu displays the announcement;
- See attached media:

![nosizean1](https://user-images.githubusercontent.com/85748693/157843014-18a59429-5e9f-453e-a256-d503b58f589c.png)
![nosizean2](https://user-images.githubusercontent.com/85748693/157843021-f82f1172-6b91-4018-a6f9-335a5f61f66c.png)

**Comment by joaonunomota** [comment]
I think this might no longer be wanted, since attachment size update has been moved to the history section on the website.

**Comment by jwhitlock** [comment]
Thanks @joaonunomota!
