### ISSUE TITLE
"Delete" button not visible on alias card when a long email address is used

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1641]
**Build:**
Stage

**Affected platforms:**
Android 12
iOS 15.2

**Browsers tested on:**
Firefox, latest release

**Prerequisites:**
The user is logged in to Firefox Relay.
The user has at least one alias created.
The user has a longer email address.

**Steps to reproduce:**

1. Open the Relay dashboard.
2. Go to the aliases list and expand the card of an alias.
3. Observe the email address displayed below "Forward emails to:" and the Delete buttton.

**Actual result:**
The email address is not fully visible. The Delete button is not fully visible/ not visible at all if the email address is longer.

**Expected result:**
The Delete button is visible. 

**Notes:**
N/A

![Android issue  2](https://user-images.githubusercontent.com/79697848/158411609-2ac8846a-4b6f-4239-a030-deb0b6e45fb1.jpg)

![Delete button not visible_LI](https://user-images.githubusercontent.com/79697848/158412126-f52f2d2b-cc2b-41e0-90ad-0c41c5de7429.jpg)

**Comment by RShnitser** [comment]
![Screenshot 2023-12-04 at 18-31-10 Firefox Relay](https://github.com/mozilla/fx-private-relay/assets/20136684/7e6e129a-ee83-459a-b0b6-6d3a909c9455)

The layout has changed since this was first posted and the delete button is now always on the bottom.
