### ISSUE TITLE
“News” button displays the notification badge again in the next day even if the user has already opened all the new announcements 

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1653]
#### Build:
- Stage;
- Production;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a freshly created Firefox Relay account;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Click on the “News” button in the page header;
3. Open each announcement message;
4. Observe the “News” button;
5. Wait until the next day;
6. Go to the Relay dashboard;
7. Observe the “News” button;

#### Expected result:
- The “News” button should not display the notification badge again;

#### Actual result:
- The “News” button displays the notification badge again even if the announcements have been opened before;

#### Notes:
- I do not know of an exact amount of time that has to pass before the notification badge appears again;
- See attachment:
![newsnot](https://user-images.githubusercontent.com/85748693/158605991-80ad7692-e97f-4893-8c48-a31605461691.png)

**Comment by Vinnl** [comment]
I think that this was fixed by https://github.com/mozilla/fx-private-relay/pull/1518.
