### ISSUE TITLE
Can't change my target email

### ISSUE THREAD

**Issue by ruslanbay** [mozilla/fx-private-relay#1656]
Steps:
1. Navigate to [relay.firefox.com](https://relay.firefox.com/)
2. Sign in with your Firefox account
3. Navigate to [accounts.firefox.com](https://accounts.firefox.com/settings)
4. Change your Primary email
5. Click "Generate New Alias"
6. Send a message to the new alias email

Expected results:
1. The "Successfully signed in as _____" message shows my current Primary email (target email)
2. The "Forward emails to: _________" message shows my current Primary email (target email)
3. Firefox Relay is forwarding messages to my current Primary email (target email)

Actual result: 
1. The "Successfully signed in as _____" message shows the previous email
2. The "Forward emails to: _________" message shows the previous email
3. Firefox Relay forwarding doesn't work

![screenshot](https://user-images.githubusercontent.com/67730802/158817687-635bb8e1-a5b9-4577-8823-3acc843962c7.png)

**Comment by ruslanbay** [comment]
I really want to from Apple's Hide My Email service, but Firefox Relay is too buggy right now.

**Comment by ruslanbay** [comment]
I'm a ProtonMail user, so I think the issue related to https://github.com/mozilla/fx-private-relay/issues/678

**Comment by ruslanbay** [comment]
I'll close it. Can't reproduce anymore.

**Comment by MarvinHannott** [comment]
Actually, it would be very useful if we could change the target email address per alias. Then we could also make use of sub-addressing.

**Comment by maxxcrawford** [comment]
Related to #706

**Comment by jwhitlock** [comment]
Please reach out to support to see what we can do to update your email address:

https://support.mozilla.org/en-US/products/relay

**Comment by valentinbgt** [comment]
This is what is stopping me to switch to Relay.
Please Mozilla, prioritize this feature.

EDIT : I found how to change your target Email !
1. Create a secondary email on your Mozilla account
2. Verify it
3. Promote it to primary
4. Visit this link to refresh Relay : [https://relay.firefox.com/accounts/profile/refresh](https://relay.firefox.com/accounts/profile/refresh)
