### ISSUE TITLE
“news” button in user-area wrapped line

### ISSUE THREAD

**Issue by FranklinYu** [mozilla/fx-private-relay#1700]
What I saw:

<img width="321" alt="image" src="https://user-images.githubusercontent.com/3153452/160298232-6bc9d9e1-5541-4c3a-9309-712c3d0e697b.png">

What I expected:

<img width="239" alt="image" src="https://user-images.githubusercontent.com/3153452/160298252-b415c9ad-c394-4cbd-ae5a-b45fd993b867.png">

The button can be found with HTML class `js-whatsnew-trigger` at https://relay.firefox.com/accounts/profile/.

**Comment by FranklinYu** [comment]
I don’t seen the change on https://relay.firefox.com/, so I assume that #1562 hasn’t yet been released?

**Comment by Vinnl** [comment]
Sorry @FranklinYu, that is correct - merged changes first get tested by our QA team before we publish them on the live website.
