### ISSUE TITLE
Consider using a/some top-level domains for addresses

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#172]
Some sites seem to block any addresses with subdomains?

<img width="578" alt="image" src="https://user-images.githubusercontent.com/71928/79584815-84d09a00-8094-11ea-8335-50b682d52c94.png">

**Comment by tomrittervg** [comment]
magazinestore.com also does not accept subdomains

**Comment by jwhitlock** [comment]
Thank you @joaonunomota!
