### ISSUE TITLE
The Interstitial page’s first section does not displayed the country list updated for the Sweden and Finland country expansion

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1737]
#### Build:
- Stage;

#### Affected Platforms:
- Across platforms;

#### Browsers tested on:
- Firefox, Release version;

#### Prerequisites:
- N/A;

#### Steps to reproduce:
1. Navigate to the Relay Interstitial page;
2. Observe the country list in the first section;

#### Expected result:
- The country list is this: “Relay Premium⁩ is available in the United States, Germany, United Kingdom, Canada, Singapore, Malaysia, New Zealand, Finland, France, Belgium, Austria, Spain, Italy, Sweden, Switzerland, Netherlands, and Ireland.”;

#### Actual result:
- The country list is this: “Relay Premium⁩ is currently available in Austria, Belgium, Canada, France, Germany, Ireland, Italy, Malaysia, the Netherlands, New Zealand, Singapore, Spain, Switzerland, the UK, and the US.”;

#### Notes:
- The FAQs page and the Homepage are updated correctly;
- See attached media:
Stage:
![image](https://user-images.githubusercontent.com/85748693/161940980-a51faac0-a256-40f1-81eb-321ad9d7617c.png)

**Comment by Bianca-O** [comment]
This issue is verified as fixed on stage under Windows 10. I confirm that Finland and Sweden are added to the interstitial page list of Premium available countries.
![interstitial added countries](https://user-images.githubusercontent.com/79697848/162396231-f02a404b-ff92-4629-b589-67d3c54d796e.png)
