### ISSUE TITLE
Consider enforcing a rate limit on new addresses over time, to prevent abusive behavior

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#174]
Bad actors sometimes use anonymous email addresses to spam and otherwise abuse other services.

During our alpha & beta releases, we should measure how frequently our users realistically need to create new addresses.

That could be a baseline for enforcing a rate limit on new addresses.

**Comment by moz-astults** [comment]
One approach for this that @say-yawn and I have been looking into is using the Redis `INCR` command with `EXPIRE`. A high level example is here: https://redis.io/commands/incr#pattern-rate-limiter

If a user breaches the rate limit, further requests could respond with a `429` rate limiting code for example.

**Comment by EMMLynch** [comment]
Please reopen if this is still needed.
