### ISSUE TITLE
Green successful messages for Signed in/ Signed out not displayed

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1744]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox, latest release

**Prerequisites:**
N/A

**Steps to reproduce:**

1. Navigate to Relay page and sign in.
2. On dashboard observe if the green successful message "Successfully signed in..." is displayed.
3. Sign out.
4. On homepage observe if the green successful message "You have signed out" is displayed.

**Actual result:**
Green successful messages for signed in/ signed out are not displayed anymore.

**Expected result:**
Green successful messages for signed in/ signed out are displayed.

**Notes:**
N/A

**React:**
![no green messages](https://user-images.githubusercontent.com/79697848/161991928-e3eada5d-7839-4e99-bb79-a632c899de92.gif)

**Comment by maxxcrawford** [comment]
Note that we want the toast to match VPN with this update: https://www.figma.com/file/cBaBmcPisqZ0QQX5LLzpjU/?node-id=300%3A0

**Comment by Vinnl** [comment]
@maxxcrawford Oh! I'll create a separate ticket for that, so it doesn't get lost.

As for implementation, it'll likely involve something like this. First, the back-end work, courtesy of @groovecoder. If we want to use our own strings (submitting to l10n as well):

> - disable the [built-in django-allauth messages](https://django-allauth.readthedocs.io/en/latest/advanced.html?highlight=messages#messages)
> - add more logic to [our existing signal receivers](https://github.com/mozilla/fx-private-relay/blob/main/privaterelay/signals.py) for [the corresponding ](https://django-allauth.readthedocs.io/en/latest/signals.html)django-allauth[ signals](https://django-allauth.readthedocs.io/en/latest/signals.html) which can set either cookies or headers that the front-end can pick up to display

If we want to re-use django-allauth's strings:

> you can probably leave the messages enabled, but may need to add new machinery for “send all django messages to the client”

Then you'll probably want to show the messages in a component that's used on every page: `<Layout>`. You'll probably want to reuse the functions from `frontend/src/functions/cookies.ts` to determine whether and what message to show.

You'll also only want to show it only at the first render, in the browser, which you can do by wrapping it in a [`useEffect` hook](https://reactjs.org/docs/hooks-effect.html) with an empty [dependencies array](https://reactjs.org/docs/hooks-reference.html#conditionally-firing-an-effect).

To display the toast, you can call the `toast` function, imported from `react-toastify`, also used elsewhere in the codebase. The second argument is an options object, on which you can set a `type` property to e.g. `success` or `error`.

**Comment by Vinnl** [comment]
It looks like Django's messages cookie isn't available on the client-side, and that it can only be exposed to the client side [if the session cookie is as well](https://docs.djangoproject.com/en/4.0/ref/contrib/messages/#settings), which we probably don't want to do.

Then we'll probably at least want to [disable django-allauth's messages](https://django-allauth.readthedocs.io/en/latest/advanced.html#messages) (which can be done by [creating empty message templates](https://django-allauth.readthedocs.io/en/latest/templates.html#overridable-templates)) to solve #1781. We can then separately figure out how to tell the front-end to render a "signed in" message.

**Comment by jwhitlock** [comment]
An alternative is to expose the messages as an API. The Django side [extracts and deletes them from the cookie](https://django.readthedocs.io/en/stable/ref/contrib/messages.html#django.contrib.messages.get_messages) and the front-end reads as JSON. However, if we're only using the messages framework for login and logout, disabling seems like a good solution.

**Comment by joaonunomota** [comment]
The signed in / out messages are now displayed.

Example (Prod):

![example-welsh-PROD](https://github.com/mozilla/fx-private-relay/assets/16689477/55197f99-e970-47ff-abe8-2943a7de3260)

Example (Stage):

![example-welsh-stage](https://github.com/mozilla/fx-private-relay/assets/16689477/5a5fee0f-6ed7-44f6-8067-15f657a9f4a4)

**Comment by jwhitlock** [comment]
Thanks @joaonunomota! This should have been closed with PR #1792.
