### ISSUE TITLE
Logos not visible in header and footer of received emails

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1748]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox, latest release

**Prerequisites:**
The user has a few aliases already created.
Have a second email address available.

**Steps to reproduce:**

1. Navigate to Relay page and sign in.
2. Go to aliases list and copy an alias.
3. Using a second email address send an email to the copied alias.
4. Check the inbox of the email that is connected to the alias for the email received.
5. Observe the header and the footer of the email.

**Actual result:**
The smiley face and Relay logo are not visible anymore.

**Expected result:**
The smiley face and Relay logo are visible.

**Notes:**
The issue occurs for both free and premium users.

**React:**
![logo header_footer not visible](https://user-images.githubusercontent.com/79697848/162178797-8d47f055-afcd-41ee-bfdb-fefcbb5a8d96.png)

**Before:**
![before](https://user-images.githubusercontent.com/79697848/162179133-19050d87-15ab-4d85-ba5d-2a026d8867b3.png)

**Comment by Vinnl** [comment]
How to fix this: these images are currently in `static/`, but static files are no longer being served from there. In Next.js, raw files that need to be served as-is [can be provided in the `/public/` directory](https://nextjs.org/docs/basic-features/static-file-serving), so the solution is to copy the files from `/static/images/email-images/` into `/frontend/public/static/images/email-images/`. Maybe also adding a file `/frontend/public/static/README.md` explaining why that folder exists (for backwards compatibility with already-sent emails linking to those URLs).

**Comment by groovecoder** [comment]
Note: To make it work (on localhost?) I also had to drop the `/static/` part of the img src: https://github.com/mozilla/fx-private-relay/pull/1767
