### ISSUE TITLE
2 tooltips displayed for "i" icon on header

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1772]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox, latest release

**Prerequisites:**
Have a user with an active subscription but no domain added.
Have VPN set up in a country where Relay Premium is available.
The user has skipped the onboarding steps.

**Steps to reproduce:**

1. Navigate to Relay page and log in.
2. Hover over the "i" icon on the header near the "Get your email domain" text.

**Actual result:**
2 tooltips are displayed: "More info" and "Create your unique and custom email domain".

**Expected result:**
Only one tooltip is displayed: "Create your unique and custom email domain".

**Notes:**
N/A

![2 tooltips displayed](https://user-images.githubusercontent.com/79697848/162981009-78a701ff-71fb-4304-b13d-938d9fed185c.png)

**Comment by Vinnl** [comment]
The cause of this issue is that setting an alt text on an SVG [involves](https://dequeuniversity.com/rules/axe/4.4/svg-img-alt?application=axeAPI) adding a `<title>` element, which apparently is also shown on hover. I guess an acceptable compromise would be to only set an `aria-label` while leaving `<title>` empty. The `<title>` is set via the `alt` prop on the icon component, so this can be done by setting that to `false` on [this line](https://github.com/mozilla/fx-private-relay/blob/main/frontend/src/components/InfoTooltip.tsx#L30), then adding an `aria-label` (which the component passes on to the `<svg>` element).

**Comment by suryakapurothu** [comment]
Hello @Vinnl,
Can you please guide me in rectifying the issue?
I can do it by getting assigned on this

**Comment by Vinnl** [comment]
Hi @suryakapurothu, apologies, the link and an instruction in my previous comment was incorrect. You should now be able to find proper guidance for solving this issue in [my previous comment](https://github.com/mozilla/fx-private-relay/issues/1772#issuecomment-1097841349).

**Comment by harshdevl** [comment]
@Vinnl can you confirm if this error is still reproducible? I can work on it.

**Comment by Vinnl** [comment]
@harshdevl I just checked at https://fx-relay-demo.netlify.app/accounts/profile/?mockId=some, and it appears to still be present indeed. Click the "(i)" at the top, move your cursor off the icon, then move it back on, and you'll see that it still has a tooltip in addition to the popover.

**Comment by harshdevl** [comment]
@Vinnl  Thanks for the confirmation,I have made the changes based on my understanding, and it appears to be functioning properly.

changes made to [this file](https://github.com/mozilla/fx-private-relay/blob/1ac4055a7511088b0fb609d709b2ab99e3d83829/frontend/src/components/dashboard/subdomain/SubdomainInfoTooltip.tsx#L152): 

    const ExplainerTrigger = (props: ExplainerTriggerProps) => {
    const l10n = useL10n();
    // your existing code for ExplainerTrigger
    // changes in return statement , InfoIcon alt property
    <InfoIcon
          alt={explainerState.isOpen ? "" : l10n.getString(
            hasPremium
              ? "tooltip-email-domain-explanation-title"
              : "tooltip-email-domain-explanation-title-free",
          )}
          width={18}
          height={18}
        />
     // existing code

from this : 

    <InfoIcon
          alt={l10n.getString(
            hasPremium
              ? "tooltip-email-domain-explanation-title"
              : "tooltip-email-domain-explanation-title-free",
          )}
          width={18}
          height={18}
        />

## Result : 

![Screenshot 2023-10-09 223024](https://github.com/mozilla/fx-private-relay/assets/44299483/098cb8e4-e4ec-4b12-b41b-fbd4244d258d)

![Screenshot 2023-10-09 223258](https://github.com/mozilla/fx-private-relay/assets/44299483/7195dbe9-ad66-4a56-8319-fb0607f230ec)

let me know if you want me to change my approach to solve this issue, otherwise will create a new PR. Thanks!

**Comment by Vinnl** [comment]
@harshdevl Ah clever, yeah I think that approach would work as well.

**Comment by harshdevl** [comment]
@Vinnl  Just want to confirm, Is this the only page where we are supposed to show the tooltip like this, right? And should I create the PR based on this change? Thanks for the review : )

**Comment by Vinnl** [comment]
I _think_ so, yes, though you could look for other instances of `<InfoIcon>` if you want to be more thorough. But if we miss any, we can always fix them later when we encounter them again :)

**Comment by harshdevl** [comment]
Sounds good, will check and create the PR.

**Comment by harshdevl** [comment]
@Vinnl While committing the new changes I am getting this error, can you please help me understand and solve it?

     Terminal > git commit 
      [STARTED] Preparing lint-staged...
      [COMPLETED] Preparing lint-staged...
      [STARTED] Running tasks for staged files...
      [STARTED] .lintstagedrc.js — 1 file
      [STARTED] frontend/**/*.{scss,css} — 0 files
      [STARTED] frontend/**/*.{ts,tsx,js,jsx,scss,css} — 1 file
      [STARTED] frontend/**/*.{ts,tsx,js,jsx} — 1 file
      [STARTED] *.md — 0 files
      [STARTED] *.py — 0 files
      [SKIPPED] frontend/**/*.{scss,css} — no files
      [SKIPPED] *.md — no files
      [SKIPPED] *.py — no files
      [STARTED] prettier --write
      [STARTED] next lint frontend --fix --file
      [FAILED] next lint frontend --fix --file  [FAILED]
      [FAILED] next lint frontend --fix --file  [FAILED]
      [COMPLETED] Running tasks for staged files...
      [STARTED] Applying modifications from tasks...
      [SKIPPED] Skipped because of errors from tasks.
      [STARTED] Reverting to original state because of errors...
      [FAILED] prettier --write [KILLED]
      [FAILED] prettier --write [KILLED]
      [COMPLETED] Reverting to original state because of errors...
      [STARTED] Cleaning up temporary files...
      [COMPLETED] Cleaning up temporary files...

      ✖ next lint frontend --fix --file :
        D:\Open-Source-Projects\Mozilla\fx-private-relay\node_modules\next\dist\compiled\arg\index.js:1
        (()=>{var e={774:e=>{const r=Symbol("arg flag");function arg(e,{argv:t,permissive:n=false,stopAtPositional:o=false}={}){ 
        if(!e){throw new Error("Argument specification object is required")}const i={_:[]};t=t||process.argv.slice(2);const a={};const s 
        ={};for(const t of Object.keys(e)){if(!t){throw new TypeError("Argument key cannot be an empty string")}if(t[0]!=="-"){throw 
        new TypeError(`Argument key must start with '-' but found: '${t}'`)}if(t.length===1)...

**Comment by Vinnl** [comment]
@harshdevl Hmm, I'm not entirely sure - are you running that in Git Bash?

**Comment by harshdevl** [comment]
@Vinnl Yes, currently trying to match the Node version V18.12.1

I think the problem for me is Here

    module.exports = {
      "frontend/**/*.{scss,css}": "stylelint --fix",
      "frontend/**/*.{ts,tsx,js,jsx,scss,css}": "prettier --write",
      "frontend/**/*.{ts,tsx,js,jsx}": (filenames) =>
        `next lint frontend --fix --file ${filenames
          .map((file) => file.split(process.cwd())[1])
          .join(" --file ")}`, 
      "*.md": "prettier --write",
      "*.py": ["black", "mypy"],
    }

**Comment by Vinnl** [comment]
Yeah, we use `lint-staged` to run a couple of checks when you commit, to avoid the PR from getting rejected when you submit it - but for some reason, it seems to not pass the filenames of the changed files to the linter.

You could run `npm run lint` yourself, and if that succeeds properly, skip the checks when committing by using `git commit --no-verify` instead. And then crossing our fingers that there are no other issues when you submit the PR :)

**Comment by harshdevl** [comment]
@Vinnl Got it, I'll run `npm run lint` and use `git commit --no-verify` if it passes. 🤞 Will Keep you posted on my progress. 

Thanks!

**Comment by harshdevl** [comment]
@Vinnl Thank you, I have created the PR. 

As suggested, I ran `npm run lint` and received warnings for a few files but fixed it using ` npx prettier --write .`.

**Comment by harshdevl** [comment]
@Vinnl Also, could you please guide me on which issue to tackle next? What would be the next logical and progressive issue to work on?

**Comment by harshdevl** [comment]
Sure, will do that : )
