### ISSUE TITLE
Re-logging in successfully for 7 times displays a 502 Bad Gateway Error message to the user

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1781]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;

#### Prerequisites:
- Have a Relay account;
- Do NOT be logged in the Relay account;

#### Steps to reproduce:
1. Go to the Relay homepage;
2. Log into the Relay account;
3. Log out from the Relay account;
4. Repeat until 7 logins have been done;
5. Observe the results;

#### Expected result:
- The user can log in without any issue;

#### Actual result:
- The user sees a 502 Bad Gateway Error;

#### Notes:
- This problem doesn’t come up on Production;
- It happens even if we use different, already existing accounts throughout the 7 logins;
- Switching to a different browser profile, clearing cookies or restarting the browser resolves this problem;
- I tried reproducing the error also by not doing all the 7 logins at a time. For example, I logged in a few times, then waited around 20 minutes and then got up to 7 and still got the error, or by waiting 1-2 minutes between each log in. Same result;
- See attached media:
![image](https://user-images.githubusercontent.com/85748693/163208419-9e0869e4-a517-489d-93aa-9aaf04cd2392.png)

**Comment by jwhitlock** [comment]
Re-opening until this is on stage and can be tested.

**Comment by jwhitlock** [comment]
Verified fixed in MPP-1867
