### ISSUE TITLE
Send `utm_source` to FxA's `/metrics-flow`

### ISSUE THREAD

**Issue by clouserw** [mozilla/fx-private-relay#1807]
This isn't a high priority but I noticed Relay isn't sending a `utm_source` parameter to FxA.  In [our docs](https://mozilla.github.io/ecosystem-platform/relying-parties/reference/metrics-for-relying-parties#metrics-related-query-parameters) the `utm_source` identifies an "Unambiguous identifier of site or browser UI element that linked to the page containing the beginning of the FxA sign-in/sign-up process".  I think this could be `relay.firefox.com` and would be added to [this function](https://github.com/mozilla/fx-private-relay/blob/main/static/js/analytics.js#L49).

Thanks!

**Comment by Vinnl** [comment]
For posterity: we're not currently sending anything here anymore since we switched to React (last week), but a reimplementation, including the sending of `utm_source`, can be found in https://github.com/mozilla/fx-private-relay/tree/fxa-metrics-flow.
