### ISSUE TITLE
If a user tries to register a subdomain containing uppercase letters the modal doesn’t make them aware they will be changed to lowercase letters

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1825]
#### Build:
- Stage;

#### Affected Platforms:
- Stage;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Premium Firefox Relay account ;
- Have at least one alias created;
- Do NOT have a custom subdomain chosen;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Click on the “Search subdomain” field and type any available name that contains uppercase letters;
3. Click on the “Search” button;
4. Observe the modal;

#### Expected result:
- The modal displays the chosen subdomain name, all letters lowercase;

#### Actual result:
- The modal displays the chosen subdomain name, letters still uppercase;

#### Notes:
- The introduced uppercase letters should be automatically changed to lowercase;
- When the user successfully registers the chosen subdomain, the uppercase letters are turned into lowercase letters anyway, so the user is informed too late that uppercase letters are not supported/allowed;
- This happens on the second step of the Premium Onboarding as well;
- See attached media:
![image](https://user-images.githubusercontent.com/85748693/164454911-fa99c515-a229-40f4-bdc4-84e844123bbb.png)
![image](https://user-images.githubusercontent.com/85748693/164454944-3b119904-0c53-439d-9cbd-8839db7f8143.png)

**Comment by imskr** [comment]
Can I work on this?

**Comment by Vinnl** [comment]
Freel free @imskr, and you can tag me if it's ready for review. One heads-up: we recently transitioned to React, but there's still traces of the old front-end in our codebase. The relevant changes will have to be made in the `/frontend/` directory.

(Also, if you haven't set up the entirety of Relay yet, for this issue you can also forego setting up the entire backend. If you clone the repository, if you first run `npm install` in `/frontend/`, and then `npm run dev:mocked`, you should see the UI right away if you visit http://localhost:3000. You can log in as the user `some` (you can follow [this link](http://localhost:3000/accounts/profile/?mockId=some) to do so) to simulate adding a new subdomain. All data is mock data, so after registering, you can just refresh the page to try it again.

**Comment by Vinnl** [comment]
@imskr Give a shout out here if you're starting actual work on it; until then I'd like to avoid discouraging others from picking this up :)
