### ISSUE TITLE
Firefox Relay Swedish translation late 

### ISSUE THREAD

**Issue by bittin** [mozilla/fx-private-relay#1834]
The Firefox Relay Swedish translation is now done , but 5 days late, is there any way to resync the translation for the website manually from Pontoon for you?

**Comment by Vinnl** [comment]
Thanks @bittin, that's great to hear! We're planning another deploy next week (the 26th if I recall correctly), and all translations that are in now should be included :slightly_smiling_face:

**Comment by bittin** [comment]
perfect thanks :)

**Comment by peiying2** [comment]
@bittin Pontoon and the Replay repo are in sync regularly automatically, not manually done. The deadline in Pontoon was suggestive, but not a block to sync. Your changes will be picked up in the next production push. Thank you for getting the changes in!

**Comment by tcinotto** [comment]
Thank you! We'll be getting a new release out this week, hopefully April 26th.
