### ISSUE TITLE
Filter buttons layout issue on Chrome

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1884]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Chrome, latest release

**Preconditions:**
The user is logged in to Firefox Relay on Chrome.

**Steps to reproduce:**
1. Scroll the page down once. 
2. Go to aliases list and click the filter button above the list.
3. Observe the “Reset” and “Apply” buttons.

**Actual result:**
The buttons are displayed outside the filter menu.

**Expected result:**
The buttons are correctly displayed.

**Notes:**
This happens only when you scroll the page a little bit.

![filter buttons issue chrome](https://user-images.githubusercontent.com/79697848/166473988-2759f910-a874-4fb3-b96e-c90a09694b5b.gif)

![chrome issue](https://user-images.githubusercontent.com/79697848/166474001-865d7ab5-6874-49ab-b391-cef963965305.png)

**Comment by Aniumbott** [comment]
If it's still open, I would like to contribute. 🙌

**Comment by Vinnl** [comment]
Go ahead, I don't tihnk anybody else is likely to pick this up in the short term. The issue is slightly different, because those buttons are now stacked on top of each other, but it's still the case that if the viewport is not high enough to contain the full menu, that parts of it fall out of it.

The relevant files are probably https://github.com/mozilla/fx-private-relay/blob/main/frontend/src/components/dashboard/aliases/CategoryFilter.tsx and https://github.com/mozilla/fx-private-relay/blob/main/frontend/src/components/dashboard/aliases/CategoryFilter.module.scss.

To experience this locally, clone the repository, then in the `/frontend/` directory, run `npm install`, then `npm run dev:mocked`. You should then be able to see the menu at http://localhost:3000/accounts/profile/?mockId=some.

**Comment by Vinnl** [comment]
I've just removed the assignments; whoever wants to pick this up, feel free to submit a pull request and leave a comment here :)

See [my previous comment](https://github.com/mozilla/fx-private-relay/issues/1884#issuecomment-1250047473) for some pointers on how to reproduce and where to look. Note that some React and CSS experience is required.

**Comment by Aniumbott** [comment]
Sorry not to be active for so long, I was having my mid terms, How can I join the slack team?

**Comment by Vinnl** [comment]
@Aniumbott There is no public Slack team. Ideally all discussion happens in this GitHub issue, so that it is findable and preserved for longer. [My comment above](https://github.com/mozilla/fx-private-relay/issues/1884#issuecomment-1250047473) should hopefully provide enough information to resolve this issue; if not, give a holler.

**Comment by Aniumbott** [comment]
Oh, ok.
I am getting an error while initializing the frontend by npm install then npm start.
![image](https://user-images.githubusercontent.com/76243585/194939135-757e29ab-bd74-423d-abef-187f245e0289.png)

**Comment by Aniumbott** [comment]
If I do only npm install it shows this,
![image](https://user-images.githubusercontent.com/76243585/195604675-4a518f02-367e-464a-9919-2ace48369c8d.png)
And if we do,
```
npm install --ignore-scripts
npx msw init public/ --save
```
It does what its supposed to do, but while **run dev**,
![image](https://user-images.githubusercontent.com/76243585/195607517-1be3dcd5-842b-4d8b-8e3c-75b328375f30.png)

If I remove that `NEXT_PUBLIC_DEBUG=true` for a while, it shows this,
![image](https://user-images.githubusercontent.com/76243585/195608249-aee02932-206d-4fd4-8c4a-f10b243c205d.png)
Let me know if I done anything wrong.

**Comment by jwhitlock** [comment]
@Aniumbott can you research cross-platform `package.json` scripts and convert these commands to work on Windows as well? We don't have Windows developers on staff, so you'd be helping other contributors as well.

**Comment by Aniumbott** [comment]
@jwhitlock I will be more than happy to do that, As I am very new this project so, I will be able to deep dive and understand the project as well. Let me know if anyone want collaborate, I will ask most of my doubts here only if you don't mind?

**Comment by Vinnl** [comment]
Oops @Aniumbott, that's another thing (it's listed in our README, but forgot to mention it here), but yeah, our translations are in a separate repository, and by running the command mentioned (`git submodule update --remote`), you should be able to retrieve those as well. The warning about `NEXT_PUBLIC_DEBUG` is fine I think, possibly Windows has a different way of setting environment variables? It's not a super important one anyway.

**Comment by tkranand** [comment]
is this project still open?

**Comment by jwhitlock** [comment]
@tkranand yes, but someone with Windows should confirm the bug is still reproducible. I can not reproduce the issue with the current version of Relay (`2023.07.31`) and Chrome 115.0.5790.170 on macOS Ventura 13.5 on Apple Silicon.

![Issue 1884](https://github.com/mozilla/fx-private-relay/assets/286017/857897b1-9ef3-46fb-80fb-7dd89640c9c8)

**Comment by harshdevl** [comment]
Yes, I can confirm. I am currently running this project on Windows 11 and `npm install` doesn't work in /frontend directory as expected.

![image](https://github.com/mozilla/fx-private-relay/assets/44299483/051cdeb9-acd7-4186-84f4-7c3460991d31)

after trying

      npm install --ignore-scripts
      npx msw init public/ --save
      git submodule update --remote

The issue remains the same
![image](https://github.com/mozilla/fx-private-relay/assets/44299483/eb00cc18-dcd5-4dee-b6f6-8790dd57ffe3)

**Comment by harshdevl** [comment]
I was able to fix the issue with changing the package.json file in `/frontend/` dir 

from 
     
     "scripts": {
    "dev": "NEXT_PUBLIC_DEBUG=true next dev",
    "dev:mocked": "NEXT_PUBLIC_MOCK_API=true npm run dev",
    "watch": "chokidar \"src/**/*\" \"next.config.js\" --initial --command=\"npm run watch_build\"",
    "watch_build": "NEXT_PUBLIC_DEBUG=true npm run build",
    "build": "next build",
    "build:mocked": "NEXT_PUBLIC_MOCK_API=true NEXT_PUBLIC_DEBUG=true npm run build",
    "start": "next start",
    "lint": "stylelint '**/*.scss' && prettier --check './src' && next lint",
    "licensecheck": "license-checker --excludePrivatePackages --production --onlyAllow 'MPL; MIT; BSD-3-Clause; BSD-2-Clause; 0BSD; Apache-2.0; ISC; Zlib; CC0; Unlicense; WTFPL; Unicode-DFS-2016;'",
    "test": "jest",
    "postinstall": "msw init public/ --save",
    "prepare": "if [ \"$ON_HEROKU\" != \"True\" ]; then cd .. && husky install frontend/.husky; fi"
    },

to this (window's compatible):

    "scripts": {
    "dev": "set NEXT_PUBLIC_DEBUG=true next dev",
    "dev:mocked": "set NEXT_PUBLIC_MOCK_API=true npm run dev",
    "watch": "chokidar \"src/**/*\" \"next.config.js\" --initial --command=\"npm run watch_build\"",
    "watch_build": "set NEXT_PUBLIC_DEBUG=true npm run build",
    "build": "next build",
    "build:mocked": "set NEXT_PUBLIC_MOCK_API=true NEXT_PUBLIC_DEBUG=true npm run build",
    "start": "next start",
    "lint": "stylelint '**/*.scss' && prettier --check './src' && next lint",
    "licensecheck": "license-checker --excludePrivatePackages --production --onlyAllow 'MPL; MIT; BSD-3-Clause; BSD-2-Clause; 0BSD; Apache-2.0; ISC; Zlib; CC0; Unlicense; WTFPL; Unicode-DFS-2016;'",
    "test": "jest",
    "postinstall": "IF NOT \"%ON_HEROKU%\"==\"True\" (cd .. && husky install frontend\\.husky)"
    },

after that the error is gone but the dev script won't run.
![image](https://github.com/mozilla/fx-private-relay/assets/44299483/068658f7-d146-44b2-aae1-bb0b0dce1325)

let me know, if you have any workaround for this. @jwhitlock @Vinnl

Also, might need to come up with different cross-platform compatible package.json file 

     e.g. : "test": "export NODE_ENV=dev; grunt", [on linux]
     which is "test": "(SET NODE_ENV=dev) & (grunt)", [on win32]

**Comment by Vinnl** [comment]
Yeah, as far as I know `set` is not cross-platform compatible. I think for now, the best approach is using Bash to run the npm scripts on Windows. Git, for example, ships with it, if I recall correctly - you should find "Git bash" among your applications if you've installed Git. I believe you should then be able to:

```bash
cd /d/Open-Source-Projects/Mozilla/fx-private-relay/frontend
npm install
npm run dev:mocked
```

(Possibly you might need some modifications to the path after `cd`; a quick web search seemed to tell me that this was the way to format it.)

**Comment by harshdevl** [comment]
Thank you, I understood that npm wasn't configured to use git bash as a default script executor. it's working now!

the error for the Windows machine is still there, I will start working on it.

![image](https://github.com/mozilla/fx-private-relay/assets/44299483/10f88aab-2e50-4961-bbb7-62fb9e05a0c7)

**Comment by harshdevl** [comment]
Hi, @Vinnl @jwhitlock I have fixed the error for Chrome in Windows and before submitting PR just want to confirm if this is how it should be.

![image](https://github.com/mozilla/fx-private-relay/assets/44299483/bf62bab1-a2db-4bff-9f83-4bd6c42aeabd)

![image](https://github.com/mozilla/fx-private-relay/assets/44299483/b05dcbb7-9072-4bc6-b219-3a5e99e1b608)

I have added `overflow-y: auto` in the CSS file as mentioned above by @Vinnl. 

> The relevant files are probably https://github.com/mozilla/fx-private-relay/blob/main/frontend/src/components/dashboard/aliases/CategoryFilter.tsx and https://github.com/mozilla/fx-private-relay/blob/main/frontend/src/components/dashboard/aliases/CategoryFilter.module.scss.

**Comment by Vinnl** [comment]
@harshdevl That looks good to me, assuming that the scrollbar is not visible if there is enough room for the menu :)

**Comment by harshdevl** [comment]
@Vinnl I have created PR https://github.com/mozilla/fx-private-relay/pull/3958#issue-1926541811, please review it. Thank you.
