### ISSUE TITLE
[Add-on] After generating more than 5 aliases “[Object Object] copied” message is displayed

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#189]
### Affected versions

* Nightly 77.0a1
* Private Relay add-on version 1.2.0 - https://drive.google.com/file/d/1OqZCFEwHrbUTH0q1dQUJBI43qVBaM3Hw/view

### Affected platforms

* Windows 10 and 7 x64
* Mac OS X 10.14
* Ubuntu 18.04

### Steps to reproduce

1. Launch the latest Nightly.
2. Install the Private Relay add-on and sign in.
3. In the Adress Toolbar, click on the Private Relay add-on and click on Generate Alias many times (6 times).

### Expected behavior
After generating more than 5 aliases a warning message should be displayed.

### Actual behavior

After generating more than 5 aliases “[Object Object] copied” message is displayed.
![Screenshot 2020-04-23 at 18 31 37](https://user-images.githubusercontent.com/15101135/80118198-bfed3480-8590-11ea-92d0-117c37a226fe.png)

**Comment by groovecoder** [comment]
This is fixed in 1.3.0 of the add-on available on AMO now.

**Comment by sv-hyacoub** [comment]
I confirm that this bug isn't reproducible any more on version 1.3.0.
