### ISSUE TITLE
The footer of relayed emails displays the incorrect logo/icon of Relay

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1894]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;
- Have at least one mask created;
- Have a different email prepared;

#### Steps to reproduce:
1. From the second email send an email to one of your Relay masks;
2. Check the inbox of the email linked to Relay;
3. Observe the footer of the email;

#### Expected result:
- The email footer displays the right image/logo of Relay;

#### Actual result:
- The email footer displays an outdated/wrong image/logo for Relay;

#### Notes:
- Initially posted by Bianca in another issue, divided by Maxx;
- See attached media:
![image](https://user-images.githubusercontent.com/85748693/166921477-46bdde3d-d924-434d-826c-784d9bfc3158.png)

**Comment by joaonunomota** [comment]
The footer for relayed emails has since been updated in https://github.com/mozilla/fx-private-relay/pull/2940 and is using a logo matching the one on the website.

Example

![image](https://github.com/mozilla/fx-private-relay/assets/16689477/fbb46f76-abed-4353-bb23-70c89bb57f2b)

**Comment by Vinnl** [comment]
Good point, thank you!
