### ISSUE TITLE
[Website] Reloading the page after turning Off the toggle turns it back to On

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#190]
### Affected versions

* Nightly 77.0a1
* Private Relay add-on version 1.2.0 - https://drive.google.com/file/d/1OqZCFEwHrbUTH0q1dQUJBI43qVBaM3Hw/view

### Affected platforms

* Windows 10 and 7 x64
* Mac OS X 10.14
* Ubuntu 18.04

### Steps to reproduce

1. Launch the latest Nightly.
2. Go to "https://relay.firefox.com" and login into your account.
3. Create New Relay Alias.
4. Turn off the toggle button.
5. Reload the page.

### Expected behavior

Reloading the page after turning Off the toggle should remain Off

### Actual behavior

Reloading the page after turning Off the toggle turns it back to On

**Comment by groovecoder** [comment]
This seems to be fixed already as of Friday's deployment? I couldn't reproduce it.

**Comment by sv-hyacoub** [comment]
I confirm that this bug isn't reproducible any more on version 1.3.0.
