### ISSUE TITLE
“Copied!” tooltip is not displayed when clicking on a mask on the dashboard

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1909]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;
- Have at least one alias created;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Click on any of the masks generated;
3. Observe the results;

#### Expected result:
- Clicking on a mask copies it and displays a “Copied!” tooltip to tell the user that;

#### Actual result:
- Clicking on a mask copies it but doesn’t display the “Copied!” tooltip;

#### Notes:
- See attached media:
![tooltip](https://user-images.githubusercontent.com/85748693/167413122-c0cc3cee-841c-4970-a0d9-23baaae6e1d6.gif)

**Comment by joaonunomota** [comment]
Clicking on a mask is showing a tooltip with "Copied!", this issue can be closed I think.

Example:

![example-copy](https://github.com/mozilla/fx-private-relay/assets/16689477/a0105a23-0a5a-4604-840d-fcaabfa29d89)

**Comment by jwhitlock** [comment]
Thanks @joaonunomota, it works for me as well on Firefox Nightly 116.0a1 and Safari 16.5, on macOS Ventura 13.4.
