### ISSUE TITLE
No expand/ collaps arrow button displayed on mask card on mobile

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1920]
**Build:**
Stage

**Affected platforms:**
Android 12
iOS 15.4

**Browsers tested on:**
Firefox, latest release

**Preconditions:**
Have a few aliases already created.

**Steps to reproduce:**
1. Go to Relay page and log in using an account with or without an active subscription.
2. Scroll to the masks list and observe the masks cards.

**Actual result:**
No arrow button is visible to inform the user that the card can be expanded/ collapsed.

**Expected result:**
An arrow button is visible informing the user that the card can be expanded/ collapsed.

**Notes:**
N/A

https://user-images.githubusercontent.com/79697848/167631297-8c2b41f7-aed8-485e-babc-33edfbdba0af.mp4

**Comment by Vinnl** [comment]
Another report at #1941:

> #### Build:
> 
>     * Stage;
> 
> 
> #### Affected Platforms:
> 
>     * Android 9 and 11;
> 
> 
> #### Browsers tested on:
> 
>     * Firefox, Release version;
> 
> 
> #### Prerequisites:
> 
>     * Be signed in into a Firefox Relay account;
> 
>     * Have at least one alias created;
> 
> 
> #### Steps to reproduce:
> 
>     1. Go to the Relay dashboard;
> 
>     2. Scroll down to the mask list section;
> 
>     3. Observe the unopened mask cards;
> 
> 
> #### Expected result:
> 
>     * There should be a button for expanding individual mask cards;
> 
> 
> #### Actual result:
> 
>     * There is no button to expand the mask cards;
> 
> 
> #### Notes:
> 
>     * Freshly generated masks are displayed with the card expanded, but there is still no button for expanding or collapsing the card;
> 
>     * See attached media:
>       ![image](https://user-images.githubusercontent.com/85748693/168293235-37925421-7fe0-48e5-a776-f8b117a8807d.png)
>       ![image](https://user-images.githubusercontent.com/85748693/168293363-3599f392-cdfd-4cff-b7fe-4da58a08c986.png)
> 
> 
> Desktop example: ![image](https://user-images.githubusercontent.com/85748693/168293719-f790100c-8032-4251-9195-f8d84aced8f5.png)
