### ISSUE TITLE
The “Social Network” and “Gaming” use cases from the Relay homepage are missing content

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1940]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Do NOT be signed in into a Firefox Relay account;

#### Steps to reproduce:
1. Go to the Relay homepage;
2. Scroll down to the use cases section;
3. Click on the “Social Network” use case and observe it;
4. Click on the “Gaming” use case and observe it;

#### Expected result:
- Clicking on the use cases should display content specific to each;

#### Actual result:
- The “Social Network” and “Gaming” use cases do not display all of their content;

#### Notes:
- See attached media:
![hp1](https://user-images.githubusercontent.com/85748693/168246909-e1877a88-e20a-44e2-bc20-481cc4a856f8.png)
![hp2](https://user-images.githubusercontent.com/85748693/168246919-372caff8-092e-44a7-ad00-09cf91ff450b.png)

**Comment by Vinnl** [comment]
Fixed by https://github.com/mozilla/fx-private-relay/pull/1943.
