### ISSUE TITLE
The green successful banner seems to be bigger than it is displayed

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1955]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Sign out of your Relay account;
3. Wait a bit until the green successful banner is displayed;
4. While the banner is displayed, try clicking on the header buttons (“Home”, “FAQ”, “Sign Up”, and “Sign In”)

#### Expected result:
- The user can click on the buttons and they work correctly;

#### Actual result:
- Clicking on the buttons does nothing;

#### Notes:
- After the banner disappears (including dismissing it) this issue is not happening anymore and the buttons work correctly;
- This happens when logging in as well;
- To me it seems this is because the banner is bigger than it actually is displayed. The “Firefox apps and service” button is clickable and works correctly while the banner is displayed, meaning it is outside of the banner’s actual area/size;
- See attached media:
![banner](https://user-images.githubusercontent.com/85748693/168833845-08666a4f-9539-471c-9497-14366d1ec2c8.gif)

**Comment by lloan** [comment]
Fixed with #1981
