### ISSUE TITLE
[Website] The "Cancel" button inside the confirmation door hanger is auto-focused 

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/fx-private-relay#196]
**Affected versions**
* latest Nightly 77.0a1

**Affected platforms**
* Windows 10 x64
* macOS 10.15
* Ubuntu 18.04 x64

**Prerequisites**
* Firefox is opened.
* Have the Private Relay add-on version 1.2.0 installed - https://drive.google.com/file/d/1OqZCFEwHrbUTH0q1dQUJBI43qVBaM3Hw/view.

**Steps to reproduce**
1. Access https://relay.firefox.com/ and login with your @mozilla.com account.
2. Create at least one Relay alias using the website.
3. From the newly created alias click on the trash icon.
4. Inspect the appeared doorhanger.

**Expected result**
* None of the two buttons, "Cancel" or "Delete" is auto-focused.

**Actual result**
* "The "Cancel" button is auto-focused.

**Additional notes**
* please observe the attached screenshot
![Screenshot from 2020-04-24 09-27-17](https://user-images.githubusercontent.com/43886441/80181601-d71e3780-860d-11ea-8826-9696d225e93f.png)

**Comment by sbadau** [comment]
This issue is no longer reproducible since the design of the Firefox Relay website changed significantly.

@groovecoder can this issue be closed?
