### ISSUE TITLE
[Mobile] The use cases are not collapsed when user taps on them 

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#1961]
**Build:**
Stage

**Affected platforms:**
Android 12
iOS 15.4

**Browsers tested on:**
Firefox, latest release

**Preconditions:**
N/A

**Steps to reproduce:**
1. Go to Relay homepage.
2. Scroll to the use cases section and tap on one to expand it.
3. Tag again to colapse it's content.

**Actual result:**
The use case content is not collapsed when user taps on it again. It is collapsed only when another use case is expanded.

**Expected result:**
The use case content is collapsed when user taps on it again.

**Notes:**
N/A

https://user-images.githubusercontent.com/79697848/169015259-413c241e-645f-44ef-97ef-df09d90b63cf.mp4

**Comment by joaonunomota** [comment]
https://github.com/mozilla/fx-private-relay/pull/3075 removed use cases from the home page, so I think this issue can be closed.

The `Carousel` component still exists in the codebase, so this would still be an issue if it is used somewhere again.

**Comment by jwhitlock** [comment]
Thanks, I agree this can be closed. There may be some dead code and related images that can be removed at https://github.com/mozilla/fx-private-relay/tree/main/frontend/src/components/landing/carousel
