### ISSUE TITLE
Deleting a mask that has forwarded emails subtracts from the “Emails Forwarded” counter displayed to Premium users

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#1971]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Premium Firefox Relay account;
- Have at least one mask created which has forwarded some emails;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Observe the “Emails Forwarded” counter from the page header;
3. Delete the mask that has forwarded some emails;
4. Repeat step 2 and observe the results;

#### Expected result:
- The number of “Forwarded Emails” shown by the counter should be the same;

#### Actual result:
- The number of “Forwarded Emails” shown by the counter has changed;

#### Notes:
- See attached media:
![forwarded emails](https://user-images.githubusercontent.com/85748693/169524582-583ad95a-7b65-496c-8000-086d8c5ab675.gif)

**Comment by say-yawn** [comment]
The number is available in `profile` backend but the profile API endpoint is not displaying the value.  To get the right numbers you need to add the `emails_forwarded` and `emails_blocked` on https://github.com/mozilla/fx-private-relay/blob/503f0995026350f782735c4f56ca8304843d06e9/api/serializers.py#L98-L121
on both `read_only_fields` and `fields`.

**Comment by joaonunomota** [comment]
Is there still anymore work needed for this issue? Looks like https://github.com/mozilla/fx-private-relay/pull/2080 fixes this one.

**Comment by jwhitlock** [comment]
Thanks @joaonunomota!
