### ISSUE TITLE
Disable certain paths from django-allauth

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#1995]
# About this Issue
Some of the paths on `/accounts` should be disabled because we are not using `django-allauth` to do account management because we are redirecting users to Firefox Accounts (FxA) instead. Some of these paths are returning an `OSError` and we should handle them:
- [/accounts/signup/Z](https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/19481400/?query=is%3Aunresolved%20oserror)
- [/accounts/email/Z](https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/19479616/?query=is%3Aunresolved%20oserror)
- [/accounts/password/reset/Z](https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/19480545/?query=is%3Aunresolved%20oserror)

# Acceptance Criteria
- [ ] Figure out which paths under `/accounts` are being used to handle account management on Relay
- [ ] Disable and return 404 for unused paths
- [ ] Check `dkango-allauth` to see what configurations needs to be set to prevent these errors in the future

**Comment by groovecoder** [comment]
Ooo, yeah there's only a couple of urls we need for OAuth:

* /accounts/fxa/login
* /accounts/fxa/login/callback

**Comment by jwhitlock** [comment]
We also need `/accounts/logout/`, but I think that's it.
