### ISSUE TITLE
[Button] Saved logins are displayed blank in the saved logins dropdown

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#200]
### Affected versions

* Nightly 77.0a1
* Private Relay add-on version 1.2.0 - https://drive.google.com/file/d/1OqZCFEwHrbUTH0q1dQUJBI43qVBaM3Hw/view

### Affected platforms

* Mac OS X 10.14

### Steps to reproduce

1. Launch the latest Nightly.
2. Install the Private Relay add-on and sign in.
3. Create an account or save a login on https://stackoverflow.com or any other account.
4. Create an account or save a login on aliexpress.com or any other account.
5. Access facebook.com and click on the email field.

### Expected behavior

Saved logins should be correctly displayed in the saved logins dropdown.

### Actual behavior

Saved logins are displayed blank in the saved logins dropdown.
![Screenshot 2020-04-24 at 12 14 44](https://user-images.githubusercontent.com/15101135/80201680-2758c200-862d-11ea-870f-b2934ef83e4c.png)

**Comment by groovecoder** [comment]
Sadly, this is an upstream, Firefox-wide bug with Nightly 77 on Mac OS 10.14.

https://bugzilla.mozilla.org/show_bug.cgi?id=1632488
