### ISSUE TITLE
Clicking on ANY of the “Get unlimited masks” buttons of the Add-on makes the add-on look as though the user is signed out

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#2009]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;

#### Prerequisites:
- Be signed in into a Free Firefox Relay account;
- Have at least one mask created;
- Have the Relay Add-on installed;
- Have the “Show Relay icon in email fields on websites” option turned on;

#### Steps to reproduce:
1. Go to any site that has a fill-able email field;
2. Click on the Relay Field Icon;
3. In the opened menu, click on the “Get unlimited masks” button;
4. Go back to the initial site and click again on the Relay Field Icon;
5. Observe the menu

#### Expected result:
- The menu presents no change;

#### Actual result:
- The menu looks like the user is signed out;

#### Notes:
- This happens for ALL add-on menus: Field Icon Menu, Context Menu, Toolbar Menu;
- This issue is not happening on Chrome. A difference to be noted here: on Firefox, when a user clicks on the CTA the menu automatically closes, while on Chrome it does not close (in case this is helpful);
- See attached media:

![logout](https://user-images.githubusercontent.com/85748693/170487097-a1ef629f-318a-44d2-a29b-16790f45a1d8.gif)

**Comment by maxxcrawford** [comment]
Transferred this issue from the add-on repo. It may be solved by https://github.com/mozilla/fx-private-relay/pull/1883. 

@lloan Can you confirm if this behavior exists in the new version of the mobile nav?

**Comment by lloan** [comment]
@maxxcrawford #1883 doesn't change how some of the menus work - it just adds the mobile menu component + updates styling. The logic is pretty much still the same. I can't replicate on my end, maybe once its on staging?
