### ISSUE TITLE
whitenoise package needs to be updated

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#2025]
# About this Issue
We saw Sentry events for `TypeError` `'>=' not supported between instances of 'NoneType' and 'tuple'` which is caused by one of the packages we use called `Whitenoise`. We are currently using `5.0.1` as seen here:
https://github.com/mozilla/fx-private-relay/blob/71cc24cce6b2fe45821a84e8f72fa4867784fe7d/requirements.txt#L30
but we should be using 5.3.0 as mentioned as a fix [here](https://whitenoise.evans.io/en/stable/changelog.html#id3).

Dependabot is not catching the update because it is watching a fork of the original `whitenoise` repo instead. 

Sentry issue: https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/19480298/
Public: https://sentry.prod.mozaws.net/share/issue/e36430063a614ef3ae3dc8a377c1b5c6/

**Comment by jwhitlock** [comment]
Submitted upstream feedback about Dependabot and Whitenoise:

https://github.com/github/feedback/discussions/17563
