### ISSUE TITLE
Icons have different color

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#2049]
**Build:**
Stage

**Affected platforms:**
Windows 10

**Browsers tested on:**
Firefox, latest release

**Preconditions:**
N/A

**Steps to reproduce:**
1. Go to Relay homepage and log in using a free/ premium account.
2. Click the Profile icon to open the menu and observe the color of the icons for the submenus.
3. Click the Settings submenu and compare the icons of the links with the icons of the Profile submenus.

**Actual result:**
The icons of the Settings links have a different color than the icons of the Profile submenus. 

**Expected result:**
The icons have the same color.

**Notes:**
N/A

![colors](https://user-images.githubusercontent.com/79697848/172176260-ec65182d-ac6a-44a7-92cf-618953cef4e1.png)

**Comment by jwhitlock** [comment]
Thanks @joaonunomota!
