### ISSUE TITLE
Suggest : It would be great to have access to your emails without going to the relay page.

### ISSUE THREAD

**Issue by lbnesquik** [mozilla/fx-private-relay#2060]
See title. 

Ideally, when i click the little extension icon, a little window open with my current active proxies, their destination and a button to copy it.

**Comment by joaonunomota** [comment]
I think this has been resolved by https://github.com/mozilla/fx-private-relay-add-on/pull/463 and https://github.com/mozilla/fx-private-relay-add-on/pull/456, the extension includes a list of all the proxies with a label and copy button.

It is only missing the destination, but as far as I know the extension only shows proxies for one account.

Example:


<img src="https://user-images.githubusercontent.com/16689477/236448835-cc49aeba-8058-449a-a82e-8b13ed7df96b.png" height="400">

**Comment by Vinnl** [comment]
Yep, AFAICS that covers it, thanks for circling back @joaonunomota!

@lbnesquik feel free to file a new issue if you feel this has been insufficiently addressed.
