### ISSUE TITLE
A few icons in the new navigation are rendering incorrectly.

### ISSUE THREAD

**Issue by lloan** [mozilla/fx-private-relay#2063]
The issue is that some icons are not using the correct color as presented in the Figma. 

The correct styling can be seen in the [demo version](https://deploy-preview-1883--fx-relay-demo.netlify.app/).

This icon should be using `$color-white` and hover state should be `$color-violet-20`

<img width="393" alt="image" src="https://user-images.githubusercontent.com/3924990/172767261-06c88115-9885-4a28-94db-bcf31e0adeb6.png">

The icons in the mobile menu should be using `$color-violet-40`

<img width="366" alt="image" src="https://user-images.githubusercontent.com/3924990/172767670-6bf2f463-d903-45b1-aea4-cf72a32a6931.png">

The mobile menu icons should look like this:  (icon colors)
<img width="513" alt="image" src="https://user-images.githubusercontent.com/3924990/172767717-40167d15-d161-48bc-a248-90ae184a7457.png">

Icons show correctly in the demo version on Netlify. 

Demo can be found [here](https://deploy-preview-1883--fx-relay-demo.netlify.app/).
Staging version [here](https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/).

**Comment by Vinnl** [comment]
Interestingly, when I check out [the tag that's currently on stage](https://github.com/mozilla/fx-private-relay/releases/tag/v3.5.10), I see at least the issue with the Bento icon, but I don't see it on latest `main` (also used on the demo site). I don't see any particular [change](https://github.com/mozilla/fx-private-relay/compare/v3.5.10...main) in there that I'd expect to fix this, apart from possibly some of the dependency updates, but it does look like something has fixed it.

**Comment by Vinnl** [comment]
For testing, note that this also caused #2097:

> #### Build:
> 
>     * Stage;
> 
> 
> #### Affected Platforms:
> 
>     * Windows 10;
> 
> 
> #### Browsers tested on:
> 
>     * Firefox, Release version;
> 
>     * Chrome, Release version;
> 
> 
> #### Prerequisites:
> 
>     * Do NOT be signed in into a Firefox Relay account;
> 
> 
> #### Steps to reproduce:
> 
>     1. Go to the Relay Home page and scroll down to the AMO reviews section;
> 
>     2. Observe the stars above the rating;
> 
>     3. Observe the stars and the quotation marks above the review displayed;
> 
> 
> #### Expected result:
> 
>     * The stars should be yellow/golden, and the quotation marks should be purple;
> 
> 
> #### Actual result:
> 
>     * All the stars and quotation marks that are initially displayed are black;
> 
> 
> #### Notes:
> 
>     * Moving to a different review switches the stars and quotation marks related to the review to the right colors, including for the initial review, but not for the add-on rating;
> 
>     * See attached media:
>       Stage:
>       ![image](https://user-images.githubusercontent.com/85748693/174557108-2273643b-474c-4c17-9de4-3901931e9e84.png)
>       Figma reference:
>       ![image](https://user-images.githubusercontent.com/85748693/174557174-73be527e-d3f1-4f7b-9e7f-6a93ff301b44.png)
>       Stage gif:
>       ![color](https://user-images.githubusercontent.com/85748693/174557274-33594aa8-c96c-4007-a591-aec6f897de85.gif)
>             
>               [
>                 
>               ](https://user-images.githubusercontent.com/85748693/174557274-33594aa8-c96c-4007-a591-aec6f897de85.gif)
