### ISSUE TITLE
"Contact us" does not link to any contact method

### ISSUE THREAD

**Issue by bcolsson** [mozilla/fx-private-relay#2118]
Build:
- Production

Browsers tested on:
- Firefox Nightly (Mac OS)
- Safari (iOS)

Prerequisites:
- Be signed in into a Firefox Relay account

Steps to reproduce:
- Click on profile
- Click on Contact us
- Observe page being redirected to FxA settings page

Expected result:
- Link directing user to some form of contact page

Actual result:
- User redirected to page with no apparent method of getting in contact

Notes:
Currently, clicking the "Contact us" option from the profile menu links to `https://accounts.firefox.com/support/?utm_source=` however this redirects to `https://accounts.firefox.com/settings` which does not have any apparent way to contact support.
![Screen Shot 2022-06-23 at 16 08 20](https://user-images.githubusercontent.com/38174554/175431238-345b6aa0-6010-47e4-99c4-1af7657d5fa1.png)

**Comment by rafalkrupinski** [comment]
I see a contact form
