### ISSUE TITLE
Account information out of sync

### ISSUE THREAD

**Issue by SzVLsY** [mozilla/fx-private-relay#2123]
I registered a new account to log in to Privacy Forward and then I set my icon, but my icon is not being synced.

And, I changed my email address and my email address is not synced either

**Comment by jwhitlock** [comment]
@SzVLsY, thanks for reaching out. This issue tracker is specific to the Relay code, and it sounds like you are having an issue with the Relay product (or a different product). Please try the support site at:

https://support.mozilla.org/products/relay/

This article, [Change primary email address on Firefox Accounts](https://support.mozilla.org/en-US/kb/change-primary-email-address-firefox-accounts), seems like it may be relevant. The last line is:

> You might have to log out and log back in to Firefox Accounts on your mobile devices in order for Firefox to display your new email. 

You may also need to log out and back into the Relay site to see changes to your Firefox Account.
