### ISSUE TITLE
“Phone Number” tab is not highlighted when a user is on the phone Number page

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#2132]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;

#### Steps to reproduce:
1. Go to the Relay Phone Number page;
2. Observe the Phone Number tab in the site header;

#### Expected result:
- The “Phone Number” tab is highlighted on the site header;

#### Actual result:
- The tab is not highlighted;

#### Notes:
- See attached media:
![phnu](https://user-images.githubusercontent.com/85748693/176198846-cca3817c-b33d-4286-9f96-addfc14f6384.gif)

**Comment by joaonunomota** [comment]
The "Phone Number" tab is currently highlighted for premium (demo website) and free users (production).

Example (Premium):

![image](https://github.com/mozilla/fx-private-relay/assets/16689477/0db8491d-fba2-43cd-92cf-d0c948303884)

Example (Free):

![example](https://github.com/mozilla/fx-private-relay/assets/16689477/3be91118-8cd6-47ea-8572-8fbae7907188)

**Comment by jwhitlock** [comment]
Thanks @joaonunomota, works for me as well!
