### ISSUE TITLE
[Context Menu] The email alias generated from the context menu isn't visible

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#215]
### Affected versions

* Nightly 77.0a1
* Private Relay add-on version 1.2.0 - https://drive.google.com/file/d/1OqZCFEwHrbUTH0q1dQUJBI43qVBaM3Hw/view

### Affected platforms

* Mac OS X 10.14
* Windows 10
* Ubuntu 18.04

### Steps to reproduce

1. Launch the latest Nightly.
2. Install the Private Relay add-on and sign in.
3. Go to "https://www.tripadvisor.com/", "espn.com".
4. Click on "Sign in" button -> "Continue with email" button.
5. Right click on the "Email" field -> "Generate email alias".

### Expected behavior

The email alias generated from the context menu should be visible.

### Actual behavior

The email alias generated from the context menu isn't visible.

**Comment by groovecoder** [comment]
Email generated from context menu shows up on tripadvisor.com. There's a different issue with the button affecting it, but there's already a separate issue for that.

**Comment by sv-hyacoub** [comment]
This issue isn't reproducible anymore on Firefox 77.0.1 using Firefox Relay Beta add-on version 1.4.1 on Windows 10, Mac OS X 10.15 and on Ubuntu 18.04.
