### ISSUE TITLE
The alias names are gone (account names)

### ISSUE THREAD

**Issue by kanlukasz** [mozilla/fx-private-relay#2163]
My aliases had names defined. Unfortunately, for unknown reasons, they stopped being displayed.
So now I don't know what each of the aliases was used for. Very annoying 🙄

![image](https://user-images.githubusercontent.com/30685349/177478487-38d21d4f-f7f8-4959-85ed-202712225a69.png)

Add-on version: `2.4.2`
Firefox version: `102.0 (64-bit)`
OS: `Win 10 21H2`

**Comment by jwhitlock** [comment]
@kanlukasz, I'm sorry that happened to you. There were similar issues reported to our support team (via https://support.mozilla.org/en-US/products/relay), and a bug was found with the add-on (issue #2098). Please update to add-on version 2.4.3 or later.
