### ISSUE TITLE
The orange warning icon on Settings page is very small

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#2191]
**Build:**
Production

**Affected platforms:**
Windows 10

**Browsers tested on:**
Firefox, latest release
Chrome, latest release

**Preconditions:**
The Data Collection is turned ON.

**Steps to reproduce:**
1. Go to Relay page and log in using an existing account.
2. Click the Profile button and then the Settings button.
3. Uncheck the Privacy checkbox and observe the warning icon displayed before the "This data will allow us to label..." text.

**Actual result:**
The orange warning icon is very small and barely visible.

**Expected result:**
The orange warning icon has a bigger dimension like before.

**Notes:**
N/A

![warning icon very small](https://user-images.githubusercontent.com/79697848/178756516-9e033cde-e7cc-4865-b782-760e03ebfd94.png)

**Comment by mariaberlinger** [comment]
This issue is verified as fixed on stage under Windows 10 and Android 12, on Chrome and Firefox. The icon has the same size on both browsers.
