### ISSUE TITLE
[Mobile] “Social Networks” and “Gaming” use cases from the Relay Home page do not display their title in the opened card

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#2193]
#### Build:
- Stage;
- Production;

#### Affected Platforms:
- Android 11;

#### Browsers tested on:
- Firefox, Release version;

#### Prerequisites:
- Do NOT be signed in into a Firefox Relay account;

#### Steps to reproduce:
1. Go to the Relay Home page;
2. Scroll down to the Use Cases section;
3. Tap on the “Social Networks” use case and observe its opened card;
4. Tap on the “Gaming” use case and observe its opened card;

#### Expected result:
- The opened cards should display the title of the Use Cases;

#### Actual result:
- The opened cards do not display the titles of the Use Cases;

#### Notes:
- This issue is not present on Desktop;
- This issue might be present because of the difference in content compared to the other Use Cases;
- See attached media:
Mobile:
![01](https://user-images.githubusercontent.com/85748693/178958200-27f13d62-6197-4c07-ab0a-d56782f75d7f.JPEG)
![02](https://user-images.githubusercontent.com/85748693/178958210-bb75e51c-2646-40ba-b022-2b54da531179.JPEG)

Desktop comparison:
![image](https://user-images.githubusercontent.com/85748693/178958333-e02a7507-c159-4a7c-9efc-ff461e1c4e86.png)
![image](https://user-images.githubusercontent.com/85748693/178958386-750cdf83-9205-416a-8c20-e06b7d829047.png)

**Comment by joaonunomota** [comment]
https://github.com/mozilla/fx-private-relay/pull/3075 removed use cases from the home page, so I think this issue can be closed.

**Comment by jwhitlock** [comment]
Thanks @joaonunomota!
