### ISSUE TITLE
[Website] "Firefox Apps" menu-icon gets into a broken state if you click it while its menu is closing

### ISSUE THREAD

**Issue by dholbert** [mozilla/fx-private-relay#221]
STR:
 1. Visit https://relay.firefox.com/
(or any website that has the 3x3 grid-of-squares "firefox apps" menu at top-right. I'm not sure if this is a Relay-website-only thing or a more general Mozilla webdesign widget)

 2. Click the grid of squares near the top right, to open the Firefox Apps menu.

 --> now the menu is open.

 3. **Double-click** the same icon, to close the menu.  (Or, equivalently: click it once, and inadvertently click it again while the menu-closing-animation is playing).

 --> now the menu is closed.

 4. After the menu has closed: click the icon again.

EXPECTED RESULTS:
The menu should open in response to my click in step 4.

ACTUAL RESULTS:
Nothing happens in response to my click in step 4.

It seems that the click-during-menu-closing gets the menu into a confused state where it doesn't know if it's open or closed. So the click in step 4 doesn't actually open it, and it looks like stuff's broken.

Note that an *additional* click (after step 4) does seem to successfully open the menu.  So at most one click gets "eaten" & has no effect, I think. (But it still feels broken for that click to be eaten.)

**Comment by groovecoder** [comment]
I had trouble reproducing this reliably.

**Comment by dholbert** [comment]
Odd - I can reproduce ~100% reliably, if I use a rapid double-click on the menu button (while the menu is open) to close the menu.  When I do this, the next click on the menu button always gets eaten/ignored somehow.

This reliably happens for me in Firefox Nightly as well as in Chrome (on Linux, though platform probably doesn't matter much here).

**Comment by dholbert** [comment]
Here's a screencast of me reproducing 3x in Firefox and then once or twice in Chrome.  Each time the menu closes, it's from me double-clicking the menu icon -- and then then I wait a second, and click the icon again (which you can see via the "pulse" color change on the icon), which fails to open the menu.

https://www.dropbox.com/s/g4sbni270bsblty/apps-grid-icon.webm?dl=0
