### ISSUE TITLE
Adds a custom note on each alias

### ISSUE THREAD

**Issue by codingepaduli** [mozilla/fx-private-relay#2212]
Please, let the user adds a custom note on each alias created and to show that in the list page, in order to remember him/her where he/she use the alias or for which feature.

I add a screenshot for a better description. 

![Enhancement](https://user-images.githubusercontent.com/52714870/179502670-929affd2-ee3a-4ac2-82a7-71fdd0670e39.png)

Thanks

**Comment by Vinnl** [comment]
Hi @codingepaduli, this is already possible! However, you need to allow Relay to store that data on its servers; see https://support.mozilla.org/en-US/kb/firefox-relay-get-your-labels-all-your-devices.

Feel free to re-open if it doesn't work for you.
