### ISSUE TITLE
Sender email address is displayed truncated in gmail

### ISSUE THREAD

**Issue by dholbert** [mozilla/fx-private-relay#223]
This might be more of a Gmail bug than anything, but it's triggered by Firefox Private Relay, so I suppose it's worth reporting.

My STR:
(1) I signed up for Firefox Private Relay
(2) I changed my Firefox Account to use my personal email address as my primary email address.
(3) I sent an email from my @mozilla.com email address to my "relay" virtual email address
(4) I looked at this email in my personal Gmail inbox

ACTUAL RESULTS:
In my Gmail in box view, the email is shown as being "From: dholbert@mozilla.co."  If I hover that address, it shows up as a little card with that same bogus address, too.

EXPECTED RESULTS:
I would expect the email address to be shown as "mozilla.com", OR I would expect the full "sender name" to be shown (ellipsized as-needed), because I think in fact what's being shown/truncated here is the sender-name which is "dholbert@mozilla.com via Firefox Private Relay" which I can see if I actually open the email.

**Comment by dholbert** [comment]
Here's what I see in my Gmail inbox:
![image](https://user-images.githubusercontent.com/426803/80420020-faa3e500-888e-11ea-887f-61ae2b8a18a9.png)

**Comment by dholbert** [comment]
(At first I was guessing that maybe this was just broken client-side ellipsizing on Firefox's end, or something, but no -- the page's DOM literally contains the text `dholbert@mozilla.co.` here, and I double-checked that Chrome matches our rendering of my gmail inbox, too.)

**Comment by groovecoder** [comment]
This is fixed in the new SES code.
