### ISSUE TITLE
The remove trackers option from the settings menu always displays the warning

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#2234]
#### Build:
- Stage;

#### Affected Platforms:
- Across platform;

#### Browsers tested on:
- Firefox, Release version;
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Click on the Profile button in the top right corner of the site header;
3. Click on the Settings option;
4. Disable or enable the “Remove email trackers in all forwarded emails.” and click the “Save” button;
5. Disable and enable it back again;
6. Repeat steps 4 and 5 a few times and observe the behaviour;

#### Expected result:
- The warning message related to the option appears only when the user disables the option;

#### Actual result:
- The warning message related to the option is always displayed;

#### Notes:
- From what I see, this warning should work like the one from the “Privacy” option, meaning it is displayed only when the user turns off the option;
- See attached media:
![alwaysthere](https://user-images.githubusercontent.com/85748693/180408827-d30ccd60-ddd0-43d6-9e3c-413986c0c801.gif)

**Comment by Vinnl** [comment]
As mentioned elsewhere, this behaviour was intentional.
