### ISSUE TITLE
[Chrome] The “Currently removing email trackers” icon from the mask cards is of a different size on Chrome

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#2235]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;
- Android 11;

#### Browsers tested on:
- Chrome, Release version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;
- Have at least one mask created;
- Have the “Remove Email Trackers” option turned on;

#### Steps to reproduce:
1. Go to the Relay dashboard;
2. Observe the “Currently removing email trackers” icon from the mask cards;

#### Expected result:
- The icon is of an appropriate size;

#### Actual result:
- The icon is smaller than it should be;

#### Notes:
- See attached media:
Firefox for comparison:
![image](https://user-images.githubusercontent.com/85748693/180411958-8ed04d8f-63bc-471d-b280-e31cca5ec0f3.png)

Chrome:
![image](https://user-images.githubusercontent.com/85748693/180412077-b241a8ab-456b-4110-8295-495adfe73a0e.png)

**Comment by Bianca-O** [comment]
This issue is verified as fixed on stage under Windows 10 and Android 12, on Chrome and Firefox. The icon has the same size on both browsers.

![icon same size](https://user-images.githubusercontent.com/79697848/181786128-81494425-9095-421d-a138-e85db310f3bb.png)
