### ISSUE TITLE
[Website] the Private Relay dashboard website doesn't resize responsively when you shrink the window

### ISSUE THREAD

**Issue by dholbert** [mozilla/fx-private-relay#226]
STR:
 1. Log in to Private Relay
 2. Visit https://relay.firefox.com/accounts/profile/ (the "dashboard")
 3. Resize your window vertically, so that  your viewport is e.g. 600-700 CSS pixels tall

EXPECTED RESULTS:
The content should condense/recenter, or otherwise reasonably accommodate the smaller viewport height.

ACTUAL RESULTS:
- The footer gets cut off the bottom of the window (and a scrollbar appears so I could scroll to see it).
- The content doesn't condense or recenter, despite the fact that it's got a ton of blank space above and below the "Manage email aliases" section which is pushing stuff offscreen.

**Comment by dholbert** [comment]
screenshot (taken using Responsive Design Mode, with a 970px by 658px viewport):
![image](https://user-images.githubusercontent.com/426803/80422020-45732c00-8892-11ea-8833-f5eed480f33e.png)

**Comment by sandysage** [comment]
We'll need to triage all our mobile issues after the invite-only Beta. Let's consider how much mobile traffic we're expecting and prioritize accordingly.

**Comment by groovecoder** [comment]
Unable to reproduce, and the dashboard UI is completely re-done.

**Comment by dholbert** [comment]
I can still reproduce using the current production website, FWIW... @groovecoder is that unexpected? (Were you testing in a yet-to-be-released version?)

Here's a screenshot of me reproducing this today:
![screenshot-relay-space](https://user-images.githubusercontent.com/426803/85336812-278e0600-b494-11ea-85f1-106233ec7f23.png)
