### ISSUE TITLE
[Button] The private relay button breaks the login form at https://apply.sfcu.org/ (any email that I type in is considered invalid)

### ISSUE THREAD

**Issue by dholbert** [mozilla/fx-private-relay#228]
STR:
1. Visit https://apply.sfcu.org/
2. Type in an email address, e.g. "a@example.com"
3. Click "Submit"

EXPECTED RESULTS:
The page should simply prompt you to enter a password.

ACTUAL RESULTS:
The page **also** says "Please enter a valid email" and flags your email as invalid.

It looks like this has something to do with the Firefox Private Relay icon that's shown (or some other interaction with this addon), because if I disable the add-on, then I get EXPECTED RESULTS.

**Comment by dholbert** [comment]
(Similar to #229 )

**Comment by groovecoder** [comment]
This should be fixed in 1.3.1 of the add-on which was just submitted to AMO.
