### ISSUE TITLE
[Button] breaks sign up at doordash.com

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#229]
With the add-on enabled, I can't sign into doordash.com. I use my password manager to auto-fill the login, but when I click "Sign In" I get "Email is required"

**Comment by ksy36** [comment]
I get a similar error on mint.com (https://accounts.intuit.com/) when trying to sign in with existing credentials:

<img width="702" alt="Screen Shot 2020-05-01 at 12 23 12 PM" src="https://user-images.githubusercontent.com/1303908/80821862-8f685480-8ba7-11ea-84ec-3640a0107c5f.png">

**Comment by groovecoder** [comment]
This should be fixed in 1.3.1 of the add-on which was just submitted to AMO.

**Comment by groovecoder** [comment]
Re-opening until we make the button also work.

**Comment by groovecoder** [comment]
Renaming to breaks sign *UP* at doordash.com and moving to backlog.

**Comment by groovecoder** [comment]
Note: I did some testing and it seems like doordash may already be blocking relay.firefox.com addresses?
