### ISSUE TITLE
Consider a setting to destroy an address after X messages

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#23]

**Comment by pdehaan** [comment]
If we do this, it might be nice to make it optional. I can imagine cases where I want a burner email address that disappears after 1-2 emails. But I might also want to set up an alias for CrateAndBarrel or BedBathAndBeyond where I expect to be on email address list for years.

**Comment by rafalkrupinski** [comment]
Wouldn't it make providers more likely to block mozmail domain?

**Comment by EMMLynch** [comment]
Please reopen with additional details if this still be considered.
