### ISSUE TITLE
Extension breaks newsletter form entry on www.mozilla.org

### ISSUE THREAD

**Issue by alexgibson** [mozilla/fx-private-relay#230]
With the add-on enabled, both the styling and behavior of the newsletter forms on www.mozilla.org are affected:

STR:

1.) Visit https://www.mozilla.org/en-US/
2.) Scroll down to the newsletter section titled "Love the Web?"
3.) Click on the "Your email address" field to focus it.

Expacted results:

When the email field is focused, the newsletter form should expand to reveal some further options.

Actual results:

The form does not expand, resulting in an unsuccessful first attempt at signup after entering an address and clicking "Sign up now". Also notice how the form styling isn't quite right, with the email field overflowing the parent container.

![image](https://user-images.githubusercontent.com/400117/80497881-f2b57500-8962-11ea-88a8-0ea7b092341b.png)

**Comment by groovecoder** [comment]
Thanks for the bug report.

**Comment by groovecoder** [comment]
The functionality part should be fixed in 1.3.1 of the add-on which was just submitted to AMO. Leaving this open for the style issues.

**Comment by birdsarah** [comment]
I believe this is fixed as of Oct 26.

![Screenshot from 2020-10-26 12-29-55](https://user-images.githubusercontent.com/1796208/97206654-03666c80-1787-11eb-95c0-46d0dd6ba68f.png)
