### ISSUE TITLE
[Context Menu] Breaks email input field on figma.com

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#231]
STR:

1. Visit https://www.figma.com/file/rTeLZ1cmvHbgfJt91AloNi/DevTools-Network-Details-Pane-(V)?node-id=351%3A0
2. Click "Sign up with Email"
3. Right-click the email input field and choose "Generate Email Alias"
4. Click in password field and choose "Use a Securely Generated Password"
5. On the next panel, enter any name and choose any kind of work
6. Click "Create Account"

Expected Results:
Account should be created and redirected 

Actual Results:
The panel pops back to the email input field with an error: "Please provide your email"

**Comment by mnoorenberghe** [comment]
Currently the field is being filled with [`.value = …;` ](https://github.com/mozilla/fx-private-relay/blob/12b74aa8345fa9cca25876d10f025c6b797807be/extension/js/fill_relay_address.js#L4)which doesn't work well on sites that do their own field validation. In Firefox we do all autofill with a privileged API [`input.setUserInput("…")`](https://searchfox.org/mozilla-central/rev/2bfe3415fb3a2fba9b1c694bc0b376365e086927/dom/webidl/HTMLInputElement.webidl#205-209) that dispatches `input` events (and a `change` event if the field isn't focused). That API isn't currently exposed to extensions but it would be easy to do so with something like `[Func="Document::IsCallerChromeOrAddonOrUAWidget"]` (`Document::IsCallerChromeOrAddon` already exists).

**Comment by groovecoder** [comment]
Thanks for the insight @mnoorenberghe !

**Comment by groovecoder** [comment]
This should be fixed in 1.3.1 of the add-on which was just submitted to AMO.

**Comment by sv-hyacoub** [comment]
@groovecoder I still can reproduce this issue on MacOS 10.14 and on Windows 10 x64 on Firefox 76.0.1 using version 1.3.1 of the addon. The panel pops back to the email input field with an error: "Please provide your email".
