### ISSUE TITLE
Add explanation when populating a sign-up for with a relay address

### ISSUE THREAD

**Issue by hafta** [mozilla/fx-private-relay#234]
When a user clicks the new relay icon in an input field and we populate the field with the new relay address, we should popup some kind of notification telling the user "this new email address will forward mail to your address foo@bar.com" with a link to the dashboard. So it is more clear what's happening for users who aren't sure how this all works.

**Comment by sandysage** [comment]
Likely related to #260

**Comment by groovecoder** [comment]
The email input interface is much improved and changed in the 1.4.0 release.
