### ISSUE TITLE
After login: Giant envelop, no other information

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/fx-private-relay#239]
I tried logging in at relay.firefox.com and I only get the image of a giant envelop:

![image](https://user-images.githubusercontent.com/584352/80694133-bd349700-8adc-11ea-91da-1e613b64d2fc.png)

Scanning the html I see the message "Relay is currently invite only". I guess something is broken with the design which makes the experience bad.

Tested on Linux / Nightly from Greece. 

Thanks!

**Comment by jeroen7s** [comment]
selecting from top-left to bottom right on the page does show the info.

**Comment by groovecoder** [comment]
I think there's a bug for this already? Do you have some kind of ad/content blocker add-on installed?

**Comment by jeroen7s** [comment]
I disabled both uBlock Origin and Privacy badger, but the issue remains.

**Comment by benborra** [comment]
I'm also encountering the giant envelop after logging in.
I'm running Firefox 75.0 64-bit and have tried in safe mode.
My console states an error loading an analytics script: 

> Loading failed for the <script> with source “https://relay.firefox.com/static/js/analytics.js”. 

And my network connection states a 404 on loading the favicon.

**Comment by Niflhem** [comment]
`Loading failed for the <script> with source “https://relay.firefox.com/static/js/analytics.js”.`
This only happens with uBlock Origin or any other ad blocker for that matter.
 
After some research it seems to be an issue with Firefox itself. @glogiotatidis mentioned that he tested this on Nightly/Linux, I can also confirm that it doesn't work on Firefox 75.0 64bit Windows 10 as @benborra stated.

Where it does behave correctly is Chrome 81.0.4044.129  (presumably any other modern version) and on **Firefox Nightly 77.0a1**, again, both **Windows 10 64bit.**

![image](https://user-images.githubusercontent.com/44680063/80826122-f30f7380-8be1-11ea-8b8f-2dcad33517a3.png)

**Comment by edumorlom** [comment]
I experience the same issue from Firefox 76 Developer Beta.

**Comment by erasmas** [comment]
Same issue with Firefox 75 having uBlock Origin and Privacy Badger addons installed.

**Comment by edumorlom** [comment]
This seems to be fixed for me.

**Comment by glogiotatidis** [comment]
> This seems to be fixed for me.

Verified fixed for me too.

**Comment by sv-hyacoub** [comment]
Can't manage to reproduce the issue anymore, I tried on MacOS 10.15, Windows 10 x64 and on Ubunutu 18.04 on the latest Firefox Nightly, Firefox 77.0b5 and on Firefox 76.0.1.
