### ISSUE TITLE
Upgrade to Postgres v14

### ISSUE THREAD

**Issue by jbuck** [mozilla/fx-private-relay#2408]
While working on the incident today I noticed that Relay is using Postgres 11. This version is still supported, but I'm willing to bet there'd be some performance improvements you'd get for free by upgrading to Postgres {12,13,14}. GCP has [documentation on in-place upgrades](https://cloud.google.com/sql/docs/postgres/upgrade-major-db-version-inplace).

**Comment by jwhitlock** [comment]
The deployment environments have been updated as of May 2023 (details in MPP-2329). The last part (which maybe should have been the first part 😬) is to update the CircleCI environment.
