### ISSUE TITLE
The "copy-to-clipboard" button should have some visual feedback when hovered and/or clicked

### ISSUE THREAD

**Issue by dholbert** [mozilla/fx-private-relay#243]
STR:
1. Visit https://relay.firefox.com/accounts/profile/
2. Click the "copy-to-clipboard" button to the right of a virtual email address.

ACTUAL RESULTS:
Nothing visually happens, so it's not obvious that the email address was copied. (It was, but I can't tell for sure until I try pasting it somewhere.  There's no easy way for me to tell whether the icon click registered or if I mis-clicked just outside of the icon, for example.)

EXPECTED RESULTS:
There should be some visual feedback (the icon changing darkness, or say "Copied!", or something like that)

For comparison / prior art, github itself has a copy-to-clipboard button in its "Clone or download" section on e.g. https://github.com/mozilla/fx-private-relay/ , and that button changes darkness when it's hovered *and* when it's clicked, which helps me know that I targeted my click correctly and that I did indeed successfully copy the thing to the clipboard.

**Comment by sandysage** [comment]
While copying from the website is not expected to be a primary use case, this is good call out for providing clear affordance feedback. Marking as P2.
