### ISSUE TITLE
Website does not load images

### ISSUE THREAD

**Issue by EdorianDark** [mozilla/fx-private-relay#246]
For me https://relay.firefox.com/ looks broken:
![image](https://user-images.githubusercontent.com/5777938/80802178-eb82a700-8bae-11ea-8681-00ca94c5d3c5.png)

I am on Firefox Developer 76, linux in germany.
But other reported the same issue.

**Comment by Booteille** [comment]
Same issue on Firefox 75, Linux Pop!_Os 20.04.

Tried on safe mode too.

**Comment by groovecoder** [comment]
Howdy. You've found our website before we're quite done setting it up! We're still working on the image assets for the page. Closing this issue for now, but keep an eye on the site for updates!
