### ISSUE TITLE
website issues with longer translations

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/fx-private-relay#2508]
In German (and probably other languages as well), terms tend to be a bit longer than in English. This causes a few issues on the Relay website.

1. The hours field of the countdown on the homepage:

<img width="695" alt="Bildschirmfoto 2022-09-14 um 23 38 56" src="https://user-images.githubusercontent.com/1100614/190267463-c0900f53-7553-470f-8b30-b1ba91d680e6.png">

2. The sign in button in the header on the smartphone:

<img width="393" alt="Bildschirmfoto 2022-09-14 um 23 39 58" src="https://user-images.githubusercontent.com/1100614/190267598-b1bb61b7-4190-4719-8970-c02a31ccf306.png">

**Comment by Vinnl** [comment]
Thanks for reporting @cadeyrn!

@peiying2 Do you think we can abbreviate Stunden (to "Stund."?) above? The relevant string is `offer-countdown-timer-hours`. The second issue is a more general one with the Relay website that also occurs in other languages, so we'll need to look at that separately.

**Comment by peiying2** [comment]
> @peiying2 Do you think we can abbreviate Stunden (to "Stund."?) above? The relevant string is `offer-countdown-timer-hours`. The second issue is a more general one with the Relay website that also occurs in other languages, so we'll need to look at that separately.

The best way is to make it 3 letter space or 4 letter space, and make it explicit that it is a limited space so the translation adheres to it, rather than guessing where the word might be truncated. I think the days of the week is a good example, there are fields/strings for the full translation and there are fields for abbreviated versions - two or three letters depending on the space.

**Comment by Vinnl** [comment]
The countdown timer is no longer visible, and the logo no longer overlaps on small screens (though it's still a bit tight):

![image](https://user-images.githubusercontent.com/4251/204795660-dfbe76d4-7d50-42f6-934f-6d9909fcb1ba.png)

Thus, I'll close this issue. Thanks for reporting!

I'll also think about a way to have a version of the website with all strings *1.5 and with special characters.

**Comment by cadeyrn** [comment]
@Vinnl Thank you!

> and the logo no longer overlaps on small screens (though it's still a bit tight)

Maybe the left and right padding of the button can be reduced by a few pixels on small screens? Then you would save a few pixels that could be used as margin between the logo and the button instead. The current solutuion is better than before but I really think there should be a few pixels space between both elements.
