### ISSUE TITLE
use `decouple.Csv` for SUBSCRIPTIONS_WITH_* env vars

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#2515]
`settings.SUBSCRIPTIONS_WITH_PHONE` and `settings.SUBSCRIPTIONS_WITH_UNLIMITED` should use `decouple.Csv` so they are validated and turned into lists at Django setup.

_Originally posted by @jwhitlock in https://github.com/mozilla/fx-private-relay/pull/2431#discussion_r971312565_

**Comment by jwhitlock** [comment]
and `SUBSCRIPTIONS_WITH_VPN` - https://github.com/mozilla/fx-private-relay/pull/2505
