### ISSUE TITLE
Extension breaks new user registration on saatchiart.com

### ISSUE THREAD

**Issue by svoisen** [mozilla/fx-private-relay#256]
**STR:**
1. Visit https://www.saatchiart.com and click on the "Register" link in the header.
2. Fill out the form. You can either type in an existing e-mail or use the extension to populate a new Firefox Relay e-mail.
3. Notice that the placeholder text does not disappear on the e-mail field, and instead is overwritten by the input text.
4. Submit the form.

**Expected Results:**
The form submits without issue. The placeholder text for the e-mail field disappears on entering other text.

**Actual Results:**
The form returns a "Please enter a valid e-mail address" error, even though a valid e-mail is supplied. The e-mail field appears broken due to overlapping text.

Disabling the extension fixes the issue.

**Comment by groovecoder** [comment]
Fixed.
