### ISSUE TITLE
Make the popup page into a mobile responsive page

### ISSUE THREAD

**Issue by gabrielluong** [mozilla/fx-private-relay#258]
In our Firefox Mobile Platforms, the web extension popup is shown as a normal page in a new tab. To provide a better experience, we will need to make changes to `popup.html` to make it into a responsive page.

Before it is mobile responsive (current):

<img width="455" alt="Screen Shot 2020-05-03 at 9 59 58 AM" src="https://user-images.githubusercontent.com/1190888/80916148-f4958480-8d24-11ea-854c-e1df7b39a8bc.png">

**Comment by sandysage** [comment]
Let's revisit mobile responsiveness and usability in the invite-only Beta testing phase, and where this fits. Right now we're primarily focused on the desktop experience as our first learning ground.

Setting as a P3 to be revisited when we have the first candidate out.
