### ISSUE TITLE
Add "join the waitlist" from the extension

### ISSUE THREAD

**Issue by sandysage** [mozilla/fx-private-relay#265]
User story: When I get the extension, during this trial experimentation, I cannot use it, which is frustrating.

**Comment by groovecoder** [comment]
When https://github.com/mozilla/fx-private-relay/issues/271 is done, this should be an easy link from the add-on to the site, right?

**Comment by groovecoder** [comment]
Join the waitlist will be on the home page of the website, and the improved sign-up/in flow will get people there.
