### ISSUE TITLE
Improve the sign-in flow

### ISSUE THREAD

**Issue by sandysage** [mozilla/fx-private-relay#266]
User story: when I get the extension first, it's not immediately clear that I need to sign up/in to a Firefox Account for the service to work.

Let's allow someone to "sign in" from the extension by directing the user to the OAuth flow and land them to a signed in state of the dashboard

**Comment by paulens12** [comment]
When you try to sign in without having an invite, this error pops up:
Sorry, the Private Relay Beta is currently by invitation only. Please check again later.

The error seems fine, except it's written in black on black background. I think this could go together with "improving the flow"

**Comment by lesleyjanenorton** [comment]
Closing - the UI flows have changed and we're immediately messaging users when the install the addon
