### ISSUE TITLE
Survey banner close button doesn't work

### ISSUE THREAD

**Issue by dannycolin** [mozilla/fx-private-relay#2695]
AB:

When, I click on the close button of the survey banner nothing happens.

EB:

Clicking the close button should remove the survey banner.

Additional Information:

I tried in Troubleshoot Mode and the same behavior happens.

**Comment by joaonunomota** [comment]
Is it possible to get any more information to recreate the problem?

I've tried to reproduce this with all the different `reasonToShow` values on the CsatSurvey component to no success. All attempts (Firefox and Chrome) have resulted in:

![example](https://user-images.githubusercontent.com/16689477/232230741-aab12b98-b9cc-4a7b-b5b8-b4769b7b86b0.gif)

**Comment by dannycolin** [comment]
Is there a way to trigger the banner because it doesn't show anymore?

**Comment by joaonunomota** [comment]
@dannycolin You can get the banner to appear by deleting a cookie with a name like `csat-survey-premium-90days_{userid}_dismissed` and then refreshing the page.

**Comment by dannycolin** [comment]
Thanks for the tip. I wasn't able to reproduce the issue so it might have been fixed by a patch for another bug. I'll close this for now.
