### ISSUE TITLE
[l10n]: request to add locale 'pt-PT'

### ISSUE THREAD

**Issue by peiying2** [mozilla/fx-private-relay#2698]
Per community request, please add `pt-PT` to the supported locale list. I have already enabled the locale in Pontoon so the community can start translation.

**Comment by Vinnl** [comment]
As soon as they get added to the l10n repository, the website should automatically pick them up, so as far as I'm aware https://github.com/mozilla-l10n/fx-private-relay-l10n/pull/108 should be enough.
