### ISSUE TITLE
Ability to use an already created Relay address on a second domain

### ISSUE THREAD

**Issue by sandysage** [mozilla/fx-private-relay#270]
Depends on #268 

Some people may never want to generate more than 5 email addresses. This enhancement would allow someone to use a generated email for multiple accounts.

This may encourage bad habits and potentially open it up for someone to proxy their whole inbox (over time) to just 5 addresses. Need to consider how this fit with expected use.

**Comment by groovecoder** [comment]
Can already do this by copy-paste but we're not planning to design for this.
