### ISSUE TITLE
Mozilla fan and cybersecurity professional - would love to join the alpha test

### ISSUE THREAD

**Issue by memildin** [mozilla/fx-private-relay#274]

**Comment by memildin** [comment]
I've already posted enthusiastically on LinkedIn about the _concept_ of this new extension. Now I'd like to try the real thing. Given that I'm not running it yet, I'll have to share my REAL email address with you and not an alias :)

**Comment by groovecoder** [comment]
We're about to send an invite to our NDA mozilla community. We will also add a "Join the Waitlist" button to the site.

After that we'll gradually open up a beta to people on the wait-list.

**Comment by memildin** [comment]
Thanks, @groovecoder. Any updates?

**Comment by Uffje** [comment]
> Thanks, @groovecoder. Any updates?

There is a "Get on the waitlist with a Firefox account"-button, I pressed it, but I think the message afterwards is not very clear and you can reapply, so I am not sure if it works properly. I read the subtext as part of the title, but I think it is more like a heads up. Maybe some thing to improve.

**Comment by memildin** [comment]
#please-close
