### ISSUE TITLE
Can't delete alias when adblocker is enabled

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/fx-private-relay#278]
If Ublock Origin is running in a browser on the Relay profile page, the delete alias button does not fire all its events and the modal does not disappear. It may be blocked by some missing analytics functionality: `sendGaPing is not defined`. See attached screenshot.

![relaybug](https://user-images.githubusercontent.com/94519/81191851-babbbc80-8f76-11ea-8cad-e7f0e6fd760c.jpg)

**Comment by brassy-** [comment]
I can confirm that with uBlockOrigin enabled I wasn't able to delete my alias too. Disabling the extension fixed the problem.

**Comment by groovecoder** [comment]
This fix has been deployed to the production site now. Should be working for you. Please try again?

**Comment by sv-hyacoub** [comment]
I couldn't reproduce this bug on MacOS 10.15, Windows 10 x64 and on Ubunutu 18.04 on Firefox Release 76.0.1.
