### ISSUE TITLE
If user don't have a invite, error text is black on black background

### ISSUE THREAD

**Issue by Eliotnand** [mozilla/fx-private-relay#283]
When you try to sign up on [https://relay.firefox.com/](https://relay.firefox.com/) without invite, error text is black.
![Screenshot from 2020-05-07 15-30-17](https://user-images.githubusercontent.com/44431797/81278593-b62afd00-9077-11ea-9215-9252f268e5dc.png)

**Comment by groovecoder** [comment]
I thought this was fixed with https://github.com/mozilla/fx-private-relay/pull/280? Which we deployed yesterday.

**Comment by lesleyjanenorton** [comment]
I can no longer reproduce this issue so I am going to close. #280 should have fixed this but please feel free to reopen of course if you're still seeing this.
