### ISSUE TITLE
"Create New Relay Alias" button has no hover state

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/fx-private-relay#296]
The "Create New Relay Alias" button doesn't have any hover state, neither visual indication on the button styling nor a pointer cursor when hovering over it. Adding at least `cursor: pointer` would help a lot.

**Comment by sv-hyacoub** [comment]
@groovecoder should the hover state be displayed on "Create Account" button also when the user is not logged into his account?
![Screenshot 2020-05-13 at 16 52 07](https://user-images.githubusercontent.com/15101135/81821252-52eb1000-953a-11ea-9901-590dae20fdae.png)
