### ISSUE TITLE
Images don’t show in Firefox nor Safari 

### ISSUE THREAD

**Issue by alex-mayorga** [mozilla/fx-private-relay#297]
![DFF2B347-3F85-46C3-865B-2A8D20347825](https://user-images.githubusercontent.com/649262/81476230-56973380-91d6-11ea-9fec-3b3fcc10fcf9.png)

**Comment by MilindaLaknath** [comment]
Same issue here for Firefox 76.0 for Manjaro Linux distribution.
![Screenshot from 2020-05-11 12-21-35](https://user-images.githubusercontent.com/6555234/81532508-1eccef00-9382-11ea-9d60-b9220177db62.png)

**Comment by groovecoder** [comment]
Hi. Thanks for the feedback. The site is still alpha and we don't actually have the images yet! But we'll get some up soon.
