### ISSUE TITLE
Account details pop-up goes under 'Create New Realy Alias' 

### ISSUE THREAD

**Issue by mMARUF** [mozilla/fx-private-relay#305]
### Steps to Reproduce:

1. Go to https://relay.firefox.com/
2. Login with your email
3. Shrink your Firefox window to a smaller size from full monitor fit window
4. Now, click on your profile picture 

**Actual Results**
Account details pop-up goes under **'Create New Realy Alias'**  button. And, also the elements of Account details pop-up starts blinking( ex- sign out button )

**Expected Results**
There should not such interactions between the **'Create New Realy Alias'**  button and Account details pop-up and also the elements of Account details pop-up should not blink

**Comment by mMARUF** [comment]
![Account details pop-up goes under 'Create New Realy Alias' ](https://user-images.githubusercontent.com/45368054/81810029-0efd0880-9544-11ea-9469-22c7245471d6.gif)

**Comment by groovecoder** [comment]
Fixed.
