### ISSUE TITLE
Received emails does not have "Relay Alias" info

### ISSUE THREAD

**Issue by mMARUF** [mozilla/fx-private-relay#306]
### **Steps to Reproduce;**

1. Create an alias from Firefox Relay
2. Create a Twitter account using that alias (enable the Forward emails to ******* -> option)
3. Now, after creating a account, you will receive a verification code into your actual email account to which the mail has been forwarded)

**Actual Results**
It can be observed that there is no information about the alias has been used to create this account. 

**Expected Results**
We have upto 5 free alias support. So, it is vital to provide the information that which alias has been used to sign up to a particular service

![Alias Email address not mentioned](https://user-images.githubusercontent.com/45368054/81811174-060d3680-9546-11ea-8111-e9783d00051a.PNG)

**Comment by lesleyjanenorton** [comment]
Thanks for filing - great point.

**Comment by groovecoder** [comment]
This has been fixed.
