### ISSUE TITLE
Search icon is *tiny* on FF iOS

### ISSUE THREAD

**Issue by birdsarah** [mozilla/fx-private-relay#3080]
See screen shot below.

I'm on iPhone 12, iOS 16, FF 109.

<img src="https://user-images.githubusercontent.com/1796208/217707446-c859fb6a-77b9-44a7-81cc-4c9c0ea854de.jpeg" width="300px">

**Comment by Vinnl** [comment]
Will copy over to the first report at https://github.com/mozilla/fx-private-relay/issues/1919
