### ISSUE TITLE
"Search & filter mask" function not visible on iPhones

### ISSUE THREAD

**Issue by magsmoz** [mozilla/fx-private-relay#3128]
**Description**
User is reporting that the search function is not visible in their Relay dashboard on iPhone (see screenshot)
We have tested this on 2 more iPhones and it is the same. Issue persists in Firefox, as well as Chrome and Safari
This is not an iOS issue, as we have tested this on an iPad Air 2 and the search function is there. So it seems exclusive to iPhones.

**Steps to Reproduce**
1. Go to Relay on the Firefox browser/Safari/Chrome
2. Scroll down to where the search function should be
4. Unable to locate the "magnifying glass" to search masks where it should be

**Expected Results**
The search and filter function should be visible above the email masks in the dashboard
![image](https://user-images.githubusercontent.com/92737666/221115994-cf516eba-c515-4b16-95ff-5d72a460f08d.png)

**Comment by Vinnl** [comment]
Will copy over to the first report at https://github.com/mozilla/fx-private-relay/issues/1919
