### ISSUE TITLE
[Website] The alias Delete doorhanger is not dismissed upon clicking out of it or on any other page element that does not refresh the page

### ISSUE THREAD

**Issue by TimeaC** [mozilla/fx-private-relay#321]
**Affected Version**
Release Version 76.0.1 (64-bit)
Private Relay Add-on version 1.4.0

**Tested on**
Windows 10 x64

**Steps to reproduce:**

1. Launch latest Firefox Release
2. Go to the Private Relay website and sign in
3. Generate 2 or more aliases
4. Click on the Delete button for all of them
5. Click anywhere on the page

**Expected:**
The delete doorhanger should be dismissed upon clicking out of it or on any other element from the page.

**Actual:**
The delete doorhangers will remain displayed unless the user cancels or confirms deleting the aliases. Video: https://streamable.com/3o4mwq

**Comment by LaurentiuApahideanSV** [comment]
The issue also occurs on Android. Tested on Firefox 68.8.1, Firefox Preview Nightly 200520 and Chrome 83.0.4103.60 using a OnePlus 6T (Android 9).

**Comment by sbadau** [comment]
This issue is also reproducible on Mac OS X 10.15 and Ubuntu 18.04 - on Firefox 76.0.1 and Private Relay add-on 1.4.

**Comment by groovecoder** [comment]
Should be fixed now.
