### ISSUE TITLE
Ensure that there is no white space underneath the footer for shorter pages

### ISSUE THREAD

**Issue by codemist** [mozilla/fx-private-relay#3223]
![Screenshot from 2023-03-24 11-25-32](https://user-images.githubusercontent.com/4251/227496893-66c96249-943a-4880-ac95-86732b09edbf.png)

The fix for this was removed in https://github.com/mozilla/fx-private-relay/pull/3222, to fix [MPP-2920](https://mozilla-hub.atlassian.net/browse/MPP-2920), so make sure that doesn't regress when fixing this bug.

[MPP-2920]: https://mozilla-hub.atlassian.net/browse/MPP-2920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jwhitlock** [comment]
Leaving open until someone with an Android 12 / 13 browser checks that MPP-2920 did not regress:

With Android 12 or 13, on the Relay dashboard, change a Relay mask status (such as block promotional or block all). Changing this setting breaks the entire page (most of the page is now whitespace).

Uploading 20230310_104241.mp4…

**Comment by Vinnl** [comment]
Verified on Mulch browser (Chromium-based) on Android 11 that MPP-2920 did not regress, which seems safe enough to me to close this issue.

I did ran into https://github.com/mozilla/fx-private-relay/pull/3714, which seems pretty serious as well, and also affects Firefox.
