### ISSUE TITLE
Generated alias mail is cleared out of field after focusing out of it on some sites

### ISSUE THREAD

**Issue by TimeaC** [mozilla/fx-private-relay#331]
**Affected Version**
Release Version 76.0.1 (64-bit)
Private Relay Add-on version 1.4.0

**Tested on**
Windows 10 x64
MacOS 10.15
Ubuntu 18.04

**Affected sites:**
1. Netflix.com
2. Instagram.com
3. Twitch.tv
4. CNN.com
5. NYTimes.com
6. Zillow.com
7. Pinterest.com

**Steps to reproduce:**

1. Launch latest Firefox Release
2. Install Private Relay add-on and log in
3. Go to netflix.com or other sites from the list
4. Generate an alias for the sign-up field (via button or context menu)
5. Click on the "Try it now" button [Netflix]
 or 
5.1 Focus out of the field 

**Expected:**
The field should remain filled and the sign-up process should continue.

**Actual:**
[Netflix]
5. "E-mail requred" validation error appears (given the field was cleared upon clicking on the "Try it now" button)
5.1 The field was cleared upon focusing out of it. 
Video 1: https://streamable.com/9urlet [Netflix]
Video 2: https://streamable.com/60mz3g [Instagram]

**Note:**
1. Selecting the generated e-mail from the autofill history dropdwon will fill it correctly and let it go further in the register process. [Netflix]

**Comment by groovecoder** [comment]
We don't think we can accurately detect all the possible ways that an email might be removed from input elements.

So, instead of trying to fix all of these, we should implement #263 so that it's easy for the user to get the email address back into the field.

**Comment by sv-hyacoub** [comment]
The same issue is reproduced on "indeed.com" when you generate an alias from the context menu or button and move the focus back and forth from the password field to the email address field, the email address is cleared out.
