### ISSUE TITLE
Private Relay addon zooms in some sites on page load

### ISSUE THREAD

**Issue by TimeaC** [mozilla/fx-private-relay#333]
**Affected Version**
Release Version 76.0.1 (64-bit)
Private Relay Add-on version 1.4.0

**Tested on**
Windows 10 x64
MacOS 10.15
Ubuntu 18.04

**Affected sites:**
1. Twitch.tv
2. Wikipedia
3. MyShopify - Loged In
4. StackOverflow
5. LinkedIn - breaks page

**Steps to reproduce:**

1. Launch latest Firefox Release
2. Install Private Relay add-on and log in
3. Go to the affected sites

**Expected:**
The sites should be displayed with normal/default zoom lvl

**Actual:**
The loaded pages are zoomed in - firefox also detects this as default zoom lvl
Video: https://streamable.com/8on9gx
Video2: https://streamable.com/6dkpd4
![2020-05-22_15h09_50](https://user-images.githubusercontent.com/65650857/82666434-992d2700-9c3e-11ea-9492-3f57870f2520.png)

**Note:**
Uninstalling the add-on displays the page with the correct/default zoom level.

**Comment by sv-hyacoub** [comment]
Verified as fixed on Firefox 77.0.1 using Firefox Relay Beta addon version 1.4.1 on Windows 10, Mac OS X 10.14 and on Ubuntu 18.04.
