### ISSUE TITLE
[Website] The newly created aliases are placed randomly on the Private Relay website

### ISSUE THREAD

**Issue by sbadau** [mozilla/fx-private-relay#334]
**Affected versions**
- Nightly 76.0.1
                                                                                                                                                                                     
**Affected platforms**
- Windows 10 and 7 x64
- Mac OS X 10.14
- Ubuntu 18.04 

**Steps to reproduce**
1. Launch the latest Nightly
2. Navigate to https://relay.firefox.com/ and sign in 
3. Create new email aliases using the "Create New Relay Alias" button

**Expected behavior**
The email alias that is just created should be placed in the same position, following a certain pattern (first in the list or last)

**Actual behavior**
The aliases that are created are not placed in a certain order (sometimes at the beginning of the list, other times in the end) making it hard to know which alias is the newest.

**Comment by say-yawn** [comment]
Was this fixed @groovecoder ? From https://github.com/mozilla/fx-private-relay/pull/465 and https://github.com/mozilla/fx-private-relay/pull/552

**Comment by groovecoder** [comment]
This should be fixed now.
