### ISSUE TITLE
Inconsistent scrolling across browsers and screen sizes

### ISSUE THREAD

**Issue by joaonunomota** [mozilla/fx-private-relay#3406]
The position of the banner and header when scrolling changes across different screen sizes as shown by the examples below. The scrolling in Chrome is also worse due to multiple scroll bars. This might be related to #3079.

I think the intended result would be to have the banner disapear from view when scrolling, while the header remains in view at the top of the screen.

Chrome:

![bad-chrome-scroll](https://github.com/mozilla/fx-private-relay/assets/16689477/07043ce1-0be0-4098-b942-cfb8a06560b2)

Firefox:

![bad-firefox-scroll](https://github.com/mozilla/fx-private-relay/assets/16689477/9ed2d313-6eca-4fb6-a782-5528fb6e208c)

**Comment by joaonunomota** [comment]
I have found a solution that I think handles this issue, #3223, and #3407. The fix does do quite a few changes on CSS and the position of the mobile menu, so I'm checking if this is an acceptable solution here first and that this won't cause any known issues.

The fix does these changes:
- Add `height: 100%` to `#__next`, `#overlayProvider`, `body`, and `html` without a media query
- Add `display: flex` and `flex-direction: column` to `#overlayProvider`
- Replace `height: 100%` with `flex: 1 0` on `.wrapper` in `Layout.module.scss`
- Wrap `PlainPageHeader` in a `div`
- Move `position: sticky`, `left: 0`, `top: 0`, and `z-index: 1` from `PlainPageHeader` to the `div`
- Add `z-index: 2` to `PlainPageHeader`
- Move `MobileNavigation` into the `div` below `PlainPageHeader` and replace `position: sticky` with `position: relative`
- Remove `overflow: auto` from `.non-header-wrapper` in `Layout.module.scss`

Here are examples of the website working without the issues mentioned, I delete some elements at the end to show the footer staying at the bottom of the screen:

![good-firefox](https://github.com/mozilla/fx-private-relay/assets/16689477/aef94525-e14e-4c88-a70a-cb44800c8338)

![good-chrom](https://github.com/mozilla/fx-private-relay/assets/16689477/a2073b5b-9b1a-48b2-9103-c40465b3f90e)

**Comment by Vinnl** [comment]
@joaonunomota Hmm, it's a bit hard for me to judge the impact of those changes from just a listing of those. It sounds like you've already made the changes somewhere, is that on a branch that's pushed somewhere? I'd love to check it out to see the changes in context and test for a bunch of edge cases.

**Comment by joaonunomota** [comment]
@Vinnl It's half on some reproduction code and half manually editing the production website on devtools. I'll put it together on a branch when I get the chance!

**Comment by Vinnl** [comment]
I ran `git bisect` to track down the source of the multiple scrollbars, which was a947289d241e5dfb6e482394b2cc8e39b4d71fc3. Turns out it was an incomplete revert that caused it. However, the reason we removed it in the first place was because we appear to be running into a Chrome bug, and we still haven't found a way to deal with that. So https://github.com/mozilla/fx-private-relay/pull/3425 should solve the immediate issue of multiple scrollbars, and I included a bunch of pointers there to more background, but will leave this open, as it will still be interesting to try the above fixes and see if it can resolve not just these, but the other issues as well.

**Comment by joaonunomota** [comment]
That's great that most of the issues are solved! I got all the changes onto a branch and I didn't spot anything wrong on Windows (Chrome / Firefox) or iOS (Safari). I only checked on the Email Masks and FAQ page, so there may need to be more changes for compatibility with other pages.

**Comment by joaonunomota** [comment]
@Vinnl I finally got around to checking the entire website (including the tracker report) and I'm happy to say that everything looks good across devices! Hope the pull request is still useful after all this time :)

**Comment by Vinnl** [comment]
Sorry about leaving this in limbo for so long (I got moved onto the Monitor project, so was juggling some balls), but congrats on getting this in!
