### ISSUE TITLE
[Addon] The UI of some search engines is broken when the add-on is installed

### ISSUE THREAD

**Issue by sbadau** [mozilla/fx-private-relay#343]
**Affected versions**
Firefox 76.0.1
Private Relay add-on version 1.4.0 

**Affected platforms**
Windows 10
Mac OS X 10.14
Ubuntu 18.04

**Steps to reproduce**:
1. Launch Firefox.
2. Install the Private Relay add-on
3. Navigate to Google.com and perform a search
4. Observe the page

**Expected behavior**
Google.com is properly displayed.

**Actual behavior**
Google logo is gone, and the "All" and "Videos" tabs are affected.

Reproduced this issue on the following websites: 
https://www.google.com/
https://ro.search.yahoo.com/

Please see the screencast for more details: 
![search](https://user-images.githubusercontent.com/56026823/82669576-5e2df200-9c44-11ea-945e-3e914b49cf4a.gif)

**Comment by sbadau** [comment]
@lesleyjanenorton I can confirm that the issue is no longer reproducible on Firefox 78.0.2 and Private Relay add-on on Mac OS X 10.15, Ubuntu 18.04 x64 and Windows 10 x64. Both Google and Yahoo search pages are properly displayed.

**Comment by groovecoder** [comment]
Has been fixed.
