### ISSUE TITLE
Reply does not work

### ISSUE THREAD

**Issue by NilsIrl** [mozilla/fx-private-relay#3523]
I have been a Firefox relay subscriber since it was first released and replies have never worked. On the relay dashboard the number of replies does show up but the recipient never receives the email.

**Comment by jwhitlock** [comment]
@NilsIrl I'm sorry to hear that. Please contact customer support at https://support.mozilla.org/en-US/questions/new/relay, so that they can get the private details they need to debug your issue.

**Comment by EMMLynch** [comment]
Support contact provided. Closing this issue.
