### ISSUE TITLE
[Website] The contrast for the keyboard navigation is not strong enough

### ISSUE THREAD

**Issue by obotisan** [mozilla/fx-private-relay#353]
**Affected versions**
- Firefox 76.0.1
- Private Relay add-on version 1.4.0

**Affected platforms**
- Mac OS X 10.14
- Windows 10 x64
- Ubuntu 118.04 x64

Steps to reproduce:
1. Launch Firefox.
2. Go to Private Relay Website and log in.
3. Navigate the page using the keyboard. 

**Expected behavior**
- The page is easily navigated. 

**Actual behavior**
- It's hard to see were you are on the page. The contrast is not strong enough, especially when you are on the card.

**Comment by sbadau** [comment]
On Windows 10, the contrast is very weak also on mouse hover. Please see the Delete button and the Delete checkbox.

**Comment by sbadau** [comment]
I verified on https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ and the only issue with the contrast for key navigation and mouse hover is now on the Delete button. Please see the screencast:

![contrast](https://user-images.githubusercontent.com/56026823/84916796-31e08680-b0c7-11ea-90ed-704343033cec.gif)
