### ISSUE TITLE
[Addon]While creating an account in Private Window, an error is displayed

### ISSUE THREAD

**Issue by obotisan** [mozilla/fx-private-relay#354]
**Affected versions**
- Firefox 76.0.1
- Private Relay add-on version 1.4.0

**Affected platforms**
- Mac OS X 10.14
- Windows 10 x64
- Ubuntu 118.04 x64

**Preconditions**
- Private Relay add-on is installed.
- Firefox private relay account is needed.

**Steps to reproduce:**
1. Launch Firefox in Private Window.
2. Go to twitter.com and click on Sign up.
3. Use the add-on to Create New Relay Alias and paste the email in the corresponding field. 
4. Go through with the sign up process. 

**Expected behavior**
- Everything goes smoothly. 

**Actual behavior**
- After the process is finished an error is displayed, even though the account is created. 

![error, even though account created](https://user-images.githubusercontent.com/42799381/82818007-ae0bf380-9ea6-11ea-9d30-3cf3c5ffe182.gif)

**Comment by groovecoder** [comment]
Thanks for digging this far into it. This looks like an issue un-related to Relay. The alias was generated and even received the verification code.
