### ISSUE TITLE
[Website][iOS][Mobile] The email address is not copied into the clipboard

### ISSUE THREAD

**Issue by LaurentiuApahideanSV** [mozilla/fx-private-relay#355]
## Steps to reproduce
1. Go to https://relay.firefox.com/ and login using mozilla credentials;
2. Click on the "Click to Copy" from an existing alias;
3. Perform a "Paste" action in an appropriate field (for example Notes).
### Expected behavior
The copied addressed is pasted.
### Actual behavior
The copied addressed is not pasted.
### Device information
Affected browsers: Safari 13, Firefox for iOS 25.1
Device: iPhone 11 Pro (iOS 13.3)

**Comment by LaurentiuApahideanSV** [comment]
The issue is fixed for the https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/ website, however it still occurs on the https://relay.firefox.com/ website.
### Device information:
- Affected browsers: Firefox for iOS 28
- Device: iPhone 11 Pro (iOS 13.3)

**Comment by joaonunomota** [comment]
This is currently working on https://relay.firefox.com/


https://user-images.githubusercontent.com/16689477/236211270-832ac6ce-78a2-4cc1-b4b8-2dc64efa8586.mp4
