### ISSUE TITLE
Consider generating an email address when a phone number is requested

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#36]
Some people may want to create a temporary email address on their phones too. When they text a duration to the relay number, could we make them an email address too?

This could give a quick mobile UX for anonymous email generation.

We would need to require people to sign up with FXA first, and provide us their phone number so we can associate the generated email address with the right FXA, using the receiving phone number as the link.

**Comment by EMMLynch** [comment]
Closing since this is not being considered at this time
