### ISSUE TITLE
Refactor sns-inbound to use basic auth

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#363]
The [code to receive and process SNS messages](https://github.com/mozilla/fx-private-relay/pull/312) includes some custom code (roll your own crypto?!) to verify the SNS message signature. This brought in a number of dependencies and some lower-level code we might rather not have.

Instead, we could use HTTPS basic auth to authenticate HTTP POSTs are coming from the real SNS.

**Comment by EMMLynch** [comment]
Please reopen is this is still needed.
