### ISSUE TITLE
Refactor and clean SES code

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#364]
# About this Issue
After SES code was meged in PR #312 and tested, we should refactor code to make email handling using SES more robust. This issue tracks some refactoring needed.

# Acceptance Criteria
- [x] `sns_inbound` should call a separate function `validate_sns_header(topic_arn, message_type)` that validates the sns headers in [these lines](https://github.com/mozilla/fx-private-relay/blob/master/emails/views.py#L129-L164) of code.
- [ ] `_sns_inbound_logic` should have a default return like:
```
        return _sns_notification(json_body)
    logger.error(
        'SNS message type did not fall under the SNS inbound logic',
        extra={'message_type': message_type}
    )
    return HttpResponse('Received SNS message with type not handled in inbound log', status=400)
```

# 
Related to #312

**Comment by EMMLynch** [comment]
Please reopen if this is still needed.
