### ISSUE TITLE
Generate new alias button doesn't match the size of the input

### ISSUE THREAD

**Issue by valenting** [mozilla/fx-private-relay#366]
Firefox 78.0a1 (2020-05-27) (64-bit) - POP! OS Linux 20.04

https://mythirdbrain.substack.com/p/what-psychedelics-teach-us-about

![Screenshot_2020-05-29 Mysterious Drugs that (Re)train Your Mind](https://user-images.githubusercontent.com/1454649/83266175-c63f8380-a1c2-11ea-97a2-790fe827c281.png)

**Comment by birdsarah** [comment]
Fixed as of v1.4.5, Oct 26, FF81, Linux

![Screenshot from 2020-10-26 12-41-51](https://user-images.githubusercontent.com/1796208/97208003-a2d82f00-1788-11eb-877c-300a4d7ecce1.png)
