### ISSUE TITLE
Create new DB user for app with minimal permissions

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#368]
https://stackoverflow.com/questions/42050025/django-postgresql-creating-a-database-what-privileges-to-grant seems to have a rough way to approach this.

When we have the list of `GRANT`s we should hand that to Ops to create the user for stage + prod.

**Comment by groovecoder** [comment]
This is turning into a rabbit-hole, so we may not finish this before beta. But the references I'm using ...

https://www.postgresql.org/docs/current/sql-revoke.html
https://www.postgresql.org/docs/current/sql-alterdefaultprivileges.html

**Comment by EMMLynch** [comment]
Please reopen if this is still needed.
