### ISSUE TITLE
Email HTML broken on Dev

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#371]
# About this Issue
After merging #312 the emails being delivered shows broken HTML on dev.
Before:
<img width="1606" alt="socketlab" src="https://user-images.githubusercontent.com/25109943/83455079-e40b2380-a422-11ea-9b01-6938e4b384b3.png">

After:
<img width="1587" alt="ses" src="https://user-images.githubusercontent.com/25109943/83455088-e7061400-a422-11ea-8d6c-8fe807146cd2.png">

The email delivered from SES also do not have the header that indicates that the email was delivered via Private Relay.

**Comment by groovecoder** [comment]
Do you mind sharing the "View Original" email contents? It should show us what the relevant email headers were. (e.g., `Content-Type` with charset, and/or `Content-Transfer-Encoding` could cause this.)

**Comment by groovecoder** [comment]
Fixed in #373.
