### ISSUE TITLE
Email header not shown on dev

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#375]
# About this Issue
Latest changes removed the email header.
Before the SES with headers:
<img width="1146" alt="Screen Shot 2020-06-03 at 1 28 59 PM" src="https://user-images.githubusercontent.com/25109943/83681670-578a6d80-a5a8-11ea-824d-30f509005368.png">

After the SES without headers:
<img width="1147" alt="Screen Shot 2020-06-03 at 2 41 00 PM" src="https://user-images.githubusercontent.com/25109943/83681625-49d4e800-a5a8-11ea-9307-70efe572126f.png">

#
Related to issue #371

**Comment by groovecoder** [comment]
This should be a pretty simple fix to add this kind of "email wrapping" code like we do on the SocketLabs view.
```python
      wrapped_html = render_to_string('emails/wrapped_email.html', {
          'original_html': html,
          'email_to': email_to,
          'display_email': display_email,
          'SITE_ORIGIN': settings.SITE_ORIGIN,
      })
```

While we're in there, we should also "wrap" the From value too ...

```python
      relay_from_address, relay_from_display = _generate_relay_From(from_address)
```

Though I'm not sure if that value will work the same for SES as it does for SocketLabs.
