### ISSUE TITLE
Accepting an invitation failed on first try

### ISSUE THREAD

**Issue by nukeador** [mozilla/fx-private-relay#376]
When accepting the invitation to Relay for the first time I clicked Sign-in and then logged with my Firefox Account.

I got
`
Error retrieving access token: b'{"code":400,"errno":105,"error":"Bad Request","message":"Unknown code","info":"https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#errors","requestCode":"2e2035a280fb014737b84263ccb0e3b4417ddcfca2ecea17064155c05404b3c0"}'`

Then I tried again later and I worked. I'm not sure if I did this in a different Firefox container.

**Comment by groovecoder** [comment]
Do you have multiple Firefox Accounts by any chance?

**Comment by nukeador** [comment]
Nope, I tested with my personal one, but first time I was asked to enter user/pwd and didn't work, the second one the account was already logged in and worked.

**Comment by groovecoder** [comment]
Invitation mechanism will be removed tomorrow, so this will go away with next release.
