### ISSUE TITLE
Option to hide Relay icon from form fields

### ISSUE THREAD

**Issue by sambody** [mozilla/fx-private-relay#3802]
Please add an option in the extension to hide the Relay icon from form fields (on desktop). 

I use the Relay function only occasionally, and the right-click menu option is enough. I don't want the icon to clutter form fields. 

Thanks,

**Comment by Vinnl** [comment]
Hi @sambody, that option is already there: https://support.mozilla.org/en-US/kb/how-enable-disable-firefox-relay-icon-on-online-fields-and-websites

Feel free to re-open or add another comment if you have further questions.
