### ISSUE TITLE
The names column dissapears on its own

### ISSUE THREAD

**Issue by bighugedev** [mozilla/fx-private-relay#3841]
When I open this URL — **https://relay.firefox.com/accounts/profile/**, there are two columns: one with custom names that I have specified, and the other with emails. The problem is that sometimes the column with custom names doesn't appear at all.

So I tried to do the following thing: I disabled all my adblockers, tracker blockers and restarted my browser. Then I tried going to the URL mentioned above, and I did see the names column. Then I tried refreshing the page (pressing F5), and the column disappeared. Then I tried refreshing the page again, and the column was, again, back. Although on the next page reloadings it would never show up.

This seems to be a bug not related to my personal settings.
![with_names](https://github.com/mozilla/fx-private-relay/assets/86791298/83788f7f-c484-4707-9b91-ca2a219c80b9)
![without_names](https://github.com/mozilla/fx-private-relay/assets/86791298/f93e65aa-73d0-4b3f-a97c-c3df6d201af3)

**Comment by Vinnl** [comment]
Some related info you could share is whether you've got the "Enable account names for email masks" checkbox enabled in [the Relay settings](https://relay.firefox.com/accounts/settings/). If not, then the labels are provided by [the Relay extension](https://addons.mozilla.org/firefox/addon/private-relay) and something might be going wrong there (and you might be able to solve the issue by enabling that checkbox).

![image](https://github.com/mozilla/fx-private-relay/assets/4251/63404fe1-d038-4d6d-b381-2e22564f618e)

**Comment by bighugedev** [comment]
Thanks. Yeah, it helped.
