### ISSUE TITLE
[QUESTION] API For Firefox Relay Premium?

### ISSUE THREAD

**Issue by ARHAEEM** [mozilla/fx-private-relay#3868]
Hello, if I subscribe to [Firefox Relay Premium](https://accounts.firefox.com/subscriptions/products/prod_MIex7Q079igFZJ?plan=price_1LwoSDJNcmPzuWtR6wPJZeoh), will I have the ability to use it with APIs like n8n.io or zapier.com?

![image](https://github.com/mozilla/fx-private-relay/assets/63544079/9b346755-04bd-4259-a3aa-54d208f8c92c)

Thanks in advance.

**Comment by jwhitlock** [comment]
I'm not familiar with https://n8n.io/ or https://zapier.com/. Currently, you should have the same functionality with the free and premium accounts with those services.

Can you describe a workflow that you'd like to automate with Relay?

**Comment by jwhitlock** [comment]
Feel free to re-open when you have more information about how you would like to use Relay with these services.
