### ISSUE TITLE
emails: Consider switching from SendGrid to Mailgun?

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#39]
[SendGrid's Inbound Parse API](https://sendgrid.com/docs/API_Reference/Parse_Webhook/inbound_email.html) seems very basic. 😢 

[Mailgun's API for receiving, forwarding, and storing messages](https://documentation.mailgun.com/en/latest/user_manual.html#receiving-forwarding-and-storing-messages) seems much richer.

**Comment by maxxcrawford** [comment]
I love Mailgun. Is the pricing comparative?

**Comment by groovecoder** [comment]
We're using SocketLabs instead of SendGrid.
