### ISSUE TITLE
[Website] Emails aren't forwarded to your email address

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#390]
### Affected versions

Nightly 77.0a1
Private Relay add-on latest version

### Affected platforms

Windows 10 x64
Mac OS X 10.15
Ubuntu 18.04

### Steps to reproduce

1. Launch the latest Firefox
2. Install the Private Relay add-on and sign in
3. Create new relay alias
4. Navigate to any website with a sign-up form to create a new account using the new created alias (eg: amazon, reddit)
5. An email should be sent to verify you email address

### Expected behavior
Emails should be forwarded to your email address

### Actual behavior
Emails aren't forwarded to your email address
Forwarded emails should be displayed on private relay website

### Note
Blocked emails are displayed on private relay website
![Screenshot 2020-06-09 at 14 29 10](https://user-images.githubusercontent.com/15101135/84142543-a418f180-aa5d-11ea-81e0-0181dab52466.png)

**Comment by groovecoder** [comment]
The PR didn't fix reddit emails. :(
