### ISSUE TITLE
[Website] Labels with errors are saved

### ISSUE THREAD

**Issue by sbadau** [mozilla/fx-private-relay#393]
**Affected versions**
Firefox 77.0.1

**Affected platforms**
Windows 10
Mac OS X 10.14
Ubuntu 18.04

**Steps to reproduce**:
1. Launch Firefox.
2. Install the Private Relay add-on
3. Navigate and sign into https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/
4. Create at least one alias.
5. Click on "Add alias label", type "}" and click outside the field.
6. Refresh the website.

**Expected behavior**
An error that "}" can't be used is received and the label should not be saved.

**Actual behavior**
An error that "}" is not allowed is received but the label is saved. 

Please see the screencast for more details.

![forbidden](https://user-images.githubusercontent.com/56026823/84157073-ee589d80-aa72-11ea-8da9-c76b667a620f.gif)

**Comment by lesleyjanenorton** [comment]
I don't think the label is actually saved into the add-on storage in this instance. If you do a hard refresh of the page or open the page in a new tab is it the label with errors still visible?

**Comment by sbadau** [comment]
> I don't think the label is actually saved into the add-on storage in this instance. If you do a hard refresh of the page or open the page in a new tab is it the label with errors still visible?

Indeed, If I add a label containing a forbidden character and I do a hard refresh by pressing on the Ctrl+F5 keys, then the label is not saved.

But, I did found one scenario where I do get the message that a label containing a forbidden character is saved - the "Label Saved" message is received and the label remains saved even after a hard refresh. Please see the screencast (the last refresh that can be seen on the video is a hard refresh)

![2020-06-10_12h11_14](https://user-images.githubusercontent.com/56026823/84249647-b5bcd080-ab13-11ea-8342-0a6df85dc2b1.gif)


Lesley, I also noticed that labels are not displayed at all If the private relay website is opened from the Manage Aliases directly from the add-on. Is this to be expected? Please see the screencast:

![2020-06-10_12h22_02](https://user-images.githubusercontent.com/56026823/84251009-6d061700-ab15-11ea-9854-87efa8bbf808.gif)

**Comment by lesleyjanenorton** [comment]
Regarding the labels not appearing when you visit the dashboard from the add-on button - this is not expected and great find! Should be fixed in 26ac3d2

**Comment by sbadau** [comment]
I can no longer reproduce the issues mentioned in my previous comment with the latest version of the add-on.

As for the scenario from the description, the label is not saved if I do a hard refresh.
