### ISSUE TITLE
[Website] Relay icon overlaps other form elements

### ISSUE THREAD

**Issue by alexgibson** [mozilla/fx-private-relay#401]
STR:

1. With the Firefox Relay extension installed, visit https://www.mozilla.org/en-US/firefox/privacy/products/
2. Scroll down to the Firefox Account signup form at the bottom of the page.

Expected result:

I should be able to fill out the form and sign up for a Firefox Account

Actual result:

The Firefox relay icon takes over the entire form area, preventing completion.

![image](https://user-images.githubusercontent.com/400117/84370542-4e188b00-abd0-11ea-99a4-401cf1f72f11.png)

**Comment by alexgibson** [comment]
There are similar issues on other pages:

https://www.mozilla.org/en-US/firefox/browsers/

![image](https://user-images.githubusercontent.com/400117/84370676-7c966600-abd0-11ea-80c4-8aae88ab38bc.png)

**Comment by groovecoder** [comment]
Oh, looks like this is fixed.
