### ISSUE TITLE
[Addon] The content of the Firefox Relay door-hanger is bouncy when opened

### ISSUE THREAD

**Issue by sbadau** [mozilla/fx-private-relay#405]
**Affected versions**
Firefox 77.0.1
Firefox Private Relay 1.3.1

**Affected platforms**
Windows 10
Mac OS X 10.14
Ubuntu 18.04

**Steps to reproduce**:
1. Launch Firefox.
2. Install the Firefox Private Relay add-on
3. In the address bar, click on the Private Relay add-on.
4. Observe the add-on's door-hanger.

**Expected behavior**
The door-hanger is properly opened and displayed.

**Actual behavior**
The content of the Firefox Private door-hanger bounces when opened. 

Please see the scree-cast for more details.

![2020-06-12_12h25_35](https://user-images.githubusercontent.com/56026823/84491829-d7ea5600-acad-11ea-83aa-5808b4bd572e.gif)

**Comment by sbadau** [comment]
I can no longer reproduce this issue with the latest version of the add-on.

**Comment by groovecoder** [comment]
Oh, looks fixed. Thanks!

**Comment by sbadau** [comment]
This issue was verified, removing the needs-qa-reproduce.
