### ISSUE TITLE
[Addon] Error message is received when trying to Join the Waitlist

### ISSUE THREAD

**Issue by sbadau** [mozilla/fx-private-relay#406]
**Affected versions**
Firefox 77.0.1
Firefox Private Relay 1.3.1

**Affected platforms**
Windows 10
Mac OS X 10.14
Ubuntu 18.04

**Steps to reproduce**:
1. Launch Firefox.
2. Install the Firefox Private Relay add-on
3. In the address bar, click on the Private Relay add-on.
4. Click on "Sign Up for the waitlist with your Firefox account" button.
5. Fill the rest of the form with the correct data (email, password, verification code)
6. Click on the "Join the Waitlist" button.
 
**Expected behavior**
A message that you have been added on the waitlist should be displayed. 

**Actual behavior**
The following error message is displayed: "Oops, we're sorry but we hit a snag adding your email to the waitlist. Please try again later or file an issue."

![2020-06-12_15h46_23](https://user-images.githubusercontent.com/56026823/84504994-9b2a5900-acc5-11ea-936a-1f2b61257de1.png)

**Comment by lesleyjanenorton** [comment]
Should be fixed in #408 . Thank you for catching!

**Comment by lesleyjanenorton** [comment]
Closing as fixed (as of #408) but please reopen if you're still able to reproduce. thanks!

**Comment by sbadau** [comment]
I can confirm that the issue is no longer reproducible - the user is now successfully been added to the Relay waitlist - verified with the latest version of the Private relay add-on (1.4.1) and Firefox 77.0.1.
