### ISSUE TITLE
[Addon] Links on "Settings" page are redirecting to the addon main page

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#407]
### Affected versions
Firefox 77.0.1
Firefox Private Relay 1.3.1

### Affected platforms
Windows 10
Mac OS X 10.14
Ubuntu 18.04

### Steps to reproduce:

1. Launch Firefox.
2. Install the Firefox Private Relay add-on.
3. In the address bar, click on the Private Relay add-on.
4. Click on "Settings" button.
5. Click on any of the links on the page.

### Expected behavior
Links are redirecting the addon main page.

### Actual behavior
[Addon] Links on "Settings" page are redirecting to the addon main page
![Screenshot 2020-06-12 at 16 25 56](https://user-images.githubusercontent.com/15101135/84515336-02033e80-acd5-11ea-9527-5802633a2c8c.png)

**Comment by lesleyjanenorton** [comment]
Thanks - this is a known but and we'll update the links as soon as we have the correct URLs

**Comment by sv-hyacoub** [comment]
Verified on Firefox 78.0.2 using Version 1.4.2 of Firefox Relay add-on on MacOS 10.14, Windows 10 x64 and on Ubuntu 18.04 x64.

**Comment by groovecoder** [comment]
Closing this one as the links are removed. We'll open a new issue for adding real links.
