### ISSUE TITLE
[Button] Private Relay button is displayed maximised 

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#412]
### Affected versions

Firefox 76.0.1
Firefox Private Relay 1.3.1

### Affected platforms
Windows 10
Mac OS X 10.14
Ubuntu 18.04

### Steps to reproduce:

1. Launch Firefox.
2. Install the Private Relay add-on.
3. Go to https://my.1password.com/signin.

### Expected behavior

Private Relay button should be correctly displayed. 

### Actual behavior

Private Relay button is displayed maximised.
![Screenshot 2020-06-15 at 12 10 55](https://user-images.githubusercontent.com/15101135/84653670-8395df00-af16-11ea-8f41-e037b5ff72fd.png)

**Comment by sv-hyacoub** [comment]
The same issue is displayed on https://www.microsoft.com/.
![Screenshot 2020-06-16 at 17 47 54](https://user-images.githubusercontent.com/15101135/84790085-a1884000-aff9-11ea-95e8-7ce9d8690768.png)

**Comment by lesleyjanenorton** [comment]
After last batch of fixes in 3fd510b
<img width="500" alt="Screen Shot 2020-06-18 at 10 11 11 AM" src="https://user-images.githubusercontent.com/22355127/85038350-15d2f880-b14c-11ea-9b67-4979b88ecee7.png">
<img width="498" alt="Screen Shot 2020-06-18 at 10 12 26 AM" src="https://user-images.githubusercontent.com/22355127/85038480-3bf89880-b14c-11ea-92a9-1382c13a4079.png">

**Comment by sv-hyacoub** [comment]
Verified as fixed on Firefox 77.0.1 using Firefox Relay Beta addon version 1.4.1 on Windows 10, Mac OS X 10.14 and on Ubuntu 18.04.
