### ISSUE TITLE
Relay add-on is shown with the wrong icon (wrong colors, looks squished) in Firefox on Android add-ons list

### ISSUE THREAD

**Issue by dholbert** [mozilla/fx-private-relay#4125]
STR:
1. Open Firefox on Android
2. Tap the 3-dot menu and choose "Add-ons"
3. Scroll down until you see the Firefox Relay listing, and look at the icon.
4. Tap the `+` to install the Relay add-on, and look at the icon now.

ACTUAL RESULTS:
* The icon shown in the Add-ons listing (step 3) looks wrong; it's got pink lines on a black hexagon, and looks vertically squashed.
* The icon shown after I hit `+` (step 4) looks correct (it matches the icon shown on https://relay.firefox.com/accounts/profile/ and has black lines on a pink hexagon, and does not look vertically squashed.

EXPECTED RESULTS:
Consistent icon -- we should show the correct Relay icon in the Add-ons listing in Firefox for Android in step 3 here.

(I don't know where this icon lives, so I'm not sure where exactly to file this -- in Relay or in https://github.com/mozilla-mobile/firefox-android or somewhere else. I'm starting this out as a bug in the Relay repo, anyway; we can morph/copypaste elsewhere as-needed.)

**Comment by dholbert** [comment]
Screenshot showing the wrong icon in step 3 (pink-lines-on-black-background, vertically squashed):
![screenshot](https://github.com/mozilla/fx-private-relay/assets/426803/096a210c-a776-436d-b204-58825924df5d)

**Comment by dholbert** [comment]
Screenshot showing what it looks like after I hit `+` (with the same wrong icon still visible, but the correct icon visible in the confirmation prompt):
![screenshot](https://github.com/mozilla/fx-private-relay/assets/426803/eede18bb-4145-4eee-93df-13f9ba1ba62f)

**Comment by dholbert** [comment]
@cpeterso noticed that the wrong icon (dark background, squashed height) seems to be live on AMO (that's probably where we're pulling it from): https://addons.mozilla.org/en-US/firefox/addon/private-relay/

**Comment by dholbert** [comment]
Screenshot of AMO with squashed/wrong-colors icon:

![Screenshot_20231119-133502](https://github.com/mozilla/fx-private-relay/assets/426803/d49769f6-4c54-4acc-a33f-2bad5526ca37)

**Comment by maxxcrawford** [comment]
@dholbert Thanks for flagging this. I updated the icon with AMO. 

https://addons.mozilla.org/en-US/firefox/addon/private-relay/ now shows the correct icon. I checked on the Firefox for Android add-ons list, but it's still cached. 

<img width="769" alt="image" src="https://github.com/mozilla/fx-private-relay/assets/2692333/2cb92949-600b-4817-a467-9b4445f62438">

<img width="417" alt="image" src="https://github.com/mozilla/fx-private-relay/assets/2692333/e2c8b423-cda9-4895-8688-ffda2b157012">

**Comment by maxxcrawford** [comment]
Also, fwiw - the Chrome web store has the same logo too. This _should_ make it consistent across all the surfaces. 

<img width="611" alt="image" src="https://github.com/mozilla/fx-private-relay/assets/2692333/495215e0-fd8c-4ed1-8e52-be807755bd2a">

**Comment by dholbert** [comment]
> @dholbert Thanks for flagging this. I updated the icon within AMO.
> 
> https://addons.mozilla.org/en-US/firefox/addon/private-relay/ now shows the correct icon. I checked on the Firefox for Android add-ons list, but it's still cached.

Thanks, @maxxcrawford ! I'm seeing the correct icon in the Firefox-for-Android addons list (testing with Firefox Beta 120.0b9 which was mostly-fresh-profile, to avoid the potential for locally cached old icons.)

So: verified-fixed. \o/
