### ISSUE TITLE
Account Is Paused

### ISSUE THREAD

**Issue by daniel-gn-desouza** [mozilla/fx-private-relay#4224]
I recently got my account paused due to high daily usage. There was no clear indication and I scrambled to get support from Mozilla/Firefox because none of my email masks were forwarding and I couldn't create more. This daily usage limit should be advertised up front when you pay for the subscription and when you get the error so at least the user knows when their account will be un-paused. It was my experience that I considered refunding my subscription and cancelling because of this uncertainty.

**Comment by groovecoder** [comment]
We have rate limits in place to prevent abuse. We do not publish these limits, to make it harder for people who would abuse Relay to work around them. Did you file a customer support ticket? It will be easier to work on this issue in a confidential customer support ticket.

**Comment by groovecoder** [comment]
Found the support ticket. I'm working with our customer support team on this now. Closing this GitHub issue.
