### ISSUE TITLE
Mention website language in the google doc "List of websites to be tested"

### ISSUE THREAD

**Issue by jakobkappel** [mozilla/fx-private-relay#425]
This will make it easier for testers to find websites they can help test.

**Comment by jakobkappel** [comment]
[privateRelayTestSites.xlsx](https://github.com/mozilla/fx-private-relay/files/4796059/privateRelayTestSites.xlsx)

Most pages are checked with Google Translate, so there might be some errors. 

---

A lot of the sites are in Chinese. Maybe you should reach out to the Chinese l10n team to get more testers to look at these sites? https://wiki.mozilla.org/L10n:Teams:zh-CN

---

For the same reason you might consider rewording the instructions for testing on the Community Portal. Hopefully a lot of Mozillians want to help - and it's probably better if they just test whatever web sites they use to log in to in their daily lives.

**Comment by EMMLynch** [comment]
Please reopen if this is still needed.
