### ISSUE TITLE
Cannot send emails with an empty subject

### ISSUE THREAD

**Issue by aroraharsh010** [mozilla/fx-private-relay#426]
STR:
 1. Generate a relay alias address.
 2. Send an email to the alias address with no subject, anything can be in the body.

Expected Results:
?The email should have been forwarded regardless of whether it has a subject or not?

Actual Results:
The email doesn't show up in the inbox nor the spam folder. The dashboard sections of forwarded, block or spam don't get updated for these emails.

**Comment by groovecoder** [comment]
https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/8894633/?query=is%3Aunresolved
