### ISSUE TITLE
Feature request: add descriprion

### ISSUE THREAD

**Issue by massimo-cassandro** [mozilla/fx-private-relay#4265]
Feature request: Ability to add a short description to the relay email addresses

**Comment by Vinnl** [comment]
Hi @massimo-cassandro, you can add labels to masks, does that cover your use case? You might have to [enable it in settings](https://support.mozilla.org/en-US/kb/use-labels-keep-your-masks-organized-firefox-relay#w_get-your-labels-on-all-your-devices) first, if you have an older account.

**Comment by massimo-cassandro** [comment]
oops, thanks, I missed that
