### ISSUE TITLE
Note which websites in the google doc "List of websites to be tested" has adult content

### ISSUE THREAD

**Issue by jakobkappel** [mozilla/fx-private-relay#427]

**Comment by couci** [comment]
@jakobkappel thanks for the note. This list is coming from alexa's most used, and while we have marked one obvious website we don't know all of them. Could you provide which website you came across as adult content?

**Comment by jakobkappel** [comment]
Well, I actually just started searching for the domain names to get an idea of which language the various sites were in (since some of them loaded slowly). And a few came up with a description that suggested that they had adult content. 

I decided to have a look at all the pages to help with #425 

So I added a column in the spread sheet for "Has adult content?"


[privateRelayTestSites.xlsx](https://github.com/mozilla/fx-private-relay/files/4796056/privateRelayTestSites.xlsx)

**Comment by EMMLynch** [comment]
Please reopen with additional details if this is still needed.
