### ISSUE TITLE
The "Private Relay" button is not displayed on the email address field only after the page is refreshed.

### ISSUE THREAD

**Issue by obotisan** [mozilla/fx-private-relay#429]
**Affected versions**
- Firefox 76.0.1
- Private Relay add-on version 1.3.1

**Affected platforms**
- Windows 10
- Mac OS X 10.14
- Ubuntu 18.04

Steps to reproduce:

1. Launch Firefox.
2. Install the Private Relay add-on
3. Navigate to nytimes.com and click on the "LOG IN" button.
4. Click on the "Create one" hyperlink.
5. Observe the "Email Address" field. 

**Expected behaviour**
- The "Private Relay" button is displayed on the email address field.

**Actual behaviour**
- The "Private Relay" button is not displayed, only after you refresh the page. 

**Additional notes**
- This happens on: adobe.com, too

**Comment by birdsarah** [comment]
I cannot reproduce this Oct 26 with 1.4.5, FF81, Linux.
