### ISSUE TITLE
[Button] The Private Relay doorhanger is wrongly positioned

### ISSUE THREAD

**Issue by andreipurice** [mozilla/fx-private-relay#431]
**Affected versions**

Release 77.0.1
Private Relay add-on version 1.3.1

**Affected platforms:**
Windows 10 
Ubuntu 18.04
Mac Os X 10.15

**Steps to reproduce**

1. Launch the latest Release
2. Install the Private Relay add-on and sign in
3. Go to https://www.tripadvisor.com and reach the sign up page
4. Observe the position of the Private Relay doorhanger 

**Expected behavior**
The Private Relay doorhanger should be displayed correctly under the button.

**Actual behavior**
The Private Relay doorhanger is displayed incorrectly in the upper left side of the screen and it can be barely seen.

Please see the screen-cast for more details: 
![tripadvisor](https://user-images.githubusercontent.com/67056974/84902834-fee1c700-b0b5-11ea-9489-3e835378387b.gif)

**Comment by lesleyjanenorton** [comment]
<img width="514" alt="Screen Shot 2020-06-18 at 9 52 31 AM" src="https://user-images.githubusercontent.com/22355127/85036281-9b08de00-b149-11ea-842c-eff5ff1811f2.png">
I can't reproduce this for some reason

**Comment by sbadau** [comment]
I can confirm this issue is fixed, verified using the latest version of the Private Relay add-on (version 1.4.1) and Firefox 77.0.1 on Windows 10, Ubuntu 18.04, and Mac OS X 10.14.
