### ISSUE TITLE
[Website] "Label saved! is not an allowed character."

### ISSUE THREAD

**Issue by donmccurdy** [mozilla/fx-private-relay#434]
Immediately after creating a new address, I see an error `Label saved! is not an allowed character.` above every address (old addresses, and the newly created one). 

![Screen Shot 2020-06-17 at 10 10 25 AM](https://user-images.githubusercontent.com/1848368/84928512-5a469180-b083-11ea-82a5-5c163d47cfc5.png)

Additionally, there are a number of whitespace / padding issues scattered around the UI, where icons are slightly shifted or text needs a bit more space around it.

**Comment by lesleyjanenorton** [comment]
This is really strange - it looks like you're seeing a combination of new templating/old CSS... have you tried hard refreshing?

**Comment by donmccurdy** [comment]
I tried a hard refresh and it looks ok now, thanks!
