### ISSUE TITLE
Mozilla is blocking Firefox Relay!? and I lost access to my Mozilla account because of it, HELP

### ISSUE THREAD

**Issue by StoopidoMan** [mozilla/fx-private-relay#4348]
My Mozilla account is made with a Firefox Relay Email, but now I can't login anymore. I was not sent any warning to change my email or anything, on top of that isn't a Firefox Relay a Mozilla product!? 

When I try to login to my Mozilla account I face this error message "Email masks can't be used to create an account"  it shows that error message because the **sign in** and **sign up** is the same button. I already have an account.

please contact your colleague and help me get my account back. 

![image](https://github.com/mozilla/fx-private-relay/assets/71223069/bf0cbe06-7e38-406c-bebf-fe3eff111b59)

**Comment by pdehaan** [comment]
Thanks for the report @StoopidoMan.
I’ve escalated this to the Mozilla Accounts team, and found this recent maybe-related-sounding ticket https://github.com/mozilla/fxa/pull/16219. It’s Sunday so it might take a day or two to get some replies and investigate. 🙏

**Comment by StoopidoMan** [comment]
THANK YOU, I Can't login to my account!!  PLEASE explain to the that this should be resolved ASAP because if there are other users like me not being able to login to your account is a horrible feeling. THANK YOU

**Comment by JC-Support** [comment]
Hey there @StoopidoMan! Can you submit a support request to our team? You can reach them by clicking the blue "Contact Support" button at https://support.mozilla.org/en-US/questions/new/mozilla-account. There is an option for contacting us if you are unable to sign into your account that you can select. 

You can update me here when you've submitted that request. Thanks!

**Comment by StoopidoMan** [comment]
@JC-Support  DONE. I added a link to this issue in the message body: "https://github.com/mozilla/fx-private-relay/issues/4348"

I did it last time but I got an automated generic reply

**Comment by JC-Support** [comment]
Hi @StoopidoMan. Thanks for doing that! I've located your ticket and responded to you. Going forward I will assist you through that channel. Thanks again!

**Comment by EMMLynch** [comment]
I'm going to close this issue on GitHub since we are moving to the ticket for any additional support.

**Comment by StoopidoMan** [comment]
Hello @JC-Support  
I am not a premium user and I can't reply to you there. I will answer here:

> can you provide the email mask you used on your account? 
 
my account is the same email address I used to contact support which start with an "i" and ends with a "g"

> can you confirm if you have a secondary email address associated with the account?  

No, I don't have any other email account associated with my account 

also, is this a permanent decision, so I can't use Firefox Relay Email to login to my Mozilla account?  
if that the case let me know, so I create a new email address for my Mozilla account.

**Comment by JC-Support** [comment]
Hi @StoopidoMan, I'm not quite sure what you mean when you say you can't reply. I contacted you via email. Are you unable to reply via email?
