### ISSUE TITLE
[Add-on] The Survey door-hanger is broken

### ISSUE THREAD

**Issue by sbadau** [mozilla/fx-private-relay#436]
**Affected versions**
Firefox 77.0.1
Firefox Private Relay 1.3.1

**Affected platforms**
Windows 10
Mac OS X 10.15
Ubuntu 18.04

**Steps to reproduce**:
1. Launch Firefox.
2. Install the Firefox Private Relay add-on and log in.
3. Go to any site with a sign-up form and create 5 aliases
4. In the address bar, click on "Take the Survey"

**Expected behavior**
The user should be able to leave a survey through the door-hanger that is opened.

**Actual behavior**
The door-hanger is broken. 
Please see the scree-cast for more details.

![survey](https://user-images.githubusercontent.com/56026823/84933715-fb166a80-b0de-11ea-9b87-c479fa2245e5.gif)

**Comment by lesleyjanenorton** [comment]
Closing - This content has changed and there will no longer be a link to the survey

**Comment by sbadau** [comment]
I can confirm this issue is no longer reproducible, the content is now chanced - verified using the Private Relay 1.4.1 and Firefox 77.0.1 on Ubuntu 18.04, Mac OS X 10.14 and Windows 10.
