### ISSUE TITLE
[Website][Enhancement] The page should refresh after an alias is Copied

### ISSUE THREAD

**Issue by sbadau** [mozilla/fx-private-relay#445]
**Affected versions**
Firefox 77.0.1
Firefox Private Relay 1.3.1

**Affected platforms**
Ubuntu 18.04
Mac OS X 10.5
Windows 10

**Steps to reproduce**:
1. Launch Firefox.
2. Install the Firefox Private Relay add-on and Sign In
3. In the Firefox Relay website, copy one of the existent alias
4. Create an account with it, go back to the tab where the Firefox Relay website is opened, and copy again the same alias. 

**Expected behavior**
The user should be able to copy again the same alias and he should also be notified about it.

**Actual behavior**
The user can copy again the alias but there is no notification about this.

Please see the screencast for more details.
![copied](https://user-images.githubusercontent.com/56026823/85024958-70397c80-b17f-11ea-8178-275e1e4042e6.gif)

**Comment by EMMLynch** [comment]
Please reopen if this is still needed.
