### ISSUE TITLE
privaterelay/templates/profile.html: Unexpected closing tag "div"

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fx-private-relay#456]
```sh
npx prettier 'privaterelay/**/*.html' --write

...

privaterelay/templates/profile.html
[error] privaterelay/templates/profile.html: SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (132:3)
[error]   130 |       </div><!-- end dashboard-container -->
[error]   131 |     </div>
[error] > 132 |   </div>
[error]       |   ^
[error]   133 | </main>
[error]   134 | 
[error]   135 | {% endblock %}
privaterelay/templates/socialaccount/authentication_error.html 49ms
```

(Note: Ignore the slightly misleading line numbers, I had to cut some code since Prettier wasn't happy about the mixed handlebars+html for some block, so I had to cut a few lines of code to make the parser happy).

The line in question seems to be this: https://github.com/mozilla/fx-private-relay/blob/6c4876b94a60f928d21644dcb68dab186c1ddc8f/privaterelay/templates/profile.html#L147

**Comment by groovecoder** [comment]
@lesleyjanenorton if we've got some time, we might go thru `npx prettier` output and see what we might be able to clean up.

**Comment by jwhitlock** [comment]
Site rendering has moved to Next.js, so this issue is now invalid
