### ISSUE TITLE
New tab on upgrade — is the waitlist open?

### ISSUE THREAD

**Issue by hackel** [mozilla/fx-private-relay#470]
This has happened to me on 2 different machines now.  I have the Firefox Relay extension installed in anticipation of the public beta opening.  After the most recent automatic update, a `moz-extension://../first-run.html` tab automatically opens (annoying) with a link prompting me to "Join the waitlist."  Clicking on this link simply takes me to https://relay.firefox.com/, where there is another link: "Get on the waitlist with a Firefox account".  Clicking on this link prompts me to sign in to Firefox Private Relay, after which I just see the message "Were you invited to join the Private Relay beta? Visit the link in your email invitation to complete your registration. Be sure you are using the same email address you used to join the waitlist." This doesn't sound like I'm actually on any waitlist, but I can't be sure.

I have no problem waiting patiently for the waitlist/beta to open, but if it's not open, the extension shouldn't be opening a new tab automatically inviting people to join.  It's confusing.

**Comment by Sim59121** [comment]
Hello,

I have exactly the same problem.
I have test with several devices.

Regard,

**Comment by groovecoder** [comment]
The wait-list should be open for you to join now. Can you try again?

**Comment by Sim59121** [comment]
I have retry and the problem is still present.

Other times, I log in and it takes me back to the Firefos Private Relay home page and asks me to log in to join the waiting list.

**Comment by groovecoder** [comment]
Okay, we'll look into this today. Thanks for reporting.

**Comment by Sim5912** [comment]
Thanks ! 

I remain at your disposal if you need me.

**Comment by say-yawn** [comment]
Hi all, wait-list is open again. As for (1) stop displaying the first-run tab after it's first displayed and (2) making the experience better on enlisting on wait-list better from add-on, there are fixes coming later today.

**Comment by hackel** [comment]
The first-run tab just opened again and I was able to follow all the links to join the waitlist successfully this time.
