### ISSUE TITLE
`css/relay.css` injected into pages conflict with web page styles

### ISSUE THREAD

**Issue by ExE-Boss** [mozilla/fx-private-relay#472]
Because the extension injects `css/relay.css` into all pages:
<https://github.com/mozilla/fx-private-relay/blob/85607c693764a59d57ecf49905318e5b71905ae2/extension/manifest.json#L45-L52>

And `css/relay.css` contains:
<https://github.com/mozilla/fx-private-relay/blob/85607c693764a59d57ecf49905318e5b71905ae2/extension/css/relay.css#L70-L89>

The injected stylesheet ends up conflicting with web page styles.

## Proposed solutions:
- Separate `css/relay.css` into a stylesheet that is safe to inject into web pages and a stylesheet that is used in extension pages.
- Use **Shadow DOM** to enclose the **Firefox Relay** menu.

**Comment by dgdavid** [comment]
I can confirm this issue. In my case, I cannot distinguish links from the rest of text in Github issues / comments / descriptions.

**Comment by dgdavid** [comment]
Probably related to / duplicated of https://github.com/mozilla/fx-private-relay/issues/341

**Comment by hoosteeno** [comment]
I am seeing an apparent relay-styles-related issue in many other sites (Google Docs, Google Analytics...). The easiest test of my issue is at www.google.com. STR:

1. Visit www.google.com in vanilla profile. See the big rainbow colored logomark above search input box.
2. Install relay extension https://addons.mozilla.org/en-US/firefox/addon/private-relay/
3. Visit www.google.com again. See no big rainbow colored logomark.

![Screen Shot 2020-06-23 at 11 47 44 AM](https://user-images.githubusercontent.com/94519/85437539-f707a400-b547-11ea-9084-e20d9db429b2.png)

**Comment by AnishRV-NYT** [comment]
Having issues on gmail as well. 
**With Private Relay enabled:**
<img width="74" alt="Screen Shot 2020-06-23 at 10 48 27 AM" src="https://user-images.githubusercontent.com/66200765/85437204-13eba980-b53f-11ea-866c-0cdd9797fb81.png"> 
**Without:**
<img width="109" alt="Screen Shot 2020-06-23 at 10 48 02 AM" src="https://user-images.githubusercontent.com/66200765/85437182-07ffe780-b53f-11ea-9321-bae43b68818e.png">

**Comment by Termuellinator** [comment]
If more examples are needed: computerbase.de has white link-texts with the latest update of privacy relay, golem.de has very narrow text-layout and the "google it!"-button of the addon [DuckDuckGoogle](https://addons.mozilla.org/de/firefox/addon/duckduckgoogle/) is almost invisible on a dark theme.
All fine when addon is disabled.

**Comment by valenting** [comment]
`box-sizing: border-box;` Also affects Google docs.
![image](https://user-images.githubusercontent.com/1454649/85589873-39aea680-b644-11ea-9d47-31964616bfb6.png)

**Comment by groovecoder** [comment]
Closing this now that https://github.com/mozilla/fx-private-relay/pull/501 is merged. All sites should be fixed in next release.
