### ISSUE TITLE
[Website] Website does not detect if the add-on is installed on first page view

### ISSUE THREAD

**Issue by jakobkappel** [mozilla/fx-private-relay#486]
1. Install the add-on
2. Click "Manage Relay Adresses" from Private Relay icon in the Bookmarks Toolbar (or go to https://relay.firefox.com/accounts/profile/)
3. A box with the text "Looks like you haven't installed the add-on... yet![...]" shows up
4. But it disappears if you reload the page.

**Comment by sv-hyacoub** [comment]
Verified on Firefox 78.0.2 using Version 1.4.2 of Firefox Relay add-on on MacOS 10.14, Windows 10 x64 and on Ubuntu 18.04 x64.
