### ISSUE TITLE
Problem for joining the waiting list on firefox

### ISSUE THREAD

**Issue by Sim5912** [mozilla/fx-private-relay#491]
Hello,

I tried to get on the waiting list on firefox, but it's not working.
I click on the button to join the waiting list, I log in and then I click on "join the waiting list".

Then, I always get the same error message : 

"Oops, we're sorry but we hit a snag adding your email to the waitlist.

Please try again later or file an issue."

I tried several times without success.

However, when I tried edge (the new one which is based on chromium), everything worked the first time.

What can I do ?

Regard,

![bug](https://user-images.githubusercontent.com/51054004/85600085-6f0bc200-b64d-11ea-8d5f-4d0c694ee91d.JPG)

**Comment by groovecoder** [comment]
Looks like this might be caused by https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/8862456/?query=is%3Aunresolved

**Comment by Sim5912** [comment]
I can't access the link because it asks me for credentials :(

**Comment by say-yawn** [comment]
@Sim5912 apologies for the confusion, that link was for me. I'll look into this. Thanks for filing!

**Comment by Sim5912** [comment]
Sorry !

No problem :) 
I remain available if needed

**Comment by groovecoder** [comment]
I was able to reproduce this with NoScript installed.

**Comment by Sim5912** [comment]
I have NoScript but he's deactivated
