### ISSUE TITLE
SNS messages with invalid signatures

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#494]
May be causing #478.

See https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/8801352/?query=is%3Aunresolved ...

**Comment by say-yawn** [comment]
To get more information in Sentry it may be worth replacing the `logger.error` [here](https://github.com/mozilla/fx-private-relay/blob/master/emails/views.py#L145) with `capture_message` from Sentry's SDK.

**Comment by groovecoder** [comment]
As mentioned in #440, one of the senders triggering this error is twitch. So they'll be a good service to work and debug this issue.
