### ISSUE TITLE
Support emails with attachments

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#498]
UPDATED DESCRIPTION:

Changing this from a bug to an enhancement. To scope the work we should first:

* [ ] Start recording the size of attachments so we can predict how much bandwidth it may take
* [ ] Start recording the file types of attachments so we know what we may need to support
* [ ] Start recording the number of attachments so we know what we may need to support

OLD DESCRIPTION:

Sentry error: https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/8811759/activity/?query=is%3Aunresolved

SES charges $0.12/GB of data in messages sent, so (large) attachments could increase costs significantly. So we need to decide how we might support attachments.

At the very least, we should relay the email content without an attachment, and possibly include a note that attachments aren't supported?

**Comment by groovecoder** [comment]
This is causing these sentry errors: https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/8811760/activity/?query=is%3Aunresolved

**Comment by say-yawn** [comment]
Reopening this as we have a follow-up PR to inform the users that we will not be supporting attachments for now.

**Comment by bastian2001** [comment]
I hope this is the right place to put my issue.

I recently ordered a ticket online using Firefox Relay, not knowing that it doesn't support attachments (yet). Firefox Relay does not list the mail as "blocked", nor have I received it. I also just tried sending an email with an attachment from another of my addresses to my relay alias. Same issue - it's not marked as blocked but also not forwarded. Is there any way I can get it?

I get the financial point, and I would pay whatever it takes to get it to me. But to me that feels very irresponsible to not tell users about this limitation. If I would have known, I would have chosen one of my actual email addresses.

**Comment by groovecoder** [comment]
Thanks for bringing this to our attention. We haven't prioritized attachment support since we've seen very little of it so far. But some attachments are obviously very important - sorry we lost this one. I'm contacting our SES support tech to see if we can recover it. And we'll consider adding messaging informing users that attachments are not currently supported.

**Comment by groovecoder** [comment]
@bastian2001 we might be able to recover the email with your attachment, if you can find the email message ID. To do so, look at the email *headers* in the relay email (e.g., in Gmail you need to click "Show Original" on the email) and find the `Message-ID:` header value. If you can send that to 9v12h877u@relay.firefox.com I'll see if we can recover the attachment.

**Comment by bastian2001** [comment]
@groovecoder thank you for your kind reply. I'm sorry, but I forgot to tell you that I was able to make them resend me the ticket to another mail address. Hope I didn't take too much time of you.

Thank you also for creating that other issue. I think informing users of this is very important.

**Comment by groovecoder** [comment]
No worries; glad you got your ticket! We definitely took your feedback to prioritize better baseline attachment support. So thank you for the feedback!

**Comment by groovecoder** [comment]
Closing this - we support attachents now.
