### ISSUE TITLE
[Website] [Extension] Website doesn't know when the extension is installed, but disabled.

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/fx-private-relay#505]
I had the Private Relay extension disabled.

I signed in to Private Relay, and the website thought I didn't have extension installed. I had it installed, but it was disabled. The message was a little bit confusing. 

See the screenshot that shows the message you get when the website thinks you don't have the extension installed:
![Screen Shot 2020-06-25 at 11 10 51 AM](https://user-images.githubusercontent.com/911251/85778070-0d903580-b6d7-11ea-8766-f528ad8b2476.png)

**Comment by groovecoder** [comment]
Closing as dupe of #486
