### ISSUE TITLE
problem with "umlauts" in sender's name

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/fx-private-relay#523]
I have sent an e-mail from my Google Mail to my Yahoo Mail account via Firefox Relay. This is how Thunderbird showed the sender's name:

<img width="148" alt="Bildschirmfoto 2020-06-29 um 23 37 06" src="https://user-images.githubusercontent.com/1100614/86058615-7a058e80-ba61-11ea-98e7-762578d063a9.png">

The name should be "Sören" not "S?ren", it's probably a problem with all "umlauts" (ä, ö, ü - very common in German language).

The From mail header looks like:

`From: "\"Sï¿½ren Hentzschel\"  <email@example.org>  [via Relay]`

I compared with other e-mails that did not have this problem. In all other e-mails the From mail header looks like:

`From: =?UTF-8?Q?S=C3=B6ren_Hentzschel?=  <email@example.org>`

**Comment by tedschuh** [comment]
Should be fixed for GA.

**Comment by groovecoder** [comment]
A related AMO review report that the entire email contents are broken in other languages. 😢 

https://addons.mozilla.org/en-US/firefox/addon/private-relay/reviews/1584361/

**Comment by say-yawn** [comment]
Was only able to replicate this error on the From header. The Subject and Body properly uses UTF-8.

**Comment by say-yawn** [comment]
Was able to replicate broken encoding on the body of the message.

**Comment by say-yawn** [comment]
Separate issue https://github.com/mozilla/fx-private-relay/issues/655 created to deal with broken encoding on the body of the message.
