### ISSUE TITLE
morningbrew.com does not accept Relay address

### ISSUE THREAD

**Issue by hmitsch** [mozilla/fx-private-relay#524]
## Test Condition
* Open https://www.morningbrew.com/
* Subscribe with email `0oahj6o1s@relay.firefox.com`

## Expected Result
* Newsletter is subscribed

## Actual Result
* `Email is not a valid. If you believe this is a mistake, contact us for help`

## Additional Information
I contacted Morning Brew support and asked for help. No answer yet.

**Comment by groovecoder** [comment]
This seems to work now.
