### ISSUE TITLE
Issue with Latin Extended Charactes

### ISSUE THREAD

**Issue by hexandcube** [mozilla/fx-private-relay#529]
It looks like Firefox Relay doesn't support Latin Extended characters, because it has changed the "ł" in my name to "B". So it's MikoBaj, instead of Mikołaj.
![image](https://user-images.githubusercontent.com/41151156/86235397-a53ec980-bb98-11ea-9971-b2027213ea0f.png)

**Comment by nukeador** [comment]
+1 to this, it seems related with unicode chars

**Comment by groovecoder** [comment]
Thanks for filing this. Closing this as dupe of #523 - can you upvote there?
