### ISSUE TITLE
Sender's email

### ISSUE THREAD

**Issue by nukeador** [mozilla/fx-private-relay#532]
On forwarded emails I can't see how is the real sender, sender is always noreply@relay.firefox.com

How I do I know who are emails really coming from?

Related with https://github.com/mozilla/fx-private-relay/issues/99

**Comment by groovecoder** [comment]
Can you provide more details of what you're seeing? This is what I see as the Sender when receiving a forwarded email ...

<img width="613" alt="image" src="https://user-images.githubusercontent.com/71928/86843249-ebe66500-c06b-11ea-8b76-5b6e8ef30ee5.png">

**Comment by nukeador** [comment]
I can only see the noreply@relay.firefox.com, even clicking on more details for the email.

![imagen](https://user-images.githubusercontent.com/531906/86912473-5c998a00-c11d-11ea-96e1-9ffee2bae8ef.png)

**Comment by neubland** [comment]
Anonaddy has the corresponding Alias as a sender. Example:

Anna sends mail to "<randomstuff@relay.firefox.com>"

Firefox Relay forwards the mail to Bob

Bob receives a mail from "Anna/Accountname <randomstuff@relay.firefox.com>", not from "<noreply@relay.firefox.com>"

Bob is now able to set up mail filters in their Inbox.

**Comment by MorbidMind** [comment]
Also have this issue. Got an email from "\"[Shop name]\"  [via Relay]" <noreply@relay.firefox.com>.

Couldn't find the original email address anywhere in the message nor in the headers.

"Reply-to:" header should be pointing to the original sender's email, but instead it points to "\"[Shop name]\"  [via Relay]" <noreply@relay.firefox.com> as well.

Situation is a bit bad, because without answering that specific message I won't be able to get a money return.

**Comment by samuelroland** [comment]
Hey
I have the same issue. It's very problematic to not be able to see the original sender email... Is there any plan to fix it? This issue is old and (from my point of view) doesn't look like a big issue to fix... Thanks for your work on this very useful tool though.

**Comment by ste0499** [comment]
Hi folks,
I would like to add the following example, an email from a reply to an ad on a popular site:

From: Bakecaincontrii.com <replyad@bakecaincontrii.com>
To: sma###@yahoo.com
**Reply-To: private###@gmail.com**

Reply-To has the real sender email address. 
With your relay service, I totally lose the sender e-mail address, so I can't reply her/him. 

From: "\"replyad@bakecaincontrii.com [via Relay]\"" <noreply@relay.firefox.com>
To: st####@gmail.com
Reply-To: replies@relay.firefox.com

This way your relay service is useless to me.

Anonaddy, a relay service competitor of yours, has a smart way to track the real sender email address with this tag:

**X-AnonAddy-Original-Reply-To-Header: sar####@gmail.com**

and it could be recovered easily even on the From: string:

From: "Bakecaincontrii.com 'replyad at bakecaincontrii.com'"
 <ezbylldx+sar####=gmail.com@anonaddy.me>

Hope it helps for future enhancements.

Cheers,

Stefano

**Comment by Vinnl** [comment]
Hi all, note that while you should be seeing the sender's email address as part o fthe sender name (e.g. in @ste0499's example, it's `replyad@bakecaincontrii.com`), you don't actually need that to reply to an email - [you can now](https://blog.mozilla.org/en/mozilla/firefox-relay-and-premium-service/) just send a reply, and Relay will forward it to the original sender without revealing your real email address.

That said, it is confusing that you need to send an email to _noreply_@relay.firefox.com; I created https://github.com/mozilla/fx-private-relay/issues/1671 to look at that.

**Comment by jwhitlock** [comment]
We changed this in August 2023. 

If the sender's headers are:

```
Subject: A special offer for you
From: "Your friends at service X" <offers@servicex.example.com>
To: r4nd0m@mozmail.com
```

Relay previously forwarded with:

```
Subject: A special offer for you
From: "offers@servicex.example.com [via Relay]" <replies@relay.firefox.com>
To: users-real-email@mail.example.com
Reply-To: replies@relay.firefox.com
```

Relay now forwards with:

```
Subject: A special offer for you
From: "offers@servicex.example.com [via Relay]" <r4nd0m@mozmail.com>
To: users-real-email@mail.example.com
Reply-To: replies@relay.firefox.com
Resent-From: offers@servicex.example.com
```

See https://github.com/mozilla/fx-private-relay/blob/main/docs/adr/0002-use-mask-as-from-address.md for options considered.

**Comment by jwhitlock** [comment]
I'm going to close this as fixed. Feel free to file new issues against the new behavior.

@ste0499 [says](https://github.com/ste0499):

> Reply-To has the real sender email address.
> With your relay service, I totally lose the sender e-mail address, so I can't reply her/him.

Since PR #1038 in September 2021, Relay has supported replies via `Reply-To: replies@relay.firefox.com`. The sender's information (including the `From` and the `Reply-To` headers) are encrypted, and the key split between us and the relayed email. When you reply to `replies@relay.firefox.com`, we determine the correct sender address (`Reply-To` then `From`) and send your email, coming from your Relay mask.
