### ISSUE TITLE
Domain forgery alert

### ISSUE THREAD

**Issue by nukeador** [mozilla/fx-private-relay#533]
My email provider is alerting me that 

> This email has failed your domain authentication requirements. It may be falsified or forwarded incorrectly!

Emails might result into spam folder due this issue.

**Comment by groovecoder** [comment]
Hmm ... our emails should be passing SPF and DKIM checks. We may need to check our DMARC for this though. Which email provider is it? So we can test this for ourselves.

**Comment by nukeador** [comment]
This is using protonmail.com

**Comment by nukeador** [comment]
Weird thing is that two emails I got today via relay on the different generated address didn't have this warning.

**Comment by groovecoder** [comment]
I wasn't able to reproduce this. This may have been during our SocketLabs-SES migration. Closing. Please re-open if it happens again.
