### ISSUE TITLE
Relay emails from Google forwarded to a gmail address will sometimes go to spam.

### ISSUE THREAD

**Issue by gergolippai** [mozilla/fx-private-relay#535]
What I tested: signup on Google (Youtube.com)
Issue: the forward email (on Gmail) went to spam
![image](https://user-images.githubusercontent.com/44131758/86397249-c6401100-bca3-11ea-834e-95466e4f0bdb.png)

(The irony, google sending it's own email to spam :))

**Comment by groovecoder** [comment]
This is hard for us to address, especially because Gmail applies all its own heuristics to categorize spam, promotions, updates, etc.

If you can click "Report not spam" for us that will help inform Gmail that we're not a spam sender. :)

**Comment by gergolippai** [comment]
Did already :)

**Comment by jwhitlock** [comment]
Since this was opened, Google no longer allows you to sign up with a Relay email, so we won't be able to make progress on this issue. We continue to investigate ways to make Relay emails look less like spam.
