### ISSUE TITLE
Update beta invitation email to improve click-thrus

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#543]
Our target conversion rate for wait-list registrations/invites has been 10% - mostly just a reasonable guess based on some industry baselines. We’re currently at 8.66% from our first 5K invites sent. The link in the email goes to AMO to install the add-on. We can see that 479 (9.4%) of email recipients visited AMO. If 9.4% of email recipients visited AMO, and 8.66% completed their invitation, then the add-on-to-sign-up flow seems pretty good.

If we bump the email-to-AMO rate from 9.4% to 10.86%, we should see the overall conversion rate hit 10%.

Ideas for improvements to the invite email:

* Subject: Keep your email address out of data breaches with Firefox Relay
* Subject: Hide your email address from hackers and trackers with Firefox Relay
* Subject: Keep your email address out of data breaches: Redeem your Firefox Relay invitation
* Body: Add 2 links to AMO - top and bottom
* What else?

**Comment by groovecoder** [comment]
We also have an index on the `subscribers.breaches_last_shown` field in Monitor. So, another idea:

* Send invitations to Monitor wait-list folks who have visited their dashboard most recently - assuming they are more engaged overall

**Comment by maxxcrawford** [comment]
Oh! This sounds like an experiment. 🦊

**Comment by lesleyjanenorton** [comment]
- Add CTA to top of email
- Subject "_Keep_ your email address safe from hackers and trackers with Firefox Relay"
- Should we explore different CTA text ("Try Firefox Relay") ?

I wonder how many people received the email and didn't make the connection between Relay and the waitlist they joined on Monitor. For context, here is the page users saw when joining the waitlist:
<img width="679" alt="Screen Shot 2020-07-10 at 9 50 52 AM" src="https://user-images.githubusercontent.com/22355127/87168356-fb47f700-c293-11ea-84b2-7de668ae2723.png">

**Comment by groovecoder** [comment]
@lesleyjanenorton  also found this was the original CTA text on Monitor dashboards:

![image](https://user-images.githubusercontent.com/71928/87174439-c7250400-c29c-11ea-9d66-7ec959ce17f2.png)

**Comment by groovecoder** [comment]
> Oh! This sounds like an experiment. 🦊

More like a tinkering.

**Comment by tedschuh** [comment]
Making that CTA more strongly worded about keeping your email address out of the clutches of hackers and spammers and trackers might be more compelling.  Some might think this CTA refers to an email inbox management app.

**Comment by groovecoder** [comment]
Closing this, as we made improvements and will be using them in today's invite batch.
