### ISSUE TITLE
Improve A11Y of carousel on landing page.

### ISSUE THREAD

**Issue by lesleyjanenorton** [mozilla/fx-private-relay#549]
To improve the A11Y of the carousel on the landing page we should: 
1.) prevent image cycling if animations are disabled 
2.) add progress indicator below carousel images
3.) pause carousel on hover (of carousel image or progress indicator)
4.) progress to next image on click

**Comment by KatieCaldwell** [comment]
![image](https://user-images.githubusercontent.com/8239152/87359472-b7b3ee00-c51c-11ea-9ab5-90e675581682.png)
 5 bars centered under image: 24px below
Light Purple: #D9BFFF  (On state) Purple: #9059FF (Off state)
size of bar: 55px (wide) x 4px (tall)
spacing between bar: 8px

**Comment by Vinnl** [comment]
I don't think this carousel exists anymore, so closing this :)
