### ISSUE TITLE
Adding "catch all" subdomain addressing

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#55]
The premium Relay experience should include "domain addressing" where a user can register a subdomain of the Relay domain (e.g., groove.relay.com); emails sent to any address at the subdomain should Just Work™. Individual user stories (file issues for each as needed):

* As a free user on the Relay dashboard, I want to see an "Upgrade" button so I can upgrade to premium Relay to claim a domain.
* As a premium user on the Relay dashboard, I want to submit a form to register my alias domain.
   * Double-confirm since the user can't delete and can't buy another one. (Can we make them re-type the domain again?)
* As a premium user on the Relay dashboard, I want to see a warning that I can NOT change my alias domain later.
* As a premium user on the Relay dashboard, I want to see my domain aliases with stats and controls to disable or delete them.
* As a premium user of the Relay dashboard, I should be able to filter my email aliases to quickly find one.

**Comment by EMMLynch** [comment]
This work is already completed.
