### ISSUE TITLE
Consider adding a "Disable instead" UI in the Delete modal

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#554]
When a user looking at the delete modal decides they do NOT want to delete an address, we should provide an option to disable the address instead - so they can stop emails from it without losing it.

**Comment by tedschuh** [comment]
Consider as a future enhancement.

**Comment by EMMLynch** [comment]
Old issue / Closing - Relay has the ability to block all emails for each mask which can be used as a way to disable a mask.
