### ISSUE TITLE
utm_source = undefined on a few bento box links

### ISSUE THREAD

**Issue by tublitzed** [mozilla/fx-private-relay#562]
I just noticed that the `utm_source` param isn't getting set correctly for a few of these links (FX Desktop & Mobile).

![Screen Shot 2020-07-21 at 3 57 52 PM](https://user-images.githubusercontent.com/1756056/88100764-00962300-cb6b-11ea-9614-e0fa5af5df14.png)

**Comment by willdurand** [comment]
@groovecoder I came here to report the exact same bug, I see either `undefined` or `${referringSiteURL}` (on Windows). Maybe because the strings below are not template strings? https://github.com/mozilla/fx-private-relay/blob/bacc498019ae3c02476c421f3c5ee4c7d46cdb53/static/js/fx-bento.js#L5-L9

**Comment by groovecoder** [comment]
@Vinnl - hmm ... looks like this is also affecting the new React UI bento box, but the links are showing up as `utm_source=` (i.e., blank). Can you take a look?
