### ISSUE TITLE
Add ability to use custom username for relay email address

### ISSUE THREAD

**Issue by kanurag94** [mozilla/fx-private-relay#572]
Type: Enhancement Request

The current way relay handles email addresses is not very useful to someone like me. I would definitely choose a username that I can easily remember instead of ```lnsani122q9kl@relay.firefox.com```.

This can be optional though. The best scenario would be to allow editing username once a new alias is requested.

**Comment by groovecoder** [comment]
labeling, and follow-up question:

How would you like a [custom username as a subdomain for you addresses](https://github.com/mozilla/fx-private-relay/issues/55)? E.g., you might get kanurag94.firefox.com, and then you can make up any alias you want:

* facebook@kanurag94.firefox.com
* twitter@kanurag94.firefox.com
* google@kanurag94.firefox.com
* microsoft@kanurag94.firefox.com
* netflix@kanurag94.firefox.com
* amazon@kanurag94.firefox.com
* apple@kanurag94.firefox.com
etc.

**Comment by kanurag94** [comment]
Thanks! This is a good approach.
I haven't looked at the code, but can you please keep this subdomain independent of username/ or editable otherwise it would be pretty easy for someone to bruteforce common words (netflix, facebook) on my username and end up flagging my username as spam forever.

**Comment by jens1o** [comment]
> labeling, and follow-up question:
> 
> How would you like a [custom username as a subdomain for you addresses](https://github.com/mozilla/fx-private-relay/issues/55)? E.g., you might get kanurag94.firefox.com, and then you can make up any alias you want

Please make this optional, the point for many users (including me) to potentially use this service is to make my e-mail I use for login less guessable for attackers so they are not even close to use other techniques to get my password.

**Comment by tedschuh** [comment]
Consider as a future enhancement.

**Comment by groovecoder** [comment]
> > How would you like a [custom username as a subdomain for you addresses](https://github.com/mozilla/fx-private-relay/issues/55)? E.g., you might get kanurag94.firefox.com, and then you can make up any alias you want
> 
> Please make this optional, the point for many users (including me) to potentially use this service is to make my e-mail I use for login less guessable for attackers so they are not even close to use other techniques to get my password.

Yes, it should be optional for sure.

**Comment by groovecoder** [comment]
Closing in favor of #55.
