### ISSUE TITLE
Service not much use with only 5 aliases permitted

### ISSUE THREAD

**Issue by madb1lly** [mozilla/fx-private-relay#573]
Hello,

I was very excited to be able to use Firefox Relay to manage all my signins and signups for various websites. In particular, I was going to start transitioning my existing logins over to Firefox Relay addresses. However, with a limit of 5 aliases the service is not really much use, sadly. I have 234 logins saved in Lockwise (I know that some will be duplicates) and there are goodness knows how many other times I've had to give my email address to sign up for something that doesn't require a password (therefore not recorded in Lockwise), so a limit of 5 is really not much use.

I will still use and test the service and the addon, but its utility is severely crippled by this limit.

Cheers 🙂

**Comment by jeroen7s** [comment]
I'm assuming this is just for the Beta and this limit will be lifted once it releases. Possibly limited amount of aliases for free with a paid option for unlimited.

**Comment by groovecoder** [comment]
Yes, the 5-alias limit is definitely an aspect of the closed and limited Beta. We are absolutely looking for the best way to offer unlimited aliases.

**Comment by pocketdrummer** [comment]
This is one of 3 issues blocking me from using this full-time. I definitely want to support Firefox any way I can, but right now AnonAddy seems like a better product specifically for these three reasons:
- Ability to create custom aliases without even needing to use an extension. Ex. Just enter spamsite@username.anonaddy.com creates the alias for that site, and I know where the email came from.
- Unlimited aliases created in that manner.
- Ability to reply to emails sent to any of those aliases. Granted, Anonaddy's method is a bit of a pain in this regard. This could be an area where Firefox Rely could come out on top.

**Comment by ro-savage** [comment]
Just adding to the view. I usually just use my email +<randomstring>@gmail.com for every sign up. And then block certain emails when they come through. This gives me unlimited emails (but anyone smart could just remove +<string> and have my real email).

Certainly needs unlimited emails to be useful, so each email address sign up is unique.

**Comment by madb1lly** [comment]
Hi @ro-savage,

Yes I use this plus-addressing method at the moment as well. It's not ideal, because as you say it's easy to remove the plus address part and easy to track the main ID, but it's still better than nothing. Subdomain addresses like AnonAddy provide (thanks foe the tip @pocketdrummer!) are much better, but still trackable. Totally anonymous addresses like Firefox Relay (and AnonAddy and others provide for a fee) are the best, but these have the highest chance of being blocked or not accepted by some websites.

Cheers 🙂

**Comment by tedschuh** [comment]
Address the limit on email aliases before GA.
