### ISSUE TITLE
How can I disable the icon on a text input?

### ISSUE THREAD

**Issue by timwis** [mozilla/fx-private-relay#591]
Is it possible to disable the injection of the icon on text inputs? It can really get in the way on some sites, and I'd much rather just interact with it from the extensions panel - personally, it feels a bit intrusive.

**Comment by groovecoder** [comment]
There's a setting in the add-on to disable the icon:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/71928/89782396-d2a55e00-dada-11ea-9d95-07c9ef46fa5b.png">

**Comment by timwis** [comment]
Not sure how I missed that! Thanks :)
