### ISSUE TITLE
Keep SocketLabs as an alternative to AWS SNS

### ISSUE THREAD

**Issue by btoueg** [mozilla/fx-private-relay#594]
I'm considering self-hosting `fx-private-relay` and SocketLabs is a nice alternative to AWS SNS in terms of ease of install (especially since instructions are not updated with SNS)

I had to revert  https://github.com/mozilla/fx-private-relay/pull/566 to have it work locally.

Great project by the way! Are contributions welcome yet?

**Comment by groovecoder** [comment]
Thanks for the heads-up. I'm going to close this, but I encourage you to make a fork of the repo from the last commit before we remove SocketLabs.

I'd like to keep the code to a minimum of 3rd-party library dependencies, and we've already got some others that we haven't removed yet. :/
