### ISSUE TITLE
Add messaging that Relay does not support emails > 150K

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#596]
At least one user has lost an important attachment thru Relay already. They didn't know Relay stripped attachments until they got their first email.

We should add messaging up front so that more users know that Relay does not support attachments or emails larger than 150K, until we finish https://github.com/mozilla/fx-private-relay/issues/498.

**Comment by groovecoder** [comment]
As we're finishing https://github.com/mozilla/fx-private-relay/pull/613, I updated this issue to show a message that we don't support emails > 150K.

**Comment by say-yawn** [comment]
Feel free to assign this to me if @lesleyjanenorton is busy.
Seems like some additional a/c are:
- [ ] when attachment is delivered, we include a line in an header about supporting only up to 150KB email size
- [ ] updating the FAQ about attachment support and relaying email only up to 150KB (bigger than this will get lost)
- [ ] updating the information when hovering over the "Forwarded" text on the dashboard.
