### ISSUE TITLE
Add BCC and CC information when relaying emails

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#600]
# About this Issue
Currently if a relay address gets an email with BCC or CC information, these information are dropped. We may want to support this especially when we allow users to respond using the Relay address.

**Comment by tedschuh** [comment]
Do we have an idea of how many of the emails so far have had BCC or CC addresses?

Setting to P2 for now - I don't think we need this for Open Beta - maybe for GA.

**Comment by groovecoder** [comment]
Closing this as it could leak identifier to un-intended recipients.
