### ISSUE TITLE
[Context Menu] Manage All Aliases option doesn't work when clicking on it 

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/fx-private-relay#603]
**Affected versions**
* Fx79

**Affected platforms**
* Windows 10 x64
* macOS 10.15
* Ubuntu 18.04 x64

**Prerequisites**
* Firefox is opened.
* Have the Private Relay add-on version 1.4.4 installed.
* The user has no remaining aliases to use.

**Steps to reproduce**
1. Access https://www.facebook.com/ or any website that has a sign up form.
2. Right click on the "Email of Phone Number" field.
3. From the context menu choose "Generate new alias" option.
4. Click on the "Manage All Aliases" option from the pop-up.

**Expected result**
* The user is redirected to the Firefox Relay Home page.

**Actual result**
* Nothing happens.

**Additional notes**
* please observe the attached screencast

![sdfds](https://user-images.githubusercontent.com/43886441/89984922-d96ed500-dc82-11ea-87ab-d6700b71b29d.gif)

**Comment by EMMLynch** [comment]
Please reopen if this is still needed.
