### ISSUE TITLE
[Context Menu] Private Relay pop-up is duplicated when there are no remaining aliases 

### ISSUE THREAD

**Issue by GeorgiuCiprian** [mozilla/fx-private-relay#604]
**Affected versions**
* Fx79

**Affected platforms**
* Windows 10 x64
* macOS 10.15

**Prerequisites**
* Firefox is opened.
* Have the Private Relay add-on version 1.4.4 installed.
* The user is logged with a @mozilla.com account into Firefox Relay website.
* The user has no remaining aliases to use.

**Steps to reproduce**
1. Access this [website](https://login.norton.com/sso/idp/SAML2?SAMLRequest=nZFfa8IwFMW%2FSsm7TeyUSagFcQwEhaEbjL2UkF41rM11ubf%2B%2Bfar1TkfhA0fk5yb8zvnpqOa134OXzUQR%2Fuq9KT3VAzFmnmjpdztdvHuIcawkolSXfk%2Bmy7sGiojLmL3t7jjPLHxFkQ0Iaph0h55KBKVqI4adLrJq3rUqq%2B7g1glPdXvdT9E9NQwOW%2FYoT95UGNS4sr52GNg9LHFShKhdMVGLkazaSKiZwwW2lRDsTQltZ4vhsht4XIzIoJw%2FHeMnuoKwgLC1ll4m09%2FnarDtc2kAM%2BOD3JkLdaeJbmVd75zkpzrGIo6eI2GHGlvKiDNVh%2FBdBIrvQnIaLEUWdrWEP4zZH5QRXYPWCpPVll6XjIUbTlNcIY9R2OsNiY4OlYMe2O5gbsWjMsGYA7LO1FvbotMVebNQN4UsnQlSHSFzY21QJQzfkJDfYshS%2BXNENlZfn7MvgE%3D&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=QwCCwWH1IYX4t9T4L2LowQRZUSFG6QnnIWdKiAAiW%2BsTtjdIe0nFV1OPruY79dinh2ZZ0mRMg9fvE%2Bfr62Y7uvt6ztKp8RyT4m0dsAbSttbp7TeJN3qeW3mLBu72otJe%2FimD2L%2F0vd19j7xe5SeHvSDAkqoLyyrfD01xPehVXfxnZfnIpRkErxkdOXahpQ%2FjHWMV5EZ6GyT5m%2BDq0Mrs0qa2yU5j1Ge9T4TfTkCpiphSbiDq6tRlxqMlnuVdpWZLneJE3N9q4wXgxN5j0s0xX%2Fp0jJNIXD%2BnnFEDAHt9cU7WwyBLDkmVvS2Sv42kqIk%2FHaHsaW9HhPyi7OT7EzQdDg%3D%3D&displang=eng&displocale=USAA).
2. Right click on the "Email address" field.
3. From the context menu choose "Generate new alias" option.

**Expected result**
* The Firefox Relay pop-up is displayed only once.

**Actual result**
* The Firefox Relay pop-up is displayed twice.

**Additional notes**
* please observe the attached screencast

![double trouble](https://user-images.githubusercontent.com/43886441/89985489-d4f6ec00-dc83-11ea-91c4-b5ae26f25dbf.gif)

**Comment by EMMLynch** [comment]
Please reopen if this is still needed.
