### ISSUE TITLE
With White Contrast Theme the buttons are not higlighted while clicking on them

### ISSUE THREAD

**Issue by obotisan** [mozilla/fx-private-relay#615]
**Affected versions**
* Fx79

**Affected platforms**
* Windows 10 x64

**Prerequisites**
* White High Contrast Theme is activated. 
* Firefox is opened.
* Have the Private Relay add-on version 1.4.4 installed.
* The user is logged with a @mozilla.com account into Firefox Relay stage server https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/

* The user has an already created alias.

**Steps to reproduce**
* Click on any of the buttons from the page

**Expected result**
* The buttons are highlighted.

**Actual result**
* The buttons are not higlighted at all.

**Additional notes**
* please observe the attached screenshot:
![no highlight](https://user-images.githubusercontent.com/42799381/90109750-efe56100-dd54-11ea-99ca-eb6a9aa82639.gif)

**Comment by andreipurice** [comment]
This is affected also when having a dark theme or any custom one while in High Contrast mode.
![high contrast](https://user-images.githubusercontent.com/67056974/90136824-71e98000-dd7d-11ea-8948-7a9c1989f0fa.gif)

**Comment by EMMLynch** [comment]
Old / Closing - Please reopen if this is still needed.
