### ISSUE TITLE
With White Contrast Theme the checkmark is not visible while trying to delete an entry

### ISSUE THREAD

**Issue by obotisan** [mozilla/fx-private-relay#616]
**Affected versions**
* Fx79

**Affected platforms**
* Windows 10 x64

**Prerequisites**
* White High Contrast Theme is activated. 
* Firefox is opened.
* Have the Private Relay add-on version 1.4.4 installed.
* The user is logged with a @mozilla.com account into Firefox Relay stage server https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/

* The user has an already created alias.

**Steps to reproduce**
* Click on any of the "Delete" button from one of the entries. 
* Check the box for "Yes, I want to delete this alias".

**Expected result**
* The checkmark is visible.

**Actual result**
* The checkmark is not visible.

**Additional notes**
* please observe the attached screenshot:
![no highlight](https://user-images.githubusercontent.com/42799381/90109750-efe56100-dd54-11ea-99ca-eb6a9aa82639.gif)

**Comment by EMMLynch** [comment]
Old / Closing - Please reopen if this is still needed.
