### ISSUE TITLE
Norton Password Manager tooltip notification isn't correctly displayed while using Firefox Relay add-on

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#618]
### Affected versions

Firefox 79.0
Private Relay add-on version 1.4.4 - updated on August 13, 2020

### Affected platforms

Windows 10
Ubuntu 18.04
Mac OS 10.14

### Steps to reproduce

1. Launch the latest Firefox
2. Install the Private Relay add-on
3. Install Norton password manager
4. Go to https://my.1password.com/signin and observe the tooltip notification.

### Expected behavior

Norton Password Manager tooltip notification should be correctly displayed while using Firefox Relay add-on.

### Actual behavior

Norton Password Manager tooltip notification isn't correctly displayed while using Firefox Relay add-on.
https://imgur.com/a/2vg799c

**Comment by EMMLynch** [comment]
Old / Closing - Please reopen if this is still needed.
