### ISSUE TITLE
Support 8-bit Content-Transfer-Encoding

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#655]
# About this Issue
Related to this add-on [review](https://addons.mozilla.org/en-US/firefox/addon/private-relay/reviews/1585861/), when we get an email with 8-bit as the Content Transfer Encoding the `message_from_string` does not properly handle the encoding. This may be related to bug filed on Python [here](https://bugs.python.org/issue41307). 

# STR
## Check that email **relayed** from https://nextgame.net/ contains broken encoding on the email body
1. Go to https://nextgame.net/ and create an account with a Relay address(create account [link](https://nextgame.net/auth/registration/?register=yes&backurl=/auth/))
2. Check that you get an email relayed via Relay with broken body that looks like:
```
\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd NextGame
------------------------------------------

\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd nextgame.net \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd.

\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd:
ID \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd: 311456

\ufffd\ufffd\ufffd: \ufffd\ufffd\ufffd
\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd: \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd
E-Mail: <your relay address>
\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd: <some Russian number you used>

\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd \ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd.
```

## Check that email from https://nextgame.net/ has Content Transfer Encoding set to 8-bit
1. Go to https://nextgame.net/ and create an account with a normal email address like mailinator (create account [link](https://nextgame.net/auth/registration/?register=yes&backurl=/auth/))
2. Check that you get an email relayed via Relay with email body that looks like:
```
Информационное сообщение сайта NextGame
------------------------------------------
 отслеживание,



Ваша регистрационная информация:

ID пользователя: <user id>
Login: <email address you used>
Пароль: <your plain text password for this account>

Для смены пароля перейдите по следующей ссылке:
http://nextgame.net/bitrix/admin/index.php?change_password=yes&lang=ru&USER_CHECKWORD=<sensitive info here>

Сообщение сгенерировано автоматически.
```
3. Check the email headers has the following:
```
Content-Type: text/plain
Content-Transfer-Encoding: 8bit
```

# Potential Fix/Technical implementation
Instead of using `message_from_string` [here](https://github.com/mozilla/fx-private-relay/pull/639/commits/44cb293438011c207c5a13afcf1b0efd75ad2002) we should consider using [message_from_bytes](https://docs.python.org/3/library/email.parser.html#email.message_from_bytes). When relaying the message to the user's actual email address we should use `send_raw_email` instead of `send_email` as mentioned in https://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html:

> Amazon SES allows you to specify 8-bit Content-Transfer-Encoding for MIME message parts. However, if Amazon SES has to modify the contents of your message (for example, if you use open and click tracking), 8-bit content isn't preserved. For this reason, we highly recommend that you encode all content that isn't 7-bit ASCII. For more information, see MIME Encoding in the Amazon SES Developer Guide. 

Sample MIME text used to test theory (found in aforementioned [Python bug](https://bugs.python.org/issue41307)):
```
"""\
Mime-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
 
ä
"""
```
If you use `message_from_string` and call `as_bytes()` on it, you will get the following error:
```
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 4: ordinal not in range(128)
```
Comparing the `as_string()` for:
`message_from_string`
```
'Mime-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\n\nä\n'
```
`message_from_bytes` with string encoded(?) (str-> bytes) with UTF-8
```
'Mime-Version: 1.0\nContent-Type: text/plain; charset="utf-8"\nContent-Transfer-Encoding: base64\n\nw6QK\n'
```
Note the slight different on `charset` and change in the `Content-Transfer-Encoding` from `8bit` to `base64` when using `message_from_bytes`

#
Related to https://github.com/mozilla/fx-private-relay/issues/523

**Comment by say-yawn** [comment]
Another add-on review with similar problem https://addons.mozilla.org/en-US/firefox/addon/private-relay/reviews/1586646/

**Comment by sv-hyacoub** [comment]
Special characters are not correctly displayed in email body section when sending emails from thunderbird to gmail via Firefox Relay

### Steps to reproduce
1. Open Thunderbird.
2. Write a new message and introduce special characters in "From", "Subject" and "Body" sections. (Sören/ שִׂין/ يتحدّث)
3. Send it to your Firefox Relay email. 

![Screenshot 2020-09-02 at 15 17 02](https://user-images.githubusercontent.com/15101135/91990623-a1672900-ed3a-11ea-92b8-5b8e5f2d7a61.png)

**Comment by Makishima** [comment]
This bug affects a lot of users from CIS :) Can we await some hotfix?

**Comment by FunkyLoiso** [comment]
Having problem with cyrillic email body too: [eml.zip](https://github.com/mozilla/fx-private-relay/files/5295190/eml.zip)

**Comment by say-yawn** [comment]
@Makishima sorry to hear that. Can you clarify what CIS stand for? Also is there an email client you used to test this issue? I am working on this and trying to replicate the issue without spamming NextGame 😅 

@FunkyLoiso I make it a habit to not open `zip` files. Can you provide the email body as a .txt instead?

**Comment by FunkyLoiso** [comment]
> Can you provide the email body as a .txt instead?
Here you go: [Добро пожаловать на конференцию «Форум сантехников, о сантехнике».eml.txt](https://github.com/mozilla/fx-private-relay/files/5302355/eml.txt)

CIS stands for "Commonwealth of Independent States", it's basically post-soviet countries.

**Comment by say-yawn** [comment]
@FunkyLoiso, @Makishima this should be fixed now.

**Comment by michaljenicek** [comment]
I had the same issue with Czech characters not showing correctly and can confirm that it works now ([thread on bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1671363)).

**Comment by FunkyLoiso** [comment]
> 
> 
> @FunkyLoiso, @Makishima this should be fixed now. Can you confirm?

Checked with one web site, it works now, thank you.
