### ISSUE TITLE
Update the name of the _get_attachment_metrics function

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#662]
Can we update the name of the function, since it's also returning the attachment itself, which is then returned further for `_sns_message` to use.

_Originally posted by @groovecoder in https://github.com/mozilla/fx-private-relay/pull/613#r474884520_

**Comment by groovecoder** [comment]
Whoa, the text "fix #662" in the description of #663 was enough to automatically close this on merge? Nice!

**Comment by say-yawn** [comment]
I added Fix #<issue> on the commit message and that probably close this issue :D
