### ISSUE TITLE
Mail ceased forwarding

### ISSUE THREAD

**Issue by Strid3r2442** [mozilla/fx-private-relay#666]
All was working perfectly fine, but I noticed that today, the "Forwarded" counter was correctly increasing, however, none of them are arriving in my inbox.

I have tried:
External site -> Relay -> ProtonMail
ProtonMail -> Relay -> ProtonMail

Direct emails are being received, so ProtonMail servers seem to be working. Which leaves either ProtonMail have decided to block Firefox Relay, there is an issue on Firefox Relay's end or perhaps something going on with my DMARC (I'm not too knowledgable about DMARC settings, so that is just a guess. I have my DMARC set to quarantine though, so if it was this, I'd expect it to be sent to spam, which it is not)

**Comment by pdehaan** [comment]
Possibly related #671

**Comment by Donnnno** [comment]
Same problem here :/ (also ProtonMail user)

**Comment by Talw3g** [comment]
Same problem, using ProtonMail too...

**Comment by groovecoder** [comment]
This should be fixed now!

**Comment by Donnnno** [comment]
Thanks!
