### ISSUE TITLE
Relay stopped forwarding emails

### ISSUE THREAD

**Issue by rywiese** [mozilla/fx-private-relay#678]
I haven't been receiving any emails sent via my aliases for almost a week now. I was getting several emails per day, and then they just stopped. I can see in the "Manage" menu that the numbers are going up, but I do not receive them. I tried manually sending myself an email from another address to each of my relay aliases. None went through. The address that is being relayed to is with protonmail.com. Missing emails do not show up in spam.

**Comment by rywiese** [comment]
Similar to [this issue](https://github.com/mozilla/fx-private-relay/issues/666#issue-697928911) posted by another ProtonMail user. I have reported the bug with ProtonMail as well.

**Comment by rywiese** [comment]
Is there a way to change which address the relay forwards to? This would help debug the issue, and would allow me to start receiving emails again.

**Comment by Strid3r2442** [comment]
> 
> 
> Is there a way to change which address the relay forwards to? This would help debug the issue, and would allow me to start receiving emails again.

Updating the primary email address of your Firefox account will forward Relay emails to that address

**Comment by proxy-sh** [comment]
he same thing happens to me but they don't resend, it doesn't increase the counter and when it does I don't get the emails (I use protonmail)

**Comment by comfytoday** [comment]
Same issue here, protonmail.
Counter increases, mails don't arrive in protonmail account. Spam or otherwise.
I've tried different aliases, including a new one, and old ones that were previously working.

**Comment by groovecoder** [comment]
Could be related to: https://github.com/mozilla/fx-private-relay/issues/683

**Comment by groovecoder** [comment]
This should be fixed now!
