### ISSUE TITLE
Automated testing suite for web compat issues

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#679]
# About this Issue
We have several web compatibility issues--[here](https://github.com/mozilla/fx-private-relay/issues?q=is%3Aopen+is%3Aissue+label%3A%22website+compat+bug%22+label%3A%22%F0%9F%A7%A9+addon%22) and [here](https://github.com/mozilla/fx-private-relay/issues?q=is%3Aopen+is%3Aissue+label%3Aaddon-compat-bug)--that we could test using integration test suite.

**Comment by birdsarah** [comment]
@davehunt wondering if you have any opinions on puppetteer vs browsertime vs diy selenium. We're looking to build out a test suite that runs integration tests that checks the performance of an addon.

**Comment by groovecoder** [comment]
If this could also go to webmail clients to actually walk thru sending/receiving email thru Relay that would be 👨‍🍳 💋 .

**Comment by birdsarah** [comment]
> If this could also go to webmail clients to actually walk thru sending/receiving email thru Relay that would be 👨‍🍳 💋 .

I think integration testing the Relay interface should be a separate issue. It's a much easier problem to solve.

**Comment by pdehaan** [comment]
> If this could also go to webmail clients to actually walk thru sending/receiving email thru Relay that would be 👨‍🍳 💋 .

Or as Gmail likes to say "boy", "frying pan with egg", "lips emoji".

![_mozilla_fx-private-relay__Automated_testing_suite_for_web_compat_issues___679__-_peterdehaan_gmail_com_-_Gmail](https://user-images.githubusercontent.com/557895/93823864-62304780-fc17-11ea-8c6d-5fa338549fdc.png)

**Comment by davehunt** [comment]
> @davehunt wondering if you have any opinions on puppetteer vs browsertime vs diy selenium. We're looking to build out a test suite that runs integration tests that checks the performance of an addon.

It's been a while since I did any web UI integration testing, but I'd probably still start with a Selenium client. Browsertime is a performance testing tool based on Selenium. If you require any features of Puppeteer then it makes sense to go in that direction, but I do expect these to be adopted by Selenium in the future via the [WebDriver BiDi spec](https://w3c.github.io/webdriver-bidi/).

**Comment by EMMLynch** [comment]
Old / Closing
