### ISSUE TITLE
Mail delivery problem | 'From' header not respecting RFC5322

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#683]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1665441#c0 ...

---

User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0

Steps to reproduce:

Sent an email to a relay address. For example sent an email from testNDM1ZmE2@gmail.com to ugfv8obfd@relay.firefox.com, that should be forwarded to cyril.schreven@protonmail.com

Actual results:

The mails sent by Firefox relay was not properly delivered.
The reason for this is that the headers were not successfully parsed at reception. More specifically the 'From' header does not contain the quotes as defined by the rfc:
"""
From: john NDM1ZmE2 <testNDM1ZmE2@gmail.com> [via Relay] <noreply@relay.firefox.com>
"""

Expected results:

The 'From' header should include the quotes and be:
"""
From: "john NDM1ZmE2 <testNDM1ZmE2@gmail.com> [via Relay]" <noreply@relay.firefox.com>
"""
The correct format is specified in rfc5322, see for example Appendix A.1.2

**Comment by pdehaan** [comment]
I wonder if this is related to #678 (seemingly all ProtonMail users as well). Possibly related to recent utf-8 From handling work?

**Comment by schreven** [comment]
Thanks for moving it here. The issue likely started the 11th of september.

**Comment by schreven** [comment]
Looked further into it and found this is discussed more precisely at <https://tools.ietf.org/html/rfc2047#section-5>.
The From header sent by the relay always contains `[` `]` `<` and `>` in its display name. For this reason I believe it should indeed be a quoted-string, before it gets encoded.

Before the support-utf8-in-headers commit, the quotes would always get added by [this piece of code](https://github.com/python/cpython/blob/3.8/Lib/email/headerregistry.py#L96).

I wrote a commit on a fork that might be along the line of what you want to do, [here](https://github.com/schreven/fx-private-relay/commit/4ef190d32ae9e10f014884894d6278e8bc9a2fa5).

**Comment by groovecoder** [comment]
Your patch seems like a good one. Would you like to submit a pull request for it?

**Comment by schreven** [comment]
All right I submitted one

**Comment by say-yawn** [comment]
Related to #685

**Comment by groovecoder** [comment]
This should be fixed now!
