### ISSUE TITLE
Emails aren't forwarding to Protonmail

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#685]
### Affected versions
Firefox 80.0.1

### Affected platforms
Windows 10
Mac OS X 10.15

### Steps to reproduce:
1. Launch Firefox.
2. Create an alias using Protonmail.
3. Send an email to the alias created before.

### Expected behavior
Emails should be forwarded to Protonmail.

### Actual behavior
Emails aren't forwarding to Protonmail.
In "accounts/profile/" emails are increased by 1 in "Forwarded" or "Blocked" section.

**Comment by groovecoder** [comment]
This should be fixed now!

**Comment by sv-hyacoub** [comment]
I confirm that this issue isn't reproducible anymore.
