### ISSUE TITLE
Mails with the same subject are grouped in the same email thread 

### ISSUE THREAD

**Issue by sbadau** [mozilla/fx-private-relay#686]
**Affected versions**
Firefox 80.0.1
Firefox Private Relay 1.4.5

**Affected platforms**
Windows 10

**Pre-requisites**
3 different email accounts are needed (Gmail1, ProtonMail, Yahoo)
1 Firefox relay account linked to a Gmail2 account is needed 

**Steps to reproduce**:
1. Launch Firefox.
2. Sing into Firefox Relay using Gmail2 account
3. Create an alias
4.  Log into ProtonMail and send a mail to the alias (from step 3) with the subject: "test 3"
5. Log in to YahooMail and send a mail to the alias with the subject "test 3"
6. Log in to the Gmail1 and send a mail to the alias with the subject "test 3"
7. Check the Gmail2 inbox.

**Expected behavior**
3 new mails forwarded from the same alias should be found in the Gmail2 Inbox.

**Actual behavior**
All 3 mails forwarded from the same alias are grouped in the same thread with the Subject "test 3", even if the mails were sent from 3 different email accounts.

![2020-09-22_15h32_17](https://user-images.githubusercontent.com/56026823/93884143-32527400-fceb-11ea-9ae8-8781dfb6d38b.png)

**Comment by groovecoder** [comment]
Have noticed this too, but it's a per-email-client behavior that we can't change.
