### ISSUE TITLE
Find a different way to display actual From

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#690]
# About this Issue
As see in [this comment](https://github.com/mozilla/fx-private-relay/pull/689#issuecomment-698582813) the use of `<>` is duplicated to indicate the from email address. As a result, on Protonmail, the display name does not include where the email was sent from--as opposed to Relay was relaying/forwarding.

Expected - actual from is displayed on the display name of the email using `<>`:
<img width="850" alt="Screen Shot 2020-09-24 at 3 48 42 PM" src="https://user-images.githubusercontent.com/25109943/94200600-454a7d00-fe80-11ea-898f-39959ffb7711.png">

Problem - use of `<>` in the Display name is overwritten by Protonmail client to indicate the From address:
<img width="642" alt="Screen Shot 2020-09-24 at 3 48 53 PM" src="https://user-images.githubusercontent.com/25109943/94200620-4d0a2180-fe80-11ea-8216-dc73d3c3938b.png">

**Comment by say-yawn** [comment]
`<>` is actually an SMTP email address format as mentioned in this [Microsoft doc link](https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/smtp-addresses).

**Comment by say-yawn** [comment]
I also wonder to prepare for the possibility/functionality for replying to the email while still using the alias, if we should think of a better way to present/store the actual From address.

**Comment by groovecoder** [comment]
We could potentially change the characters from `<` `>` to some other characters like `{` and `}`, or we could add the original sending address to the email template header.

**Comment by Ender-events** [comment]
Do you have any update on this issue ?
The proton webmail only display `replies@relay.firefox.com`

Here an example of how simplelogin fix this issue
![image](https://user-images.githubusercontent.com/7770119/212490044-36ff8f45-308d-4c09-8569-b3f78d4c6a19.png)

**Comment by EMMLynch** [comment]
Old / Closing - Please reopen if this is still needed.
