### ISSUE TITLE
Inline images are not displayed

### ISSUE THREAD

**Issue by sv-hyacoub** [mozilla/fx-private-relay#691]
### Affected versions
Firefox 81.0

### Affected platforms
Windows 10
Mac OS X 10.15

### Steps to reproduce:
1. Launch Firefox.
2. Send an inline image to your Firefox relay address from yahoo/gmail/proton/aol/thunderbird/outlook.
3. Observe the email.

### Expected behavior
Emails should be received with the inline image correctly displayed.

### Actual behavior
Results might vary:
- Emails are empty
- filename.png is displayed in the body of the email without the inline image
- preview icon with filename.jpeg
![Screenshot 2020-09-25 at 12 56 35](https://user-images.githubusercontent.com/15101135/94254152-07f0f880-ff2f-11ea-89c3-ef629922c215.png)

**Comment by groovecoder** [comment]
How did you include the image in the email? Did you paste an image into the email? Or add it as an attachment?

**Comment by omniproc** [comment]
Same

**Comment by jwhitlock** [comment]
This is now fixed. Inline images are retained for forwarded emails.
