### ISSUE TITLE
Malware attachments sent from ProtonMail or to ProtonMail aliases increments profile dashboard

### ISSUE THREAD

**Issue by sbadau** [mozilla/fx-private-relay#692]
**Affected versions**
Firefox 81
Firefox Private Relay 1.4.5

**Affected platforms**
Windows 10

**Steps to reproduce**:
1. Launch Firefox.
2. Sing into Firefox Relay and create an alias
3. Navigate to ProtonMail and send a mail with a malware attachment to the previously created alias.

**Expected behavior**
The mail and the malware attachment should not be forwarded to the relay alias and the profile dashboard should not be incremented.  

**Actual behavior**
The mail and the malware attachment are not forwarded on the relay alias but the profile dashboard is incremented with 1.
I reproduced this issue with the following email clients: Yahoo, Gmail, AOL, ProtonMail, Outlook, and Thunderbird in the following combinations:
- from ProtonMail email client to Yahoo, Gmail, AOL, ProtonMail, Outlook, and Thunderbird aliases.
- from Yahoo, Gmail, AOL, ProtonMail, Outlook, and Thunderbird email clients to ProtonMail aliases. 
The malware attachments used to reproduce this issue are the files from https://www.eicar.org/?page_id=3950

**Comment by EMMLynch** [comment]
Old / Closing - Please reopen if this is still needed.
