### ISSUE TITLE
Private Relay home page is ambigous on sign-in sign-up

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#693]
# About this Issue
As mentioned by @birdsarah currently the page only has `sign in` which can confuse the user to expecting that they must have an account with Relay before they can access Relay.

**Comment by say-yawn** [comment]
Linked In has option to "Join now" and "Sign in"
<img width="1064" alt="Screen Shot 2020-09-28 at 12 44 54 PM" src="https://user-images.githubusercontent.com/25109943/94467476-a7f58e80-0188-11eb-8bba-0df837d94755.png">

Meanwhile Relay only has "Sign in"
<img width="1064" alt="Screen Shot 2020-09-28 at 12 45 04 PM" src="https://user-images.githubusercontent.com/25109943/94467483-aaf07f00-0188-11eb-803e-f7a3b45be6b2.png">

**Comment by pdehaan** [comment]
Had to search Google Image cache for this, but Send had a "Sign in/up" button.

![](https://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/wp-content/uploads/2019/03/Firefox-Send-Blog-Post-ONE-1.png)

**Comment by groovecoder** [comment]
Let's do "Join now" and "Sign in" buttons - they can both do the same thing.

**Comment by AOiegas** [comment]
Confirming there is is a Sign Up and a Sign In button displayed, both redirecting the user to the authentication flow.
![image](https://user-images.githubusercontent.com/85748693/129528440-74120a11-cf02-4fb1-9021-fd5da73b226c.png)
