### ISSUE TITLE
Better contrast between + and Generate New Alias button background

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fx-private-relay#697]
The black `+` color against the background color is difficult to see.

![Firefox_Relay](https://user-images.githubusercontent.com/557895/94592291-c9648200-023d-11eb-90c8-aee41c118168.png)

![Firefox_Relay](https://user-images.githubusercontent.com/557895/94594937-f82f2800-023e-11eb-8fdc-fd0ef2a11582.png)

https://relay.firefox.com/static/images/plus-sign.svg

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"><path fill="#20123a" d="M14 7H9V2a1 1 0 00-2 0v5H2a1 1 0 100 2h5v5a1 1 0 002 0V9h5a1 1 0 000-2z"/></svg>
```

Looks like the SVG icon might only be used in that one place.

```sh
git grep -n plus-sign.svg

static/css/style.css:774:  background-image: url("/static/images/plus-sign.svg");
```

**Comment by malqinneh** [comment]
@lesleyjanenorton are you able to change the SVG to white (via SVG code)? I would recommend that as a quick fix here.

**Comment by pdehaan** [comment]
While editing the SVG, I noticed we also seem to have a https://github.com/mozilla/fx-private-relay/blob/master/static/images/plus-sign-white.svg file which is the same as "plus-sign.svg" although I don't think the *-white.svg version is used anywhere.

I can modify my PR to use the existing [and currently orphaned] plus-sign-white.svg file instead.

**Comment by malqinneh** [comment]
> I can modify my PR to use the existing [and currently orphaned] plus-sign-white.svg file instead.

Sounds good, thank you @pdehaan
