### ISSUE TITLE
Update version of web-ext

### ISSUE THREAD

**Issue by birdsarah** [mozilla/fx-private-relay#698]
By my understanding, web-ext is specified as greater than 3.2.1 in the package.json but for whatever reason it would only install that version rather than the latest.

3.2.1 didn't work for me similar to https://github.com/mozilla/web-ext/issues/1937.

Propose upping min version to latest 5.1.0

(I'll take this PR)

**Comment by pdehaan** [comment]
> but for whatever reason it would only install that version rather than the latest.

https://github.com/mozilla/fx-private-relay/blob/bd7b1c8af392400515f4550103bec4bde4929f67/extension/package.json#L6-L8

Note that the version number in extension/package.json starts with a [`^`](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) which means it will install anything greater than or equal to 3.2.0 **but _less than_ 4.0.0**.
Looking at the handy [npm semver calculator](https://semver.npmjs.com/) and setting the package name to "web-ext" and range of `^3`, we can see that there were no newer 3.x versions before jumping to 4.0.0 and it looks like the current version of 5.1.0. Or, you can verify the available versions via the command line using <kbd>npm info web-ext versions</kbd>:

```js
[
  '0.0.1', '1.0.0', '1.0.1',  '1.1.0',
  '1.2.0', '1.2.1', '1.2.2',  '1.2.3',
  '1.2.4', '1.3.0', '1.4.0',  '1.5.0',
  '1.6.0', '1.7.0', '1.8.0',  '1.8.1',
  '1.9.0', '1.9.1', '1.10.0', '1.10.1',
  '2.0.0', '2.1.0', '2.2.0',  '2.2.1',
  '2.2.2', '2.3.0', '2.3.1',  '2.3.2',
  '2.4.0', '2.5.0', '2.6.0',  '2.7.0',
  '2.8.0', '2.9.0', '2.9.1',  '2.9.2',
  '2.9.3', '3.0.0', '3.1.0',  '3.1.1',
  '3.2.0', '3.2.1', '4.0.0',  '4.1.0',
  '4.2.0', '4.3.0', '5.0.0',  '5.1.0'
]
```

**Comment by birdsarah** [comment]
Thank you @pdehaan I should really take the time to understand package.json properly.
