### ISSUE TITLE
Autofill existing relay addresses.

### ISSUE THREAD

**Issue by ewlsh** [mozilla/fx-private-relay#714]
In addition to creating new relay addresses, I'd like the extension to also offer to fill existing addresses. This is particularly beneficial when you've recently created a relay address on the site (or during account creation).

**Comment by groovecoder** [comment]
Dupe of #263 . Please upvote and comment there, as it's already in our project board.

**Comment by ewlsh** [comment]
This is slightly different. If there **isn't** a relay for the site, I'd like the extension to offer to autofill other existing addresses.

Where this is relevant:
- You created an address during Relay signup or from the Relay homepage
- You have exhausted your 5 email addresses and want to reuse one

**Comment by ewlsh** [comment]
@groovecoder
