### ISSUE TITLE
Ability to nickname relays

### ISSUE THREAD

**Issue by OddHouseGames** [mozilla/fx-private-relay#730]
Having 5 relays should include ability to nickname relays, especially to help keep everything organized when information gets breached and accounts need to be updated with a different relay.

**Comment by groovecoder** [comment]
There should be an edit icon next to the domain of the relay address ... if you click that you can edit the label of the alias.

<img width="226" alt="image" src="https://user-images.githubusercontent.com/71928/98575975-7d1a5200-227f-11eb-8a06-934b2940d010.png">

**Comment by Githubuxer** [comment]
Where are you seeing that option?![image](https://user-images.githubusercontent.com/62911518/98590016-2d964f00-229c-11eb-8259-7c974f4f49ec.jpeg)

**Comment by lolrepeatlol** [comment]
Yeah, I'm not seeing that here.

**Comment by m-p-3** [comment]
@groovecoder that option is only there if you have the Firefox Relay add-on installed, and it seems to be saved locally. If I disable the add-on, the labels goes away.
