### ISSUE TITLE
Provide grouping feature for Relay alias

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#731]
# About this Issue
According to this review https://addons.mozilla.org/en-US/firefox/addon/private-relay/reviews/1619766/ we see behavior of users grouping their Relay aliases for a specific purpose. Consider having a UX/UI where a user can click on button to auto-group the Relay aliases but ensure that the user is generating a new alias every time (we discourage re-using an alias).

# Concerns
Currently we see users grouping their alias. We want to understand why the users are doing this and if the user no longer has a limit will that change their behavior? Perhaps using the buttons that helps grouping so users who have a limit can simply get existing alias returned while users without the limit can get new alias created under the grouping will help?

**Comment by EMMLynch** [comment]
Not planned at this time.
