### ISSUE TITLE
Add posibility to blok (or allow) emails by regex or at least host and addres metch

### ISSUE THREAD

**Issue by elcepi** [mozilla/fx-private-relay#733]
I'm getting constantly contact by the same website (they are using different address) add a way to block emails by the from field.

**Comment by Githubuxer** [comment]
Can't you just setup a rule for incoming Mail using your email provider? Not sure that it falls on Mozilla's responsibilities.

**Comment by elcepi** [comment]
You mean on the client side, sure I can. But I'm having problems hen understanding what is the purpose of this product.

**Comment by Githubuxer** [comment]
The purpose is that it improves personal security by not having to provide your actual email address to third parties who may suffer data breaches or sell data to third parties.

**Comment by elcepi** [comment]
OK my bad ... I thought the product have to do with spam ...
