### ISSUE TITLE
How do I stop relay from forwarding messages from a website to me

### ISSUE THREAD

**Issue by LiamDun** [mozilla/fx-private-relay#746]
So I signed up to this website and it started getting spammy, how do I make firefox relay stop forwarding messages from that website to me?

**Comment by groovecoder** [comment]
There's a "forwarding" toggle at the upper-right of each email alias in your relay dashboard. You can switch that to "blocking"

![image](https://user-images.githubusercontent.com/71928/101390244-20af5000-3888-11eb-9e0b-cc0e30b44614.png)
