### ISSUE TITLE
deleted_user_objects log causing bigquery export errors

### ISSUE THREAD

**Issue by oremj** [mozilla/fx-private-relay#750]
The following code is causing bigquery export errors, because it's an array that contains two different data types. The first element of the array is a number, the second is a dictionary.

https://github.com/mozilla/fx-private-relay/blob/60e5d9191056140f8e39f5e2802691be3b39518d/privaterelay/views.py#L233-L236

Can we change this to output two elements of the same type or change the whole dataset to a dictionary?

![image](https://user-images.githubusercontent.com/45590/101388420-c5c02d80-3874-11eb-9da5-335a54b7127c.png)

**Comment by Micheletto** [comment]
Note this is still a problem: ```The following log sink in a project you own had errors while exporting logs. Due to this error, logs are not being exported to the sink destination. ```

**Comment by Micheletto** [comment]
How can I help raise the priority of this issue?
