### ISSUE TITLE
Not possibility to name mail alias

### ISSUE THREAD

**Issue by EdorianDark** [mozilla/fx-private-relay#755]
In the website https://relay.firefox.com/accounts/profile/ I clicked on "Generate new Alias"
Afterwards a new alias is added, but I have no idea how to remember for what I used the alias.
![grafik](https://user-images.githubusercontent.com/5777938/102766894-1c525f00-437f-11eb-942a-976fe2aeb4fa.png)
I would expect there to be a field in which I can add a note, where I want to use it.
Preferably this would already be asked while creating an alias.

**Comment by EdorianDark** [comment]
See also #660 for the same issue with the addon

**Comment by SublimeDeer** [comment]
This has been added. On my screen I can see my relay address and over that I can put in a little note to help me remember where I've inserted the address.

**Comment by EdorianDark** [comment]
Only if the Addon is installed.
Furthermore the notes are not synchronized, so if you use two Computers the notes are completely useless.

**Comment by SublimeDeer** [comment]
> 
> 
> Only if the Addon is installed.
> Furthermore the notes are not synchronized, so if you use two Computers the notes are completely useless.

Just type in those notes again. We've all only got four relays so far so typing in those notes again ain't that much of a job, hehe.

**Comment by EdorianDark** [comment]
Closing the issue, as it is now possible to name aliases
