### ISSUE TITLE
Setting "Show Relay icon in email fields on websites" does not toggle

### ISSUE THREAD

**Issue by bershanskiy** [mozilla/fx-private-relay#772]
## Repro steps

1. Install extension
2. Open extension's pop-up (click on extension icon)
3. Open "settings menu" by clicking "cog" icon in the top right corner
4. Click on toggle "Show Relay icon in email fields on websites"

## Expected result

The toggle changes state (goes from "ON" to "OFF")

## Actual result

Nothing happens. The toggle just gets a highlight, but does not change state.

Note that a similar toggle called "Allow Mozilla to collect interaction data" on the same page works fine.

**Comment by groovecoder** [comment]
Working on this now.

**Comment by bershanskiy** [comment]
@groovecoder Thanks for the fix! I built extension locally and can confirm that it behaves as expected now.
