### ISSUE TITLE
Bug: KeyError 'Subject' in /emails/sns-inbound

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#779]
Now that SNS is sending bounces (and complaints?) to our /emails/sns-inbound endpoint, we're seeing these errors:

https://sentry.prod.mozaws.net/operations/fx-private-relay-prod/issues/10500508/?query=is%3Aunresolved

I believe this particular issues is caused by `Complaint` objects coming at our endpoint that we're not handling.

**Comment by jwhitlock** [comment]
With PR #2345, we are now handling complaints by logging them. I see no instances of a KeyError for Subject in the new Sentry instance.
