### ISSUE TITLE
Add CODE_OF_CONDUCT and CONTRIBUTING files?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fx-private-relay#782]
Per https://pdehaan.github.io/repo-lint-www/repo/mozilla/fx-private-relay/

Looks like we're missing a CODE_OF_CONDUCT.md file and a CONTRIBUTING.md file.

Can probably copy-pasta from https://github.com/mozilla/blurts-server/blob/main/CODE_OF_CONDUCT.md and https://github.com/mozilla/blurts-server/blob/main/docs/CONTRIBUTING.md.

**Comment by EMMLynch** [comment]
Added both files
