### ISSUE TITLE
When a user deletes an address, hard bounce it and prevent future users from getting the same address

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#79]
When a user deletes an address, we still need to:

* [x] Prevent any future addresses from using the same localpart
* [ ] Hard-bounce any messages sent to the address

To do this AND still delete our record of the plaintext email address:

1. [x] Insert the deleted address into a new `emails.deleted_addresses` table
2. [x] Delete the address from the `emails.relay_address` table
3. [ ] Hard bounce all emails sent to unknown addresses
   * Call [`CreateReceiptRule`](https://docs.aws.amazon.com/ses/latest/APIReference/API_CreateReceiptRule.html) with `BounceAction` for the recipient.

**Comment by groovecoder** [comment]
SocketLabs may not have an API to bounce emails sent to unknown/deleted addresses.

Amazon SES has a [CreateReceiptRule API](https://docs.aws.amazon.com/ses/latest/APIReference/API_CreateReceiptRule.html) so we could create bounce rules for addresses that are deleted.

**Comment by EMMLynch** [comment]
Please reopen if this is still needed.
