### ISSUE TITLE
Add Permissions-Policy: interest-cohort=()

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#807]
See https://web.dev/floc/?s=03#do-websites-have-to-participate-and-share-information

**Comment by groovecoder** [comment]
test comment to trigger email.

**Comment by groovecoder** [comment]
real next comment to trigger email.

**Comment by groovecoder** [comment]
another comment to trigger a blocked email.

**Comment by EMMLynch** [comment]
Please reopen with additional details if this is still needed.
