### ISSUE TITLE
Remove Adjust Link within Bento menu

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/fx-private-relay#818]
Per https://github.com/mozilla/bedrock/issues/8309#issuecomment-819324507, these links should be replaced. 

https://github.com/mozilla/fx-private-relay/blob/15d8db336310640ff4a6df1bd9c19d5eef3ad926/static/js/fx-bento.js#L6

**Comment by EMMLynch** [comment]
Old / Closing - Please reopen if this is still needed.
