### ISSUE TITLE
Change message banner to non-alert color

### ISSUE THREAD

**Issue by say-yawn** [mozilla/fx-private-relay#829]
# About this Issue 
After #827, while the errors are being displayed properly, non-errors are being displayed like errors (successful login/logout). We should change the banner color such that the non-errors and errors alike can be displayed to the users.
<img width="1246" alt="Screen Shot 2021-05-11 at 10 38 47" src="https://user-images.githubusercontent.com/25109943/117873278-35dc4080-b265-11eb-8be2-a193aab8b87c.png">

# Acceptance Criteria
- [ ] Errors are displayed properly
- [ ] Messages are displayed properly (are not displayed like they may be errors)

**Comment by groovecoder** [comment]
Should we consider https://github.com/mozilla/fx-private-relay/issues/126 fixed with this too?
