### ISSUE TITLE
Unlimited email aliases

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#830]
The premium Relay experience should include unlimited email aliases.

* [ ] Mock-ups
   * [Post-purchase dashboard with alias search, sort, and filter UI](https://www.figma.com/file/jp318GsWGaR3RALWNqv7cp/Prospector-MVP-Workflows?node-id=520%3A2987)
* [ ] Implementation
* [ ] QA
* [ ] l10n
* [ ] Support

#### User Stories
* As a non-user of Relay ... ??
* As a free user on the Relay dashboard, I should be able to "Upgrade" to purchase a premium subscription, so I can create unlimited email aliases
   * Top of dashboard
   * "0 remaining aliases" UI
   * Disabled "Generate New Alias" button
* As a premium user of the Relay dashboard, I should be able to create as many aliases as I want.
* As a premium user of the Relay dashboard, I should be able to search/filter/sort my email aliases to quickly find one. Search/filter/sort by:
   * alias label
   * enabled/disabled
   * "made last week"
   * most-used/least-used
* As a free user of the Relay add-on, I should see an "Upgrade" link to purchase a premium subscription, so I can create unlimited email aliases
* As a premium user of the Relay add-on, I should be able to create as many aliases as I want.
* As a premium user of the Relay add-on, I should be able to filter my email aliases to quickly find one.

**Comment by EMMLynch** [comment]
Completed / Closing
