### ISSUE TITLE
Regression: FXA Relying Party event handler doesn't update email address

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#835]
STR:

1. Go to https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/
2. In the account menu, click "Manage your account" to go to https://accounts.stage.mozaws.net/settings
3. Use https://accounts.stage.mozaws.net/settings#profile to change primary email address (may need to add a secondary and then make the secondary into the primary)
4. Go back to https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/

Expected results:
Page should say "Welcome, `<new primary email address>`"

Actual results:
Page still says "Welcome, `<old primary email address>`"

**Comment by say-yawn** [comment]
@groovecoder Was this a problem on prod and/or can we work on this after the 1.2.3 (domain address, redis, the package update) release?

**Comment by wagnerand** [comment]
I am facing this issue on prod and analyzed it with @groovecoder which lead to the creation of this issue.

**Comment by say-yawn** [comment]
Thanks for elaborating @wagnerand, did the problem get solved by a workaround? I tried to reproduce this issue on Prod and was unable to. I followed the steps above and I was able to change the primary email on Prod. Maybe I should try changing it from FXA first (instead of logging into Relay then going to FXA account setting?).

**Comment by say-yawn** [comment]
I think some possible solutions to issue above are:
- Check/compare FxA profile information and update during login
- Add uniqueness of email address (possible places: Django's User, Email's Profile)
- If first option for refreshing user information from FxA is not good enough create a job to fetch latest profile information from FxA and update our information

**Comment by wagnerand** [comment]
Any updates on this?

**Comment by groovecoder** [comment]
Howdy. Were you able to get your account fixed up? Can we close this?
