### ISSUE TITLE
Start new Privacy "Pack" dashboard page

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#836]
We will re-use the Relay code-base to build and host the Privacy Pack.

The Pack UI will live at a single url: e.g., privacy.mozilla.org. Individual products (VPN, Monitor, Relay) will link users to privacy.mozilla.org, which will serve as a marketing landing page for the Pack and links to FXA subscription to buy the Pack. After purchase, the user will land back on privacy.mozilla.org with an updated dashboard to start using all the products.

1. Add [django-hosts](https://github.com/jazzband/django-hosts) to the code-base and set a rule to serve a new view & template at the new host: privacy.mozilla.org.
2. Add new FXA OAuth Client for privacy.mozilla.org
   * Note: we will need to have multiple django-allauth social apps in the system, and we will need to use the proper one (i.e., Relay or PMO) in the code
3. When a FXA signed-in user comes from VPN, Monitor, or Relay, we should be able to use prompt=none auth to automatically register them in the Pack
4. For non-FXA users, we should be able to send them thru FXA account creation as normal

**Comment by EMMLynch** [comment]
Old / Closing - Please reopen if this is still needed.
