### ISSUE TITLE
Update hidden/modal string calls to be lazy

### ISSUE THREAD

**Issue by maxxcrawford** [mozilla/fx-private-relay#842]
_Originally posted by @flodolo in https://github.com/mozilla/fx-private-relay/pull/815#discussion_r639050796_

For any strings that are not visible to the user (example: delete confirmation modal), these strings should be called lazily. 

https://django-ftl.readthedocs.io/en/latest/usage.html#lazy-translations

**Comment by EMMLynch** [comment]
Please reopen with additional details if this is still needed.
