### ISSUE TITLE
Bug: "Manage your Domain aliases" appears when `settings.PREMIUM_ENABLED` is `False`.

### ISSUE THREAD

**Issue by groovecoder** [mozilla/fx-private-relay#843]
STR:

1. Set `settings.PREMIUM_ENABLED=True` in `.env`
2. Purchase premium product thru regular flow
3. Set `settings.PREMIUM_ENABLED=False` in `.env`
4. Go to dashboard

Expected results:
All of the UI for unlimited and domain aliases should go away.

Actual results:
Still see "Manage your domain aliases" at the bottom of the dashboard.

**Comment by EMMLynch** [comment]
Completed / Closing
