### ISSUE TITLE
“Get the extension for Firefox” banner still displayed with the extension installed

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#861]
#### Platforms affected::
- Windows 10, Linux Ubuntu 18.04, MacOS;

#### Browsers tested on:
- Firefox;

#### Prerequisites:
- Have the Production Firefox Relay extension installed in your browser - https://addons.mozilla.org/en-US/firefox/addon/private-relay/;

#### Steps to reproduce:
1. Access the https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ page;
2. Sign in with a FxA account;
3. Observe the banners beneath the page header;

#### Expected result:
- There shouldn’t be any banner about installing the extension;

#### Actual result:
- There is a banner that suggests the user to install the extension even though you have it installed;

#### Notes:
- N/A;

![image](https://user-images.githubusercontent.com/85748693/121696508-d035db00-cad4-11eb-843f-7b75675e0b9b.png)

**Comment by groovecoder** [comment]
Note: The production add-on from addons.mozilla.org only affects the relay.firefox.com site. To make the banner go away on the https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ page, you need to run with the dev build of the add-on.
