### ISSUE TITLE
The alias where the messages are forwarded is not displayed in the Delete alias modal text

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#862]
**Build:**
Dev

**Affected platforms:**
Windows 10 64-bit
macOS 10.15

**Browsers tested on:**
Firefox

**Preconditions:**
The user is logged in to Firefox Relay.
The user has already added some aliases.

**Steps to reproduce:**

1. Select an alias and click the “Show Details” option.
2. Click “Delete” button.
3. Observe the text displayed in the modal.

**Actual result:** 
The alias where the messages are forwarded is missing from the text.

**Expected result:** 
The alias where the messages are forwarded is displayed in the text.

![alias missing](https://user-images.githubusercontent.com/79697848/121699494-a8944200-cad7-11eb-844e-9a4e69cbff19.PNG)

**Comment by maxxcrawford** [comment]
May be related to #863

**Comment by Bianca-O** [comment]
@maxxcrawford @groovecoder Verified this issue on Stage under Windows 10 64-bit and macOS. The real email address is displayed in the Delete dialog. Shouldn't the alias be displayed instead?

**Comment by groovecoder** [comment]
Thanks for the catch. Re-opening.

**Comment by Bianca-O** [comment]
Verified this issue on Stage under Windows 10 64-bit and macOS. I confirm that the alias is displayed in the Delete dialog.

![new situation](https://user-images.githubusercontent.com/79697848/126129538-d08f73d3-cf10-435b-b9f0-a54cd2df8d04.PNG)
