### ISSUE TITLE
The “Your domain name is:” section looks incorrect  

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#863]
#### Platforms affected:
- Windows 10, Linux Ubuntu 18.04, MacOS 10.15;

#### Browsers tested on:
- Firefox;

#### Prerequisites:
- Be signed in into a Firefox Relay account;
- Have a paid subscription for it;

#### Steps to reproduce:
1. Go to https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/;
2. In the Domain section of the page, in the “Search your new domain” field enter any domain name;
3. Click on the “Get it” button;
4. Observe the Domain section of the page;

#### Expected result:
- There should be a correct display of your new domain name;

#### Actual result:
- The Domain section looks incorrect;

#### Notes:
- N/A;
![image](https://user-images.githubusercontent.com/85748693/121699762-e2fddf00-cad7-11eb-96ce-d0ef9dcd1615.png)

**Comment by maxxcrawford** [comment]
Figma screenshot: 

<img width="320" alt="image" src="https://user-images.githubusercontent.com/2692333/121949874-9ce68c80-cd1e-11eb-8f00-828dc2ef2f80.png">

This entire element should be removed and the top header should be updated instead.

**Comment by AOiegas** [comment]
Verified the issue on Windows 10 and Android 9 while using the latest Firefox version.
The domain name banner does not appear anymore after creating a domain name, and the page’s header contains the related information, displayed accordingly.
