### ISSUE TITLE
Display error for the product icon in the “Set up your subscription page”

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#864]
#### Platforms affected:
- Windows 10, Linux Ubuntu 18.04, MacOS 10.15;

#### Browsers tested on:
- Firefox;

#### Prerequisites
- Be signed in into a Firefox Relay account;
- Don’t have a paid subscription for the Relay;

#### Steps to reproduce:
1. Go to https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/;
2. Click on the “Upgrade to Mozilla Privacy Pack now!” link;
3. Go through the authentication to the “Set up your subscription” page;
4. Observe the icon of the Mozilla Privacy Pack in the right side of the page; 

#### Expected result:
- The displayed icon is the correct one;

#### Actual result:
- The icon is missing, displaying only a blank black square, and it has layout issues sitting on top of text;

#### Notes:
- N/A;
![image](https://user-images.githubusercontent.com/85748693/121700023-29533e00-cad8-11eb-9dd4-c3a1e1af5f73.png)

**Comment by maxxcrawford** [comment]
@say-yawn This will require subplat work, I think?

**Comment by groovecoder** [comment]
To fix this, we need to upload the privacy pack icon image to https://github.com/mozilla/fxa/tree/main/assets/product-icons, and then update the product in stripe to use the image URL from the results FXA CDN, which is allowed by the subplat CSP.

**Comment by maxxcrawford** [comment]
Submitted this today – https://github.com/mozilla/fxa/pull/8884

**Comment by groovecoder** [comment]
@AOiegas - FXA deployed their latest assets, so this should be ready to re-test now.

**Comment by AOiegas** [comment]
Looking good.
Verified on Windows 10 and Android 9 while using the latest version of Firefox.
The "Set up your subscription page" displays an icon with no layout issues.
![image](https://user-images.githubusercontent.com/85748693/123048837-8370cf00-d407-11eb-842e-43a94f5cd177.png)
