### ISSUE TITLE
The font or size and the layout of the text in the FAQ page differs between the Staging version and the released version

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#865]
#### Platforms affected:
- Windows 10, Linux Ubuntu 18.04, MacOS 10.15;

#### Browsers tested on:
- Firefox;

#### Prerequisites:
- N/A

#### Steps to reproduce:
1. Go to https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/faq;
2. In a different tab open https://relay.firefox.com/faq;
3. Cycle between the two tabs and compare the text layout and;

#### Expected result:
- The text in the pages should be identical;

#### Actual result:
- There are differences in the size or font and layout between the two versions;

#### Notes:
- A very random find. Should there be this change?;

![image](https://user-images.githubusercontent.com/85748693/121700944-15f4a280-cad9-11eb-8eeb-d93731d695e7.png)
![image](https://user-images.githubusercontent.com/85748693/121701039-2dcc2680-cad9-11eb-97fe-d5a26296ed15.png)

**Comment by EMMLynch** [comment]
Old / Closing - Please reopen if this is still needed.
