### ISSUE TITLE
The banner section disappears after installing the dev version of the Relay addon

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#868]
#### Platforms affected::
- Windows 10, Linux Ubuntu 18.04, MacOS 10.15;

#### Browsers tested on:
- Firefox;

#### Prerequisites:
- A new firefox profile has been created;
- The user has a Private Relay account without the Mozilla Privacy Pack purchased;
- Have the test addon downloaded, but not installed;

#### Steps to reproduce:
1. Open firefox in the new profile;
2. Go to https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/;
3. Log into the created profile and check the banner section just below the page header;
4. Install the test addon that points to the fxa stage;
5. Refresh the Relay page and check the banner section again;

#### Expected result:
- The promotional banner should stay displayed;

#### Actual result:
- The promotional banner disappears;

#### Notes:
- Uninstalling the extension and refreshing does not change anything;

![image](https://user-images.githubusercontent.com/85748693/121701686-d37f9580-cad9-11eb-91f3-6eb7410a73f4.png)
![image](https://user-images.githubusercontent.com/85748693/121701741-e2fede80-cad9-11eb-8cb4-c8c0842ebb5c.png)

**Comment by AOiegas** [comment]
Repeating the same steps that are above, the banner section disappears, including the upgrade banner present in the top side of the page. Tested on both stage and dev versions.

**Comment by maxxcrawford** [comment]
@AOiegas So is the issue now that the upgrade banner should still be visible? Or is the empty space still visible?

**Comment by AOiegas** [comment]
So, to me it seems pretty natural that the upgrade banner should remain to a user that has not yet subscribed, because it seems to be the main visual thing that suggests the user to upgrade. But after installing the extension it disappears. This is the problem with the top upgrade banner, but the bottom one still remains.
![nosub1 1](https://user-images.githubusercontent.com/85748693/123213505-bf229c00-d4ce-11eb-970d-e51199a2c2f5.png)

![nosub1 2](https://user-images.githubusercontent.com/85748693/123213530-c47fe680-d4ce-11eb-8d6e-33184c360be7.png)
