### ISSUE TITLE
Number of created aliases is not displayed correctly in the addon window

### ISSUE THREAD

**Issue by madalincm** [mozilla/fx-private-relay#869]
#### Platforms affected::
- Windows 10, Linux Ubuntu 18.04, MacOS 10.15;

#### Browsers tested on:
- Firefox;

#### Prerequisites:
- FxA account with relay subscription;
- The Stage extension is installed;

#### Steps to reproduce:
1. Create more than 5 relay aliases;
2. Click on the Relay add-on icon from the top right corner;

#### Expected result:
- The menu should display “You have unlimited aliases” or the exact number of aliases created;

#### Actual result:
-A negative number is displayed . For example:  “You have -1 aliases remaining”;

![image](https://user-images.githubusercontent.com/15685441/121699874-00cb4400-cad8-11eb-8f13-4cd47397866e.png)

**Comment by maxxcrawford** [comment]
@madalincm This bug should be filed in https://github.com/mozilla/fx-private-relay-add-on. Moving now.
