### ISSUE TITLE
Forwarded emails tooltip has display issues

### ISSUE THREAD

**Issue by madalincm** [mozilla/fx-private-relay#870]
#### Platforms affected::
- Windows 10, Linux Ubuntu 18.04, MacOS 10.15;

#### Browsers tested on:
- Firefox;

#### Steps to reproduce:
1. Open the Relay page while being logged in: https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. Hover the "0 Forwarded" text of any of the created aliases;
3. Observe the tooltip that is displayed;

#### Expected result:
- There are no display issues;

#### Actual result:
- The tooltip appears cut at the bottom
![image](https://user-images.githubusercontent.com/15685441/121702911-f3638900-cada-11eb-8822-de748b95b935.png)

**Comment by Bianca-O** [comment]
This issue is verified as fixed on Stage under Windows 10 and macOS 10.14. The tooltip is correctly displayed. See new situation:

![new situation tooltip](https://user-images.githubusercontent.com/79697848/127306940-b3e2ddca-a46f-4079-a57c-91a8a30b310e.PNG)
