### ISSUE TITLE
Sign in/ Sign out successful message position could be improved

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#871]
**Build:**
Dev

**Affected platforms:**
Windows 10 64-bit
macOS 10.15

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/ and sign in using an existing account.
2. Observe the Sign in successful message position and the 'x' option.

**Actual result:** 
Sign in successful message is not centered.

**Expected result:** 
1. Sign in successful message is centered and the 'x' option is displayed next to it.
or
2. Sign in successful message is centered and the 'x' option is displayed in the far right side of the blue bar.

Note: Same issue for the Sign out successful message.

![sign in msg position](https://user-images.githubusercontent.com/79697848/121703047-1726cf00-cadb-11eb-8fcb-b326d6b6aa79.PNG)
![sign out msg position](https://user-images.githubusercontent.com/79697848/121703072-1db54680-cadb-11eb-9ff9-956b852e7dc3.PNG)

**Comment by maxxcrawford** [comment]
Screenshots from Figma for reference. 

![image](https://user-images.githubusercontent.com/2692333/121946856-fa78da00-cd1a-11eb-84a5-228d50fc9046.png)

![image](https://user-images.githubusercontent.com/2692333/121946895-05336f00-cd1b-11eb-9121-894066beb11a.png)

**Comment by Bianca-O** [comment]
This issue is verified as fixed on Stage under Windows 10 64-bit and iOS 14.6. I confirm that the successful/ unsuccessful message is centered and the 'x' option is displayed in the far right side of the message bar. See new situation:

![new situation - successful msg bar](https://user-images.githubusercontent.com/79697848/127278419-7352cf14-3cc8-4ded-a25a-767b0399481f.PNG)

![new situation error msg](https://user-images.githubusercontent.com/79697848/127278435-f5158325-1d51-4d94-97e3-8eed9dae58cc.PNG)
