### ISSUE TITLE
In some email fields aliases are not filled when are generated from the context menu

### ISSUE THREAD

**Issue by madalincm** [mozilla/fx-private-relay#873]
#### Platforms affected::
- Windows 10, Linux Ubuntu 18.04, MacOS 10.15;

#### Browsers tested on:
- Firefox;

#### Prerequisites:
- FxA account with relay subscription;
- The Stage extension is installed;

#### Steps to reproduce:
1. Open the relay page and observe the number of generated aliases;
2. Open any fxa sign in window;
3. Right click in the filed and click the Generate New Alias button;
4. Go back to the relay page and observe the number of generate alias;

#### Expected result:
- The alias is generated and filled in the email field;

#### Actual result:
- The alias was generated but it was not filled in the email field in the fxa sign in window;

![GIF](https://user-images.githubusercontent.com/15685441/121713349-6eca3800-cae5-11eb-9abc-94ce289bdac6.gif)

**Comment by groovecoder** [comment]
This looks like another instance using the stage add-on with the dev server?

If you use the dev add-on, make sure you always use dev.fxprivaterelay.nonprod.cloudops.mozgcp.net site.

If you use the stage add-on, make sure you always use stage.fxprivaterelay.nonprod.cloudops.mozgcp.net site.
