### ISSUE TITLE
Tapping on the “Upgrade Mozilla Privacy Pack now” displays a 500 error message

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#879]
#### Platforms affected:
- Android 9;

#### Browsers tested on:
- Firefox;

#### Prerequisites:
- The user has a Private Relay account without the Mozilla Privacy Pack purchased;
- Be signed in into a Firefox Relay account;

#### Steps to reproduce:
1. Go to https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/;
2. Scroll down to the banner section;
3. Tap on the “Upgrade to Mozilla Privacy Pack now!” link;
4. Observe the results;

#### Expected result:
- The purchase flow is displayed;

#### Actual result:
- The user gets a 500 error message;

#### Notes:
- It also seems to redirect outside of stage;

![upgrade](https://user-images.githubusercontent.com/85748693/122020465-77648c00-cdcd-11eb-8c5f-dd529b8719ec.JPEG)

**Comment by groovecoder** [comment]
Sorry again. We updated the dev environment but forgot an environment variable. Should be fixed now.
