### ISSUE TITLE
“Server Error (500)” is displayed when trying to sign in to the stage version of Firefox Relay

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#881]
#### Platforms affected:
- All platforms;

#### Browsers tested on:
- Firefox;

#### Prerequisites:
- N/A

#### Steps to reproduce:
1. Go to https://dev.fxprivaterelay.nonprod.cloudops.mozgcp.net/;
2. Click/tap on the “Sign In” button;
3. Observe the results;

#### Expected result:
- The user should be redirected to authentication flow;

#### Actual result:
- The user gets a “Server Error 500”;

#### Notes:
- N/A;

![image](https://user-images.githubusercontent.com/85748693/122022313-248bd400-cdcf-11eb-9cdb-b5adfb01c2ce.png)

**Comment by groovecoder** [comment]
Sorry, this should be fixed now. We plan to release to stage this week and for future releases so we won't be breaking the QA environment so much.

**Comment by AOiegas** [comment]
Verified this issue while using Windows 10 and Android 9 on Firefox browser.
The problem is no longer reproducing, the error does not show up anymore and the page loads correctly.
