### ISSUE TITLE
[Feature request] Allow to disable addon icon in input

### ISSUE THREAD

**Issue by pashtet04** [mozilla/fx-private-relay#892]
I'd prefer to disable icon at input text because it conflicts with one of another addon

![image](https://user-images.githubusercontent.com/8694425/122461292-d1c33f80-cfbb-11eb-8f28-c27a4b34e767.png)
![image](https://user-images.githubusercontent.com/8694425/122461368-ec95b400-cfbb-11eb-95af-15fef6d310cb.png)

**Comment by maxxcrawford** [comment]
@pashtet04 Hey there! This is possible to turn off the icon in the add-on settings. 

Click the gear icon in the top right of the add-on: 

<img width="396" alt="image" src="https://user-images.githubusercontent.com/2692333/123161320-e3ca3580-d434-11eb-8efd-0bf73124406e.png">

Then, toggle OFF the first setting: 

<img width="413" alt="image" src="https://user-images.githubusercontent.com/2692333/123161385-efb5f780-d434-11eb-83ca-3892c0e71eda.png">

That should turn off the icons in the input fields.

**Comment by maxxcrawford** [comment]
Quick note – I'm transferring this issue to add-on repo (https://github.com/mozilla/fx-private-relay-add-on/)
