### ISSUE TITLE
Add Mozilla VPN intro pricing banner to all Private Relay Pages

### ISSUE THREAD

**Issue by tcinotto** [mozilla/fx-private-relay#897]
Add the following banner to the top of all private relay pages, similar to https://github.com/mozilla/blurts-server/issues/2088 on monitor. 

We need to remove the banner on July 13th, ill create an issue for this. 

This banner should only go live in US, UK, CA, Singapore, New Zealand, and Malaysia in English only.

The banner should be dismissable.

UTM parameter: https://www.mozilla.org/products/vpn/?utm_source=private-relay&utm_medium=private-relay&utm_campaign=intro-pricing

**Comment by joaonunomota** [comment]
This can be closed, since the banners have been removed for https://github.com/mozilla/fx-private-relay/issues/898.

**Comment by jwhitlock** [comment]
Thanks @joaonunomota!
