### ISSUE TITLE
“Made by Mozilla” link redirects to the russian localization of the Mozilla page

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#901]
#### Platforms affected:
- Windows 10, Android 9;

#### Browsers tested on:
- Firefox, Chrome;

#### Prerequisites:
- N/A;

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/ ;
2. Click on the nine squares button in the top right side of the page, in the header;
3. Click on the “Made by Mozilla” link at the bottom of the opened menu;

#### Expected result:
- The user should be redirected to https://www.mozilla.org/en-US/?utm_campaign=bento&utm_medium=referral&utm_source=undefined ;

#### Actual result:
- The user is redirected to the russian version of the page ( https://www.mozilla.org/ru/?utm_campaign=bento&utm_medium=referral&utm_source=undefined );

#### Notes:
- Reproduced on 3 different machines/ not reproducing on two other machines;
- There is no VPN active;
- Reproduced in a private window and with a new Firefox browse profile as well; 

![mother russia](https://user-images.githubusercontent.com/85748693/123098145-81bfff00-d439-11eb-817e-5b3e177311d5.gif)

**Comment by groovecoder** [comment]
I think this must be a bug in bedrock? Our link goes to www.mozilla.org, so everything that happens after that is handled by @mozilla/bedrock-admin team?

**Comment by pmac** [comment]
I get the en-US page. Are your browser language settings set for Russian? The site relies on your `accept-language` header value to send you to the best translation of the page.

**Comment by pmac** [comment]
I see your notes about a new profile. I have no idea how that would happen.

**Comment by AOiegas** [comment]
> 
> 
> I get the en-US page. Are your browser language settings set for Russian? The site relies on your `accept-language` header value to send you to the best translation of the page.

I can confirm there is no option set to russian in the browser.

**Comment by alexgibson** [comment]
> I can confirm there is no option set to russian in the browser.

You can change your language preferences in Firefox by going to Preferences (about:preferences) - > Languages -> Choose.

The list you define there will dictate the web page locale mozilla.org will redirect you to.

**Comment by AOiegas** [comment]
Sorry if I wasn't clear enough. I made sure the language options for the browser were not set to russian in any instance. There is only English there.

**Comment by alexgibson** [comment]
> I made sure the language options for the browser were not set to russian in any instance. There is only English there.

In that case I can't really see how this would be a website issue. The site relies on whatever is in your browsers `accept-language` header, and if only English is in there then there must be something else up with your browser profile / configuration.
