### ISSUE TITLE
“Forwarded” text and the More details button are displayed outside the alias’s white background

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#917]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in with an existing account.
2. Add an alias and observe the “Forwarded” text and the More details button.

**Actual result:** 
“Forwarded” text and the More details button are displayed outside the alias’s white background.

**Expected result:** 
“Forwarded” text and the More details button are displayed on the alias’s white background.

![text displayed outside the white background](https://user-images.githubusercontent.com/79697848/126136708-82d844a9-7a7d-440d-8f21-c895fc2c7df1.PNG)

**Comment by codemist** [comment]
@maxxcrawford I think this is just because of the unusually long domain name for the stage version?

**Comment by Bianca-O** [comment]
This issue is verified as fixed on Stage under Windows 10 64-bit and macOS 10.14. I confirm that “Forwarded” text and the More details button are displayed correctly. See new situation:

![new situation](https://user-images.githubusercontent.com/79697848/127296498-e92eae5f-30c2-414d-8951-f809af5adda0.PNG)
