### ISSUE TITLE
“Manage your Firefox Account” link is not visible anymore when you hover over it

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#918]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in with an existing account.
2. Click on the Avatar icon in the upper right hand corner and then hover over the “Manage your Firefox Account” link.

**Actual result:**
“Manage your Firefox Account” link is not visible anymore when you hover over it.

**Expected result:** 
"Manage your Firefox Account” link is still visible when you hover over it.

![Manage account button hover issue](https://user-images.githubusercontent.com/79697848/126147521-05d1da49-b7b2-48c0-a799-f9132eab3bdd.gif)

**Comment by AOiegas** [comment]
Verified the issue on Windows 10, on the stage site. The "Manage your Firefox Account" link remains visible when hovering over it.
![manage verification](https://user-images.githubusercontent.com/85748693/127299427-348a7e48-d8e8-43c6-8dd4-74c5703004cd.gif)
