### ISSUE TITLE
Title “Get your email domain for your aliases” on the your domain card is barely visible

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#920]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Preconditions:**
The user has already upgraded to Mozilla Privacy Pack.
The user doesn’t have an email domain added yet.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in.
2. Observe the title on the your domain card.

**Actual result:**
The title is written with light grey color on white background and it is barely visible.

**Expected result:** 
The title is written with dark color and it is visible.

![email domain subtitle is not visible](https://user-images.githubusercontent.com/79697848/126166025-1131dee3-2274-40a8-908f-149820257101.gif)

**Comment by AOiegas** [comment]
Verified this issue on stage. The title of the Domain Name card is visible now.
![image](https://user-images.githubusercontent.com/85748693/128483209-c0f07a57-3d26-4a76-830a-54e06e03571d.png)
