### ISSUE TITLE
The blue message bar for Signed out is not fully visible on mobile

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#931]
**Build:**
Stage

**Affected platforms:**
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account.
2. Click on the avatar icon in the upper right corner and then sign out.
3. Observe the blue message bar.

**Actual result:**
The blue message bar is not fully visible.

**Expected result:** 
The blue message bar is fully visible.

![message bar not fully visible](https://user-images.githubusercontent.com/79697848/126305314-e10abd6f-2e52-4a9a-80a8-44f98195cb9b.PNG)

**Comment by codemist** [comment]
Related to https://github.com/mozilla/fx-private-relay/issues/871

**Comment by AOiegas** [comment]
Verified and closed in [#871](https://github.com/mozilla/fx-private-relay/issues/871).
