### ISSUE TITLE
When the alias search bar contains any typed character, a small x appears inside the search bar for no apparent reason

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#932]
#### Build:
- Stage;

#### Affected Platforms:
- Android 9;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Have a few aliases created;
- Have the stage version of the Relay Add-on installed;

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. Click on the “Add account name” bar above any created alias;
3. Type anything;
4. Observe the search bar;

#### Expected result:
- The search bar updates accordingly and has no display issues;

#### Actual result:
- The search bar updates accordingly but displays a small x;

#### Notes:
- Clicking on the small x activates the “X” button nearby, but it might be that actually it is the “X” button that gets clicked on;
- Clearing the search bar makes the little x disappear as well;

![1626702542148](https://user-images.githubusercontent.com/85748693/126308130-3414d3e5-e3ca-4f18-a1fc-a82bca9107ad.JPEG)
![1626702542123](https://user-images.githubusercontent.com/85748693/126308157-40092f71-1bb2-4aff-be5c-c6c14abb91db.JPEG)

**Comment by codemist** [comment]
@maxxcrawford I can't seem to replicate this issue on my desktop, but I do see the bug when I test on my Android 10. Not sure how to debug.

**Comment by codemist** [comment]
@maxxcrawford Is there a reason why the label class `.additional-notes` is disabled? I can't edit the label even why I disable the `display: none;` property

**Comment by AOiegas** [comment]
This issue seems to not reproduce anymore. Verified it on stage, on Android 9 and on Windows 10. There is no little "x" appearing anymore.
![image](https://user-images.githubusercontent.com/85748693/128681123-11a610e4-c268-48cb-8011-56ed49926202.png)
