### ISSUE TITLE
"x" button overlaps the text on the message bar on mobile

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#933]
**Build:**
Stage

**Affected platforms:**
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Preconditions:**
The user has upgraded to MPP.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account.
2. Leave the "Search your new domain" field empty and tap on "Get it" button.
3. Observe the red message displayed.

**Actual result:**
The "x" button overlaps the text.

**Expected result:** 
The "x" button doesn't overlap the text.

**Note:** 
Same issue for green successful message.

![red msg bar issue Android](https://user-images.githubusercontent.com/79697848/126307945-55593a55-1871-4800-9856-6b9e63d777a7.PNG)
![green msg bar issue iOS](https://user-images.githubusercontent.com/79697848/127290908-d9206cca-3b0c-43ef-8e25-997a7264f8ac.PNG)

**Comment by Vinnl** [comment]
I think this may have been fixed by https://github.com/mozilla/fx-private-relay/pull/1001?

**Comment by Bianca-O** [comment]
This issue is verified as fixed on stage under Android 11 and iOS 14.8. The "x" button doesn't overlap the message text anymore. For some messages the "x" button is not displayed anymore but there is another issue already created for this. Closing.
See new situation:

![new situation 2](https://user-images.githubusercontent.com/79697848/140339034-e4164e35-ca01-4642-8e13-e6b479977fe3.png)

![new situation 1](https://user-images.githubusercontent.com/79697848/140339022-6dcb285b-57dc-4b64-9a1b-890403b1084d.PNG)
