### ISSUE TITLE
Alignment issue when more aliases are added 

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#940]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account.
2. Generate a few aliases.
3. Observe the alignment of "Blocked" and "Forwarded".

**Actual result:**
Text is not correctly aligned.

**Expected result:** 
Text is correctly aligned.

![alignment issue](https://user-images.githubusercontent.com/79697848/126491546-574c1c17-ca44-4d23-acbb-a63747750ecf.PNG)

**Comment by codemist** [comment]
Seems related to #917

**Comment by codemist** [comment]
Addressing the issue #917 seems to have fixed this one. 

Preview:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/13066134/126714378-40e7b685-a847-488f-9ac5-8f72fca9f8e3.png">

cc: @maxxcrawford

**Comment by Bianca-O** [comment]
Indeed the issue seems to be fixed. Verified on Stage under Windows 10 64-bit and macOS 10.14. Closing the issue.

![new situation](https://user-images.githubusercontent.com/79697848/127297778-e902c608-baaa-4949-bfed-c6cc49b7433c.PNG)
