### ISSUE TITLE
Longer alias labels are cut off

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#942]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Have a few aliases created;
- Have the stage version of the Relay add-on installed;

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. Click on the “Add account name” bar above any created alias;
3. Write a long name;

#### Expected result:
- The label is displayed in its entirety;

#### Actual result:
- The label is cut off;

#### Notes:
- N/A;

![labelcut1 1](https://user-images.githubusercontent.com/85748693/126510902-0a9ec3fa-a7cb-4039-b1ef-1c1e72d17bfa.png)
![labelcut1 2](https://user-images.githubusercontent.com/85748693/126510910-7ce3adb6-efcd-4db7-977a-1aefbfae8d2c.png)
![labelcut1 3](https://user-images.githubusercontent.com/85748693/126510918-87d092cb-0130-4777-9674-53d02c437ee9.png)

**Comment by codemist** [comment]
@maxxcrawford Is there a reason why the label class `.additional-notes` is disabled? I can't edit the label even why I disable the `display: none;` property

**Comment by AOiegas** [comment]
Verified this issue on stage. Longer aliases are not cut off anymore.
To be noted:
- The alias name now has a maximum number of characters allowed.
- Issue [#996](https://github.com/mozilla/fx-private-relay/issues/996) has appeard.

![image](https://user-images.githubusercontent.com/85748693/128476433-df6e2617-5b10-4d90-a7a7-70c760f5cece.png)
