### ISSUE TITLE
Long email alias is displayed outside the "Delete" dialog

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#945]
**Build:**
Stage

**Affected platforms:**
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account.
2. Generate an alias.
3. Tap on "Details" arrow.
4. Tap on "Delete" button and observe the alias in the dialog.

**Actual result:**
The email alias is displayed outside the "Delete" dialog.

**Expected result:** 
The email alias is divided on several lines.

![longer alias issue](https://user-images.githubusercontent.com/79697848/126654789-bd316626-f0ac-42f2-b5fa-3526a6191c48.png)

**Comment by AOiegas** [comment]
Verified on Windows 10 and Android 9, stage version. The email alias fits well in the "Delete" dialog box.
![image](https://user-images.githubusercontent.com/85748693/127300187-8ea15828-9f56-4142-9a10-f90889d56329.png)
![aliaslong](https://user-images.githubusercontent.com/85748693/127300722-181c2e35-f500-4d4c-9b8d-2291b66ccec5.JPEG)
