### ISSUE TITLE
Long email address overlaps text on desktop and creates layout issues on mobile

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#949]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and create an account using a long email address.
2. Upgrade to Mozilla Privacy Pack.
3. Observe the username displayed after "Welcome" message.
4. Only for mobile - Zoom out the page.

**Actual result:**
The username overlaps the "Email aliases used" text.
On mobile there is a layout issue.

**Expected result:**
No overlapping. No layout issue.

**Desktop 1:**

![long alias text overlaps](https://user-images.githubusercontent.com/79697848/126765347-e65492c8-ebd5-4185-b91f-ea119d93a5bb.PNG)

**Desktop 2:**

![long alias text overlaps2](https://user-images.githubusercontent.com/79697848/126765353-cdeb7fbe-2b4b-48b2-a12a-c6c7a8a78044.PNG)
**Mobile:**

![mobile layout issue](https://user-images.githubusercontent.com/79697848/126767086-15b7f002-0fcb-4d13-a81b-120a0ff343b0.PNG)

**Comment by AOiegas** [comment]
Verified this issue on stage, on both Windows 10 and Android 9. The email address doesn't overlap text or create layout issues. When the address is long it is truncated without issue.
