### ISSUE TITLE
Not all info is visible when "Menu" is expanded on mobile/ Scroll issue

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#956]
**Build:**
Stage

**Affected platforms:**
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account.
2. Expand the "Menu".
3. Observe the info on the page.
4. Scroll down the page.

**Actual result:**
Not all information is visible when "Menu" is expanded. When you scroll down the page the info is visible but it is not fixed.

**Expected result:**
All information is visible when "Menu" is expanded or it is visible and fixed when scrolling down the page.

https://user-images.githubusercontent.com/79697848/126962269-1bb1742a-11ae-49b0-a44b-fd52ef56d972.mp4

**Comment by codemist** [comment]
@maxxcrawford Eduardo redesigned the drop down mobile menu to look like this:
![image](https://user-images.githubusercontent.com/13066134/127679059-b81922f9-6428-490f-a5eb-a764b5a1bcb5.png)

Should I still add the missing Sign up/Sign in links in the old version of the menu (quick fix for now), or create Jira ticket for the redesign?

**Comment by maxxcrawford** [comment]
@codemist We need to get with Eduardo – The "Bento" items need to remain in the Bento box for now. I would pick up part of this design – the white bg with the two links for now. 

We also need to confirm if the white menu seen here is only for premium users.

**Comment by AOiegas** [comment]
It seems this problem is still present, both on stage and dev.

https://user-images.githubusercontent.com/85748693/129526489-ecc452c2-b188-4655-a860-9bf9f9512385.mp4

**Comment by maxxcrawford** [comment]
@AOiegas  What other items should be visible? The only two links that should be in the menu when logged in is Home and FAQ. 

The [screenshot](https://github.com/mozilla/fx-private-relay/issues/956#issuecomment-889986219) from @codemist is not targeted for this issue.

**Comment by AOiegas** [comment]
I see, ok then. From Bianca's initial issue and from what followed I understood that the problem is the drop-down menu showing on top of the page and covering information while opened instead of letting the user scroll up and uncovering the said information. As in the above video, when the drop-down menu is opened it covers the welcome message.
