### ISSUE TITLE
"...email address" in the "Buy Mozilla Privacy Pack" banner could be changed to plural 

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#957]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Preconditions:**
The user hasn't upgraded to MPP.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account. 
2. Observe the "Buy Mozilla Privacy Pack" banner text.

**Actual result:**
Email address is at singular.

**Expected result:**
Email address is at plural.

![change to plural](https://user-images.githubusercontent.com/79697848/126974980-7ae9b992-30d1-4262-85ac-2463fdb0b7c3.PNG)

**Comment by AOiegas** [comment]
Verified this issue on stage, both on Windows 10 and Android 9. The error was corrected and it's looking good now.

![image](https://user-images.githubusercontent.com/85748693/128492293-ee742357-0013-4f76-9f57-3ec0d28478f6.png)
