### ISSUE TITLE
Domain name already taken error message disappears too fast

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#960]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10, Android 9;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Have an email domain name that is already taken noted down;

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. Type the email domain name from the prerequisites in the “Get your domain name” field and press enter;
3. Observe the results;

#### Expected result:
- The domain is not created and an error is displayed explaining the user that the domain name is already taken;

#### Actual result:
- The error message disappears too fast;

#### Notes:
- N/A;

![used domain](https://user-images.githubusercontent.com/85748693/126992892-f3a464a9-4e82-42b7-b4b6-32f1acebd2ba.gif)

**Comment by codemist** [comment]
Should be resolved in https://github.com/mozilla/fx-private-relay/pull/946

**Comment by AOiegas** [comment]
On dev it seems the problem is fixed, but it is still happening on stage. What has changed though, both on stage and dev, is that its space and the Firefox Relay dashboard are now white, and with the survey link being white as well you cannot see the link at all. Was this change in color intended?
![updating survey banner](https://user-images.githubusercontent.com/85748693/128525348-8a2ec4e6-dece-4d48-b8e2-9ab0ebbdd89f.gif)

**Comment by EMMLynch** [comment]
Marked as completed in Jira / Closing
