### ISSUE TITLE
Mozilla VPN promotional banner still displayed after closing it

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#963]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Launch Firefox with a new profile.
2. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account.
3. Close the Mozilla VPN promotion banner.
4. Click FAQ.
5. Observe that Mozilla VPN promotion banner is still displayed.

**Actual result:**
Mozilla VPN promotion banner is still displayed on FAQ page after closing it on Home page.

**Expected result:** 
Mozilla VPN promotion banner is not displayed anymore after closing it.

**Note:** 
If the user is logged out and the promotional banner is closed on Home page it is not displayed anymore on FAQ page.

![VPN banner still displayed](https://user-images.githubusercontent.com/79697848/127105957-20bc38c1-0989-4fd4-ac9e-b4953d27a2c8.gif)

**Comment by maxxcrawford** [comment]
I took it a step further – if a user dismisses it on home/FAQ and THEN logs in, the banner stays hidden. It's only when they dismiss from the signed-in dashboard. Weird. 

I experimented with adding `secure;` and `SameSite=None` attributes but no dice.
