### ISSUE TITLE
Long name typed in alias search bar overlaps the aliases number

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#965]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14
Android 11
iOS 14.6

**Preconditions:**
The user has a few aliases created.

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account.
2. Type a long name in the alias search bar.

**Actual result:**
The name overlaps the aliases number.

**Expected result:** 
The name does not overlap the aliases number.

![name overlaps aliases number](https://user-images.githubusercontent.com/79697848/127124647-30ab2527-9781-452f-b9f6-d0e081b281bc.PNG)

**Comment by AOiegas** [comment]
Verified this issue on stage, on Windows 10. The alias number is not overlapped anymore by long names typed in the search bar.
