### ISSUE TITLE
The border corners for error message bar are not rounded

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#971]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14
Android 11
iOS 14.6

**Preconditions:**
The user has an active MPP subscription.
No email domain added.

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/ and log in using an existing account.
2. In the "Search your new domain" field type a long email domain and click "Get it" to force an error message.
3. Observe the error message bar.

**Actual result:**
The corners of the message bar are not rounded.

**Expected result:** 
The corners of the message bar are rounded. 

![error msg bar](https://user-images.githubusercontent.com/79697848/127283763-d88339e1-80c4-43cb-976d-9e2b0c6d941b.PNG)

See **[Figma](https://www.figma.com/file/jp318GsWGaR3RALWNqv7cp/Prospector-MVP-Workflows?node-id=520%3A5030)** for reference:
![Figma](https://user-images.githubusercontent.com/79697848/127283970-1a8e5b50-ffd8-4862-af3f-9013a2df811f.PNG)

**Comment by AOiegas** [comment]
Verified this issue on stage, on both Windows 10 and Android 9. The error message bar appears in the correct shape.
To be noted: 
- The issue [#998](https://github.com/mozilla/fx-private-relay/issues/998) appeared;
- Comparing with the Figma references, there is a length of space missing from beneath the error message bar;
![image](https://user-images.githubusercontent.com/85748693/128512288-188b8aeb-a12f-41fa-8ef9-1080d1c9f2d6.png)
![image](https://user-images.githubusercontent.com/85748693/128513444-4bebce41-bb65-4b8b-a57a-62840d73e762.png)
