### ISSUE TITLE
Incorrect color for successful message bar 

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#972]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14
Android 11
iOS 14.6

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/ and log in using an existing account.
2. Observe the successful message bar color.

**Actual result:**
The color of the message bar is light green #3FE1B0.

**Expected result:** 
The color of the message bar is #00D053 - as per [Figma](https://www.figma.com/file/jp318GsWGaR3RALWNqv7cp/Prospector-MVP-Workflows?node-id=520%3A5470)

![successful msg bar](https://user-images.githubusercontent.com/79697848/127289653-e2474a19-b3a3-4f15-9b01-9e7346055f01.PNG)

**Comment by codemist** [comment]
@maxxcrawford Could we flag to QA that the Protocol / Nebula design system is yet to be added to Figma?

**Comment by maxxcrawford** [comment]
Yes. Closing this issue and marking as a `wontfix`.
