### ISSUE TITLE
“Add account name” field’s highlighting box is missing the top edge when selected

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#973]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account with an active subscription;
- Have a few aliases created;
- Have the stage version of the Relay add-on installed;

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. Click on the “Add account name” of a created alias;
3. Observe the results;

#### Expected result:
- The field is selected and is displayed correctly;

#### Actual result:
- The field is selected but its highlighting box misses the top edge;

#### Notes:
- N/A;
![image](https://user-images.githubusercontent.com/85748693/127303316-37dd6e62-1f07-4649-81d2-f66195c08271.png)

**Comment by codemist** [comment]
I noticed this issue, and addressed it in this PR: https://github.com/mozilla/fx-private-relay/pull/978

**Comment by codemist** [comment]
@AOiegas is this still an issue?

**Comment by AOiegas** [comment]
Somehow I missed this. No this is not a problem anymore. Verified it on stage and on Windows 10. The box is displayed without any issues.
