### ISSUE TITLE
"Get unlimited aliases" button text becomes white when changing tabs

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#974]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14 

**Browsers tested on:**
Firefox

**Preconditions:**
Relay extension is not installed.
No upgrade to MPP.

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account.
2. Click on “Get unlimited aliases” button and then go back to Firefox Relay tab.

**Actual result:**
The "Get unlimited aliases" text is written with white color and it is not that visible.

**Expected result:** 
The "Get unlimited aliases" text is written with blue color like before.

![Get unlimited aliases button text white](https://user-images.githubusercontent.com/79697848/127320086-9cd0931e-16d6-44e0-b490-dbd9f8e5ca8d.gif)

**Comment by maxxcrawford** [comment]
Nice find.

**Comment by codemist** [comment]
I can't seem to replicate this issue locally, the CTA gets disabled after 5 aliases.

**Comment by Bianca-O** [comment]
The issue is reproducible only on Stage environment. It cannot be reproduced on Production because like you said the button gets disabled.

**Comment by Vinnl** [comment]
@codemist I could reproduce this locally, hope you don't mind my picking it up: #1117.

**Comment by AOiegas** [comment]
Verified this as fixed on stage, Windows 10. The "Get unlimited aliases" button's text does not change colors after clicking on it.
