### ISSUE TITLE
No tooltip displayed for Firefox account menu icon

### ISSUE THREAD

**Issue by Bianca-O** [mozilla/fx-private-relay#977]
**Build:**
Stage

**Affected platforms:**
Windows 10 64-bit
macOS 10.14 

**Browsers tested on:**
Firefox

**Steps to reproduce:**

1. Navigate to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net and log in using an existing account.
2. Hover over the Account icon.

**Actual result:**
There's no tooltip displayed for Account icon.

**Expected result:** 
Tooltip is displayed for Account icon.

![no tooltip for Firefox account menu](https://user-images.githubusercontent.com/79697848/127447449-7807e47b-3b18-4ff8-a9e4-1aad493fc7fa.gif)

**Comment by codemist** [comment]
Contacted Chris about what to add as the tooltip for this, he'll be getting back to me next week on Monday.

**Comment by AOiegas** [comment]
Verified this issue on stage, on Windows 10. The menu icon now displays a tooltip, more exactly it displays "Profile".
![image](https://user-images.githubusercontent.com/85748693/129524553-a4f12996-c8e7-4040-80ee-94f19c99c931.png)
