### ISSUE TITLE
Add reply to emails

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fx-private-relay#99]
I created an alias and sent myself an email from my personal gmail account.
The email redirected to my work account as expected, but I was unable to reply to the email and get the response to my personal gmail address.

@groovecoder said it was a known issue, but I didn't see an issue for it.

**Comment by groovecoder** [comment]
The fix here is to create a reply address for each sender to a relay address … so:

1. `sender@example.com` sends to `abcdef123@relay.firefox.com`
2. We create `zyxwvu987@relay.firefox.com` to send to `sender@example.com`
3. We put `Reply-To: zyxwvu987@relay.firefox.com` on the email when we send it
4. Real address of `abcdef...` replies
5. We receive the reply email for `zyxwvu987@relay.firefox.com` and relay it to `sender@example.com` with `Reply-To: abcdef123@relay.firefox.com`
6. We repeat steps 3-5 for as many emails as the participants send to each other

**Comment by jest** [comment]
This is a bit more complicated than described by @groovecoder, if you want to protect the privacy of the user replying to the e-mail. The real user's address might be revealed in some headers of the message, mainly `Received` — those should be removed at `relay.firefox.com` MX host I guess.

Also, to avoid the risk of being an open relay, you might consider creating a unique `Reply-To` address per-message, not per-original sender. Although this leads to ever-growing mapping UID -> address... Anyway, replying is harder than just receiving mail. :)

**Comment by jest** [comment]
I just checked, 33mail uses different Reply-to addresses for messages received from the same sender. So there must be some rationale behind it.

**Comment by xanoni** [comment]
One thing that would be important here is to at least attempt to filter out identifying information from the body and headers of the email that is quoted / responded to.

E.g., we don't want to real email address to appear ("On Jan 1st, 2021 real@email.com wrote:").

**Comment by githubacc02442** [comment]
Hope it is okay to ask here:
- Is the reply feature going to be for both premium and free users? or just premium users only?
- If we ever get a reply feature, please allow the generation of a reply/reverse alias on the extension.
- Will there be an increase in the attachment size? That 150kb really sucks if we ever receive important files. 
- I've seen a clip of the Privacy Pack costing $5/month for VPN and Relay. However, will users be allowed to purchase a Relay subscription only? If so, is there a price set for it currently, or not yet decided? Kinda pointless to purchase the pack if VPN isn't available in a user's country.

**Comment by tcinotto** [comment]
@githubacc02442 Thank you for the feedback! We'll be sharing out more details on the Replies feature very shortly and hope that you will enjoy the new experience! The additional feedback around attachment size and subscriptions, we hear you and are listening to your feedback on how to improve the experience, so please keep it coming. Please stay tuned as I think we'll have some exciting information coming soon.

**Comment by rafalkrupinski** [comment]
Hi, is there an update on this feature?

**Comment by Vinnl** [comment]
Apologies @rafalkrupinski, indeed replying is now available to Premium users. See https://relay.firefox.com/premium/

**Comment by rafalkrupinski** [comment]
Thank you @Vinnl , I was wondering if the ability to initiate conversations is planned.

**Comment by Vinnl** [comment]
At the current time, I believe it is not, as it avoids the masks being used for abuse (e.g. spam) - it's one argument we can use to keep Relay addresses off of blocklists. Possibly we'll be able to come up with other anti-abuse measures in the future that allow us to enable that functionality.
