### ISSUE TITLE
An alias name that is longer than the initial empty name field flickers when hovering over it

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#996]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Be signed in into a Firefox Relay account;
- Have a few aliases created;
- Have the stage version of the Private Relay add-on installed

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/accounts/profile/ ;
2. Name one of the created aliases with a maximum length name;
3. Hover over the set name field, from left to right, until exiting the name’s space;

#### Expected result:
- The alias name is shown without issue and the field highlights;

#### Actual result:
- The alias name field flickers and cuts the name;

#### Notes:
- The name field cuts back to its initial size then back to the full size of the set name when flickering;

![alias name bar](https://user-images.githubusercontent.com/85748693/128479764-e07268a1-d7ad-4932-928c-1d0d8d3296af.gif)

**Comment by Bianca-O** [comment]
This issue is verified as fixed on Stage under Windows 10 64 bit. The alias name is shown without issue and the field highlights. See new situation:
![new situation](https://user-images.githubusercontent.com/79697848/133401523-f6803d62-f9c1-4032-817e-b3266acd85a9.gif)
