### ISSUE TITLE
Comparing with the Figma References, there is a length of space missing from beneath message bars

### ISSUE THREAD

**Issue by AOiegas** [mozilla/fx-private-relay#999]
#### Build:
- Stage;

#### Affected Platforms:
- Windows 10, Android 9;

#### Browsers tested on:
- Firefox, latest version;

#### Prerequisites:
- Have a Private Relay account with the Mozilla Privacy Pack purchased;

#### Steps to reproduce:
1. Go to https://stage.fxprivaterelay.nonprod.cloudops.mozgcp.net/ ;
2. Sign in to the Private Relay;
3. Observe the successful message bar;

#### Expected result:
- The message bar appears correctly according to the Figma reference, spaced nicely between the Private Relay header and the Welcome/Alias Counter section;

#### Actual result:
- The message bar appears glued to the Welcome/Alias Counter section;

#### Notes:
- Even if it might not be considered an actual bug, aesthetically it affects a user. It just look nicer and tidier spaced correctly;
![image](https://user-images.githubusercontent.com/85748693/128520138-c23f9aa9-f58a-47d0-8ac1-61417b8abbe5.png)

Figma reference:
![space](https://user-images.githubusercontent.com/85748693/128520652-6e535af8-ebd4-4d49-9ecf-11e9c21bad43.png)

**Comment by codemist** [comment]
This is resolved in https://github.com/mozilla/fx-private-relay/pull/1001

**Comment by AOiegas** [comment]
Verified this issue on stage, on both Windows 10 and Android 9. The message box has a nicely fitted space below and above it.
